// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: active_sessions.sql

package sqlc

import (
	"context"
)

const allocateNextSeq = `-- name: AllocateNextSeq :one
UPDATE active_sessions
   SET last_seq = last_seq + 1
 WHERE org_id = $1
   AND thread_id = $2
   AND owner_replica = $3
RETURNING last_seq
`

type AllocateNextSeqParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	OwnerReplica string `json:"owner_replica"`
}

// Returns the next seq for events.Append. Bumping last_seq inside the
// same transaction as the event INSERT prevents two concurrent appenders
// from minting the same seq. The owner_replica guard ensures a
// partitioned-but-alive old owner cannot mint seqs after a takeover.
func (q *Queries) AllocateNextSeq(ctx context.Context, arg AllocateNextSeqParams) (int64, error) {
	row := q.db.QueryRow(ctx, allocateNextSeq, arg.OrgID, arg.ThreadID, arg.OwnerReplica)
	var last_seq int64
	err := row.Scan(&last_seq)
	return last_seq, err
}

const cancelActiveSession = `-- name: CancelActiveSession :execrows
UPDATE active_sessions
   SET cancelled = TRUE
 WHERE org_id = $1
   AND thread_id = $2
`

type CancelActiveSessionParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

// The cancel handler can be served by any replica. Setting the flag here
// causes the owner's renew loop (or the cancel-aware emitter check) to
// propagate the cancel locally. A recovery replica also reads this flag
// when scanning expired leases and skips re-attaching.
func (q *Queries) CancelActiveSession(ctx context.Context, arg CancelActiveSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelActiveSession, arg.OrgID, arg.ThreadID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimActiveSession = `-- name: ClaimActiveSession :one
INSERT INTO active_sessions (
    org_id, thread_id, request_id, owner_replica, lease_expires_at,
    sandbox_id, session_token, command_id, last_seq, cancelled, started_at
) VALUES (
    $1, $2, $3, $4, NOW() + ($5::int || ' seconds')::interval,
    '', '', '', 0, FALSE, NOW()
)
ON CONFLICT (org_id, thread_id) DO UPDATE SET
    request_id       = EXCLUDED.request_id,
    owner_replica    = EXCLUDED.owner_replica,
    lease_expires_at = EXCLUDED.lease_expires_at,
    cancelled        = FALSE
WHERE active_sessions.lease_expires_at < NOW()
RETURNING org_id, thread_id, request_id, owner_replica, lease_expires_at,
          sandbox_id, session_token, command_id, last_seq, cancelled, started_at
`

type ClaimActiveSessionParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	RequestID    string `json:"request_id"`
	OwnerReplica string `json:"owner_replica"`
	LeaseSeconds int32  `json:"lease_seconds"`
}

// Atomic lease acquisition. Wins when:
//
//	(a) no row exists for (org_id, thread_id), OR
//	(b) the existing row's lease_expires_at has passed (the previous
//	    owner crashed / shut down without releasing).
//
// Loses (returns 0 rows) when another replica still holds a live lease.
// The caller distinguishes these via pgx.ErrNoRows.
func (q *Queries) ClaimActiveSession(ctx context.Context, arg ClaimActiveSessionParams) (ActiveSession, error) {
	row := q.db.QueryRow(ctx, claimActiveSession,
		arg.OrgID,
		arg.ThreadID,
		arg.RequestID,
		arg.OwnerReplica,
		arg.LeaseSeconds,
	)
	var i ActiveSession
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.RequestID,
		&i.OwnerReplica,
		&i.LeaseExpiresAt,
		&i.SandboxID,
		&i.SessionToken,
		&i.CommandID,
		&i.LastSeq,
		&i.Cancelled,
		&i.StartedAt,
	)
	return i, err
}

const deleteCancelledActiveSessions = `-- name: DeleteCancelledActiveSessions :execrows
DELETE FROM active_sessions
 WHERE cancelled = TRUE
   AND lease_expires_at < NOW() - ($1::int || ' seconds')::interval
`

// Garbage-collect cancelled tombstones. The owner's Release path
// deletes its own rows, but a crash AFTER the cancel flag was flipped
// and BEFORE the owner's renew loop noticed leaves a permanent row —
// ListExpiredActiveSessions skips cancelled rows so recovery never
// claims them either. The cleanup tick in recovery.go invokes this
// with a grace window so a cancel-in-flight isn't deleted out from
// under its owner.
func (q *Queries) DeleteCancelledActiveSessions(ctx context.Context, graceSeconds int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCancelledActiveSessions, graceSeconds)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const expireActiveSession = `-- name: ExpireActiveSession :execrows
UPDATE active_sessions
   SET lease_expires_at = NOW()
 WHERE org_id = $1
   AND thread_id = $2
   AND owner_replica = $3
`

type ExpireActiveSessionParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	OwnerReplica string `json:"owner_replica"`
}

// Force the lease to expire NOW so a different replica can claim it
// without waiting for the natural expiry. Used by graceful shutdown when
// we want recovery to pick the turn up immediately on another pod.
func (q *Queries) ExpireActiveSession(ctx context.Context, arg ExpireActiveSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireActiveSession, arg.OrgID, arg.ThreadID, arg.OwnerReplica)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT org_id, thread_id, request_id, owner_replica, lease_expires_at,
       sandbox_id, session_token, command_id, last_seq, cancelled, started_at
FROM active_sessions
WHERE org_id = $1 AND thread_id = $2
`

type GetActiveSessionParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) GetActiveSession(ctx context.Context, arg GetActiveSessionParams) (ActiveSession, error) {
	row := q.db.QueryRow(ctx, getActiveSession, arg.OrgID, arg.ThreadID)
	var i ActiveSession
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.RequestID,
		&i.OwnerReplica,
		&i.LeaseExpiresAt,
		&i.SandboxID,
		&i.SessionToken,
		&i.CommandID,
		&i.LastSeq,
		&i.Cancelled,
		&i.StartedAt,
	)
	return i, err
}

const listExpiredActiveSessions = `-- name: ListExpiredActiveSessions :many
SELECT org_id, thread_id, request_id, owner_replica, lease_expires_at,
       sandbox_id, session_token, command_id, last_seq, cancelled, started_at
FROM active_sessions
WHERE lease_expires_at < NOW()
  AND cancelled = FALSE
ORDER BY lease_expires_at
LIMIT $1
FOR UPDATE SKIP LOCKED
`

// The recovery worker's scan target. FOR UPDATE SKIP LOCKED so multiple
// replicas can scan concurrently without blocking each other; LIMIT keeps
// a runaway recovery loop from claiming everything at once.
func (q *Queries) ListExpiredActiveSessions(ctx context.Context, lim int32) ([]ActiveSession, error) {
	rows, err := q.db.Query(ctx, listExpiredActiveSessions, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveSession
	for rows.Next() {
		var i ActiveSession
		if err := rows.Scan(
			&i.OrgID,
			&i.ThreadID,
			&i.RequestID,
			&i.OwnerReplica,
			&i.LeaseExpiresAt,
			&i.SandboxID,
			&i.SessionToken,
			&i.CommandID,
			&i.LastSeq,
			&i.Cancelled,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyActiveSessions = `-- name: ListMyActiveSessions :many
SELECT org_id, thread_id, request_id, owner_replica, lease_expires_at,
       sandbox_id, session_token, command_id, last_seq, cancelled, started_at
FROM active_sessions
WHERE owner_replica = $1
`

// Used during graceful shutdown to enumerate the leases this replica
// still holds, so we can expire each in turn before exiting.
func (q *Queries) ListMyActiveSessions(ctx context.Context, ownerReplica string) ([]ActiveSession, error) {
	rows, err := q.db.Query(ctx, listMyActiveSessions, ownerReplica)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ActiveSession
	for rows.Next() {
		var i ActiveSession
		if err := rows.Scan(
			&i.OrgID,
			&i.ThreadID,
			&i.RequestID,
			&i.OwnerReplica,
			&i.LeaseExpiresAt,
			&i.SandboxID,
			&i.SessionToken,
			&i.CommandID,
			&i.LastSeq,
			&i.Cancelled,
			&i.StartedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseActiveSession = `-- name: ReleaseActiveSession :exec
DELETE FROM active_sessions
 WHERE org_id = $1
   AND thread_id = $2
   AND owner_replica = $3
`

type ReleaseActiveSessionParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	OwnerReplica string `json:"owner_replica"`
}

// Owner-side terminal release. Either the turn finished cleanly or the
// replica is shutting down — drop the row so recovery does not pick it
// up as a stale lease.
func (q *Queries) ReleaseActiveSession(ctx context.Context, arg ReleaseActiveSessionParams) error {
	_, err := q.db.Exec(ctx, releaseActiveSession, arg.OrgID, arg.ThreadID, arg.OwnerReplica)
	return err
}

const renewActiveSession = `-- name: RenewActiveSession :execrows
UPDATE active_sessions
   SET lease_expires_at = NOW() + ($4::int || ' seconds')::interval
 WHERE org_id = $1
   AND thread_id = $2
   AND owner_replica = $3
`

type RenewActiveSessionParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	OwnerReplica string `json:"owner_replica"`
	LeaseSeconds int32  `json:"lease_seconds"`
}

// Refresh the lease while the owner is still alive. Returns 0 rows if
// another replica has stolen the lease (the owner column will not match),
// which the caller treats as "we lost ownership, abort".
func (q *Queries) RenewActiveSession(ctx context.Context, arg RenewActiveSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewActiveSession,
		arg.OrgID,
		arg.ThreadID,
		arg.OwnerReplica,
		arg.LeaseSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setActiveSessionSandbox = `-- name: SetActiveSessionSandbox :execrows
UPDATE active_sessions
   SET sandbox_id    = $3,
       session_token = $4,
       command_id    = $5
 WHERE org_id        = $1
   AND thread_id     = $2
   AND owner_replica = $6
`

type SetActiveSessionSandboxParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	SandboxID    string `json:"sandbox_id"`
	SessionToken string `json:"session_token"`
	CommandID    string `json:"command_id"`
	OwnerReplica string `json:"owner_replica"`
}

// Stamp the Daytona handle on the lease as soon as ExecuteSessionCommand
// returns. Without this, a recovery replica has no way to reattach to the
// running command after the owner crashes.
//
// The owner_replica guard prevents a delayed write from a crashed owner
// (or one that briefly partitioned away) from clobbering the handle a
// recovery replica has already stamped. Without the guard, recovery
// could end up attached to the wrong Daytona command.
func (q *Queries) SetActiveSessionSandbox(ctx context.Context, arg SetActiveSessionSandboxParams) (int64, error) {
	result, err := q.db.Exec(ctx, setActiveSessionSandbox,
		arg.OrgID,
		arg.ThreadID,
		arg.SandboxID,
		arg.SessionToken,
		arg.CommandID,
		arg.OwnerReplica,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const takeOverActiveSession = `-- name: TakeOverActiveSession :execrows
UPDATE active_sessions
   SET owner_replica    = $3,
       lease_expires_at = NOW() + ($4::int || ' seconds')::interval
 WHERE org_id = $1
   AND thread_id = $2
`

type TakeOverActiveSessionParams struct {
	OrgID        string `json:"org_id"`
	ThreadID     string `json:"thread_id"`
	OwnerReplica string `json:"owner_replica"`
	LeaseSeconds int32  `json:"lease_seconds"`
}

// Recovery worker: after ListExpiredActiveSessions returns a row inside a
// transaction, this writes the new owner + extends the lease before
// committing. Same transaction as the SELECT so SKIP LOCKED's row lock
// guards the handoff.
func (q *Queries) TakeOverActiveSession(ctx context.Context, arg TakeOverActiveSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, takeOverActiveSession,
		arg.OrgID,
		arg.ThreadID,
		arg.OwnerReplica,
		arg.LeaseSeconds,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
