// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAgentProfilesByOrg = `-- name: CountAgentProfilesByOrg :one
SELECT COUNT(*) FROM agent_profiles
WHERE org_id = $1
`

func (q *Queries) CountAgentProfilesByOrg(ctx context.Context, orgID string) (int64, error) {
	row := q.db.QueryRow(ctx, countAgentProfilesByOrg, orgID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const disableAgentProfile = `-- name: DisableAgentProfile :execrows
UPDATE agent_profiles
SET enabled = FALSE,
    updated_at = NOW()
WHERE org_id = $1
  AND slug = $2
`

type DisableAgentProfileParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

func (q *Queries) DisableAgentProfile(ctx context.Context, arg DisableAgentProfileParams) (int64, error) {
	result, err := q.db.Exec(ctx, disableAgentProfile, arg.OrgID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentProfileBySlug = `-- name: GetAgentProfileBySlug :one
SELECT
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    vault_backend,
    sx_bot_key_encrypted,
    template_slug,
    sync_status,
    sync_error,
    enabled,
    built_in,
    created_at,
    updated_at
FROM agent_profiles
WHERE org_id = $1 AND slug = $2
`

type GetAgentProfileBySlugParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

type GetAgentProfileBySlugRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             string             `json:"org_id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	SxBot             string             `json:"sx_bot"`
	PersonaAsset      string             `json:"persona_asset"`
	PersonaPrompt     string             `json:"persona_prompt"`
	SlackAliases      []string           `json:"slack_aliases"`
	Skills            []string           `json:"skills"`
	VaultBackend      string             `json:"vault_backend"`
	SxBotKeyEncrypted []byte             `json:"sx_bot_key_encrypted"`
	TemplateSlug      string             `json:"template_slug"`
	SyncStatus        string             `json:"sync_status"`
	SyncError         string             `json:"sync_error"`
	Enabled           bool               `json:"enabled"`
	BuiltIn           bool               `json:"built_in"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAgentProfileBySlug(ctx context.Context, arg GetAgentProfileBySlugParams) (GetAgentProfileBySlugRow, error) {
	row := q.db.QueryRow(ctx, getAgentProfileBySlug, arg.OrgID, arg.Slug)
	var i GetAgentProfileBySlugRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Skills,
		&i.VaultBackend,
		&i.SxBotKeyEncrypted,
		&i.TemplateSlug,
		&i.SyncStatus,
		&i.SyncError,
		&i.Enabled,
		&i.BuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentProfileTemplate = `-- name: GetAgentProfileTemplate :one
SELECT
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    enabled,
    created_at,
    updated_at
FROM agent_profile_templates
WHERE slug = $1 AND enabled
`

func (q *Queries) GetAgentProfileTemplate(ctx context.Context, slug string) (AgentProfileTemplate, error) {
	row := q.db.QueryRow(ctx, getAgentProfileTemplate, slug)
	var i AgentProfileTemplate
	err := row.Scan(
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Skills,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentProfileTemplates = `-- name: ListAgentProfileTemplates :many
SELECT
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    enabled,
    created_at,
    updated_at
FROM agent_profile_templates
WHERE enabled
ORDER BY slug
`

func (q *Queries) ListAgentProfileTemplates(ctx context.Context) ([]AgentProfileTemplate, error) {
	rows, err := q.db.Query(ctx, listAgentProfileTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentProfileTemplate
	for rows.Next() {
		var i AgentProfileTemplate
		if err := rows.Scan(
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.SxBot,
			&i.PersonaAsset,
			&i.PersonaPrompt,
			&i.SlackAliases,
			&i.Skills,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentProfilesByOrg = `-- name: ListAgentProfilesByOrg :many
SELECT
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    vault_backend,
    sx_bot_key_encrypted,
    template_slug,
    sync_status,
    sync_error,
    enabled,
    built_in,
    created_at,
    updated_at
FROM agent_profiles
WHERE org_id = $1
ORDER BY slug
`

type ListAgentProfilesByOrgRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             string             `json:"org_id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	SxBot             string             `json:"sx_bot"`
	PersonaAsset      string             `json:"persona_asset"`
	PersonaPrompt     string             `json:"persona_prompt"`
	SlackAliases      []string           `json:"slack_aliases"`
	Skills            []string           `json:"skills"`
	VaultBackend      string             `json:"vault_backend"`
	SxBotKeyEncrypted []byte             `json:"sx_bot_key_encrypted"`
	TemplateSlug      string             `json:"template_slug"`
	SyncStatus        string             `json:"sync_status"`
	SyncError         string             `json:"sync_error"`
	Enabled           bool               `json:"enabled"`
	BuiltIn           bool               `json:"built_in"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAgentProfilesByOrg(ctx context.Context, orgID string) ([]ListAgentProfilesByOrgRow, error) {
	rows, err := q.db.Query(ctx, listAgentProfilesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentProfilesByOrgRow
	for rows.Next() {
		var i ListAgentProfilesByOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.SxBot,
			&i.PersonaAsset,
			&i.PersonaPrompt,
			&i.SlackAliases,
			&i.Skills,
			&i.VaultBackend,
			&i.SxBotKeyEncrypted,
			&i.TemplateSlug,
			&i.SyncStatus,
			&i.SyncError,
			&i.Enabled,
			&i.BuiltIn,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const seedDefaultAgentProfilesForOrg = `-- name: SeedDefaultAgentProfilesForOrg :exec
INSERT INTO agent_profiles (
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    built_in,
    enabled
)
SELECT
    $1,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    TRUE,
    enabled
FROM agent_profile_templates
WHERE enabled
ON CONFLICT (org_id, slug) DO NOTHING
`

func (q *Queries) SeedDefaultAgentProfilesForOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, seedDefaultAgentProfilesForOrg, orgID)
	return err
}

const updateAgentProfileName = `-- name: UpdateAgentProfileName :one
UPDATE agent_profiles
SET
    display_name = $3,
    updated_at = NOW()
WHERE org_id = $1
  AND slug = $2
  AND enabled = TRUE
RETURNING
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    vault_backend,
    sx_bot_key_encrypted,
    template_slug,
    sync_status,
    sync_error,
    enabled,
    built_in,
    created_at,
    updated_at
`

type UpdateAgentProfileNameParams struct {
	OrgID       string `json:"org_id"`
	Slug        string `json:"slug"`
	DisplayName string `json:"display_name"`
}

type UpdateAgentProfileNameRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             string             `json:"org_id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	SxBot             string             `json:"sx_bot"`
	PersonaAsset      string             `json:"persona_asset"`
	PersonaPrompt     string             `json:"persona_prompt"`
	SlackAliases      []string           `json:"slack_aliases"`
	Skills            []string           `json:"skills"`
	VaultBackend      string             `json:"vault_backend"`
	SxBotKeyEncrypted []byte             `json:"sx_bot_key_encrypted"`
	TemplateSlug      string             `json:"template_slug"`
	SyncStatus        string             `json:"sync_status"`
	SyncError         string             `json:"sync_error"`
	Enabled           bool               `json:"enabled"`
	BuiltIn           bool               `json:"built_in"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAgentProfileName(ctx context.Context, arg UpdateAgentProfileNameParams) (UpdateAgentProfileNameRow, error) {
	row := q.db.QueryRow(ctx, updateAgentProfileName, arg.OrgID, arg.Slug, arg.DisplayName)
	var i UpdateAgentProfileNameRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Skills,
		&i.VaultBackend,
		&i.SxBotKeyEncrypted,
		&i.TemplateSlug,
		&i.SyncStatus,
		&i.SyncError,
		&i.Enabled,
		&i.BuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentProfileVaultSync = `-- name: UpdateAgentProfileVaultSync :one
UPDATE agent_profiles
SET
    vault_backend = $3,
    sx_bot_key_encrypted = $4,
    template_slug = $5,
    sync_status = $6,
    sync_error = $7,
    updated_at = NOW()
WHERE org_id = $1
  AND slug = $2
RETURNING
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    vault_backend,
    sx_bot_key_encrypted,
    template_slug,
    sync_status,
    sync_error,
    enabled,
    built_in,
    created_at,
    updated_at
`

type UpdateAgentProfileVaultSyncParams struct {
	OrgID             string `json:"org_id"`
	Slug              string `json:"slug"`
	VaultBackend      string `json:"vault_backend"`
	SxBotKeyEncrypted []byte `json:"sx_bot_key_encrypted"`
	TemplateSlug      string `json:"template_slug"`
	SyncStatus        string `json:"sync_status"`
	SyncError         string `json:"sync_error"`
}

type UpdateAgentProfileVaultSyncRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             string             `json:"org_id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	SxBot             string             `json:"sx_bot"`
	PersonaAsset      string             `json:"persona_asset"`
	PersonaPrompt     string             `json:"persona_prompt"`
	SlackAliases      []string           `json:"slack_aliases"`
	Skills            []string           `json:"skills"`
	VaultBackend      string             `json:"vault_backend"`
	SxBotKeyEncrypted []byte             `json:"sx_bot_key_encrypted"`
	TemplateSlug      string             `json:"template_slug"`
	SyncStatus        string             `json:"sync_status"`
	SyncError         string             `json:"sync_error"`
	Enabled           bool               `json:"enabled"`
	BuiltIn           bool               `json:"built_in"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAgentProfileVaultSync(ctx context.Context, arg UpdateAgentProfileVaultSyncParams) (UpdateAgentProfileVaultSyncRow, error) {
	row := q.db.QueryRow(ctx, updateAgentProfileVaultSync,
		arg.OrgID,
		arg.Slug,
		arg.VaultBackend,
		arg.SxBotKeyEncrypted,
		arg.TemplateSlug,
		arg.SyncStatus,
		arg.SyncError,
	)
	var i UpdateAgentProfileVaultSyncRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Skills,
		&i.VaultBackend,
		&i.SxBotKeyEncrypted,
		&i.TemplateSlug,
		&i.SyncStatus,
		&i.SyncError,
		&i.Enabled,
		&i.BuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAgentProfile = `-- name: UpsertAgentProfile :one
INSERT INTO agent_profiles (
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    built_in,
    enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (org_id, slug) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    description    = EXCLUDED.description,
    sx_bot         = EXCLUDED.sx_bot,
    persona_asset  = EXCLUDED.persona_asset,
    persona_prompt = EXCLUDED.persona_prompt,
    slack_aliases  = EXCLUDED.slack_aliases,
    skills         = EXCLUDED.skills,
    -- Seeded profiles stay marked built-in even after an admin renames their
    -- org copy; this flag records provenance and is intentionally monotonic.
    built_in       = agent_profiles.built_in OR EXCLUDED.built_in,
    enabled        = EXCLUDED.enabled,
    updated_at     = NOW()
RETURNING
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    skills,
    vault_backend,
    sx_bot_key_encrypted,
    template_slug,
    sync_status,
    sync_error,
    enabled,
    built_in,
    created_at,
    updated_at
`

type UpsertAgentProfileParams struct {
	OrgID         string   `json:"org_id"`
	Slug          string   `json:"slug"`
	DisplayName   string   `json:"display_name"`
	Description   string   `json:"description"`
	SxBot         string   `json:"sx_bot"`
	PersonaAsset  string   `json:"persona_asset"`
	PersonaPrompt string   `json:"persona_prompt"`
	SlackAliases  []string `json:"slack_aliases"`
	Skills        []string `json:"skills"`
	BuiltIn       bool     `json:"built_in"`
	Enabled       bool     `json:"enabled"`
}

type UpsertAgentProfileRow struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             string             `json:"org_id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	SxBot             string             `json:"sx_bot"`
	PersonaAsset      string             `json:"persona_asset"`
	PersonaPrompt     string             `json:"persona_prompt"`
	SlackAliases      []string           `json:"slack_aliases"`
	Skills            []string           `json:"skills"`
	VaultBackend      string             `json:"vault_backend"`
	SxBotKeyEncrypted []byte             `json:"sx_bot_key_encrypted"`
	TemplateSlug      string             `json:"template_slug"`
	SyncStatus        string             `json:"sync_status"`
	SyncError         string             `json:"sync_error"`
	Enabled           bool               `json:"enabled"`
	BuiltIn           bool               `json:"built_in"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertAgentProfile(ctx context.Context, arg UpsertAgentProfileParams) (UpsertAgentProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertAgentProfile,
		arg.OrgID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.SxBot,
		arg.PersonaAsset,
		arg.PersonaPrompt,
		arg.SlackAliases,
		arg.Skills,
		arg.BuiltIn,
		arg.Enabled,
	)
	var i UpsertAgentProfileRow
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Skills,
		&i.VaultBackend,
		&i.SxBotKeyEncrypted,
		&i.TemplateSlug,
		&i.SyncStatus,
		&i.SyncError,
		&i.Enabled,
		&i.BuiltIn,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
