// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAgentRunEvent = `-- name: AppendAgentRunEvent :one
WITH next_event AS (
    UPDATE agent_runs
       SET next_event_seq = next_event_seq + 1,
           heartbeat_at = NOW(),
           updated_at = NOW()
     WHERE id = $1
       AND lease_owner = $4
       AND state IN ('preparing', 'running', 'recovering', 'finalizing')
     RETURNING next_event_seq - 1 AS seq
)
INSERT INTO agent_run_events (run_id, seq, event, data)
SELECT $1, seq, $2, $3
FROM next_event
RETURNING seq
`

type AppendAgentRunEventParams struct {
	RunID      string `json:"run_id"`
	Event      string `json:"event"`
	Data       []byte `json:"data"`
	LeaseOwner string `json:"lease_owner"`
}

// Appends intentionally serialize per run on the agent_runs row lock so
// next_event_seq stays monotonic and replay order is deterministic.
func (q *Queries) AppendAgentRunEvent(ctx context.Context, arg AppendAgentRunEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendAgentRunEvent,
		arg.RunID,
		arg.Event,
		arg.Data,
		arg.LeaseOwner,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const claimAgentRunForCancel = `-- name: ClaimAgentRunForCancel :one
UPDATE agent_runs
   SET lease_owner = $2,
       lease_expires_at = NOW() + $3::interval,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at
`

type ClaimAgentRunForCancelParams struct {
	ID            string          `json:"id"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) ClaimAgentRunForCancel(ctx context.Context, arg ClaimAgentRunForCancelParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimAgentRunForCancel, arg.ID, arg.LeaseOwner, arg.LeaseDuration)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const claimAgentRunLease = `-- name: ClaimAgentRunLease :one
UPDATE agent_runs
   SET state = 'recovering',
       lease_owner = $2,
       lease_expires_at = NOW() + $3::interval,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND (lease_expires_at IS NULL OR lease_expires_at < NOW() OR lease_owner = $2)
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at
`

type ClaimAgentRunLeaseParams struct {
	ID            string          `json:"id"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) ClaimAgentRunLease(ctx context.Context, arg ClaimAgentRunLeaseParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimAgentRunLease, arg.ID, arg.LeaseOwner, arg.LeaseDuration)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (
    id, org_id, thread_id, run_kind, request_id, user_request,
    state, lease_owner, lease_expires_at, heartbeat_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    'preparing', $7, NOW() + $8::interval, NOW()
)
ON CONFLICT DO NOTHING
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at
`

type CreateAgentRunParams struct {
	ID            string          `json:"id"`
	OrgID         string          `json:"org_id"`
	ThreadID      string          `json:"thread_id"`
	RunKind       string          `json:"run_kind"`
	RequestID     string          `json:"request_id"`
	UserRequest   string          `json:"user_request"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, createAgentRun,
		arg.ID,
		arg.OrgID,
		arg.ThreadID,
		arg.RunKind,
		arg.RequestID,
		arg.UserRequest,
		arg.LeaseOwner,
		arg.LeaseDuration,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveAgentRunForThread = `-- name: GetActiveAgentRunForThread :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at
FROM agent_runs
WHERE org_id = $1 AND thread_id = $2
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
ORDER BY updated_at DESC
LIMIT 1
`

type GetActiveAgentRunForThreadParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) GetActiveAgentRunForThread(ctx context.Context, arg GetActiveAgentRunForThreadParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getActiveAgentRunForThread, arg.OrgID, arg.ThreadID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at
FROM agent_runs
WHERE id = $1
`

func (q *Queries) GetAgentRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentRunByRequest = `-- name: GetAgentRunByRequest :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at
FROM agent_runs
WHERE org_id = $1 AND request_id = $2
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type GetAgentRunByRequestParams struct {
	OrgID     string `json:"org_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) GetAgentRunByRequest(ctx context.Context, arg GetAgentRunByRequestParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRunByRequest, arg.OrgID, arg.RequestID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestAgentRunForThread = `-- name: GetLatestAgentRunForThread :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at
FROM agent_runs
WHERE org_id = $1 AND thread_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAgentRunForThreadParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) GetLatestAgentRunForThread(ctx context.Context, arg GetLatestAgentRunForThreadParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getLatestAgentRunForThread, arg.OrgID, arg.ThreadID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentRunEventsFromSeq = `-- name: ListAgentRunEventsFromSeq :many
SELECT run_id, seq, event, data, created_at
FROM agent_run_events
WHERE run_id = $1 AND seq > $2
ORDER BY seq ASC
`

type ListAgentRunEventsFromSeqParams struct {
	RunID string `json:"run_id"`
	Seq   int64  `json:"seq"`
}

func (q *Queries) ListAgentRunEventsFromSeq(ctx context.Context, arg ListAgentRunEventsFromSeqParams) ([]AgentRunEvent, error) {
	rows, err := q.db.Query(ctx, listAgentRunEventsFromSeq, arg.RunID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRunEvent
	for rows.Next() {
		var i AgentRunEvent
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAgentRuns = `-- name: ListExpiredAgentRuns :many
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at
FROM agent_runs
WHERE state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND (lease_expires_at IS NULL OR lease_expires_at < NOW())
ORDER BY updated_at ASC
LIMIT $1
`

func (q *Queries) ListExpiredAgentRuns(ctx context.Context, limit int32) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listExpiredAgentRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.RunKind,
			&i.RequestID,
			&i.SandboxID,
			&i.Branch,
			&i.UserRequest,
			&i.SessionID,
			&i.CommandID,
			&i.CommandStartSeq,
			&i.State,
			&i.LogCursor,
			&i.NextEventSeq,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentRunLease = `-- name: TouchAgentRunLease :exec
UPDATE agent_runs
   SET heartbeat_at = NOW(),
       lease_owner = $2,
       lease_expires_at = NOW() + $3::interval,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $2
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type TouchAgentRunLeaseParams struct {
	ID            string          `json:"id"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) TouchAgentRunLease(ctx context.Context, arg TouchAgentRunLeaseParams) error {
	_, err := q.db.Exec(ctx, touchAgentRunLease, arg.ID, arg.LeaseOwner, arg.LeaseDuration)
	return err
}

const updateAgentRunBranch = `-- name: UpdateAgentRunBranch :exec
UPDATE agent_runs
   SET branch = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunBranchParams struct {
	ID         string `json:"id"`
	Branch     string `json:"branch"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunBranch(ctx context.Context, arg UpdateAgentRunBranchParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunBranch, arg.ID, arg.Branch, arg.LeaseOwner)
	return err
}

const updateAgentRunCommand = `-- name: UpdateAgentRunCommand :exec
UPDATE agent_runs
   SET session_id = $2,
       command_id = $3,
       command_start_seq = next_event_seq,
       state = 'running',
       heartbeat_at = NOW(),
       lease_owner = $4,
       lease_expires_at = NOW() + $5::interval,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $4
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunCommandParams struct {
	ID            string          `json:"id"`
	SessionID     string          `json:"session_id"`
	CommandID     string          `json:"command_id"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) UpdateAgentRunCommand(ctx context.Context, arg UpdateAgentRunCommandParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunCommand,
		arg.ID,
		arg.SessionID,
		arg.CommandID,
		arg.LeaseOwner,
		arg.LeaseDuration,
	)
	return err
}

const updateAgentRunKind = `-- name: UpdateAgentRunKind :exec
UPDATE agent_runs
   SET run_kind = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunKindParams struct {
	ID         string `json:"id"`
	RunKind    string `json:"run_kind"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunKind(ctx context.Context, arg UpdateAgentRunKindParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunKind, arg.ID, arg.RunKind, arg.LeaseOwner)
	return err
}

const updateAgentRunLogCursor = `-- name: UpdateAgentRunLogCursor :exec
UPDATE agent_runs
   SET log_cursor = GREATEST(log_cursor, $2),
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunLogCursorParams struct {
	ID         string `json:"id"`
	LogCursor  int64  `json:"log_cursor"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunLogCursor(ctx context.Context, arg UpdateAgentRunLogCursorParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunLogCursor, arg.ID, arg.LogCursor, arg.LeaseOwner)
	return err
}

const updateAgentRunSandbox = `-- name: UpdateAgentRunSandbox :exec
UPDATE agent_runs
   SET sandbox_id = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunSandboxParams struct {
	ID         string `json:"id"`
	SandboxID  string `json:"sandbox_id"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunSandbox(ctx context.Context, arg UpdateAgentRunSandboxParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunSandbox, arg.ID, arg.SandboxID, arg.LeaseOwner)
	return err
}

const updateAgentRunSession = `-- name: UpdateAgentRunSession :exec
UPDATE agent_runs
   SET session_id = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunSessionParams struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunSession(ctx context.Context, arg UpdateAgentRunSessionParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunSession, arg.ID, arg.SessionID, arg.LeaseOwner)
	return err
}

const updateAgentRunState = `-- name: UpdateAgentRunState :exec
UPDATE agent_runs
   SET state = $2,
       last_error = $3,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $4
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunStateParams struct {
	ID         string `json:"id"`
	State      string `json:"state"`
	LastError  string `json:"last_error"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunState(ctx context.Context, arg UpdateAgentRunStateParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunState,
		arg.ID,
		arg.State,
		arg.LastError,
		arg.LeaseOwner,
	)
	return err
}
