// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agents.sql

package sqlc

import (
	"context"
)

const getAgentProfileBySlug = `-- name: GetAgentProfileBySlug :one
SELECT
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    enabled,
    created_at,
    updated_at
FROM agent_profiles
WHERE org_id = $1 AND slug = $2
`

type GetAgentProfileBySlugParams struct {
	OrgID string `json:"org_id"`
	Slug  string `json:"slug"`
}

func (q *Queries) GetAgentProfileBySlug(ctx context.Context, arg GetAgentProfileBySlugParams) (AgentProfile, error) {
	row := q.db.QueryRow(ctx, getAgentProfileBySlug, arg.OrgID, arg.Slug)
	var i AgentProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentProfilesByOrg = `-- name: ListAgentProfilesByOrg :many
SELECT
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    enabled,
    created_at,
    updated_at
FROM agent_profiles
WHERE org_id = $1
ORDER BY slug
`

func (q *Queries) ListAgentProfilesByOrg(ctx context.Context, orgID string) ([]AgentProfile, error) {
	rows, err := q.db.Query(ctx, listAgentProfilesByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentProfile
	for rows.Next() {
		var i AgentProfile
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.SxBot,
			&i.PersonaAsset,
			&i.PersonaPrompt,
			&i.SlackAliases,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentProfile = `-- name: UpsertAgentProfile :one
INSERT INTO agent_profiles (
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (org_id, slug) DO UPDATE SET
    display_name   = EXCLUDED.display_name,
    description    = EXCLUDED.description,
    sx_bot         = EXCLUDED.sx_bot,
    persona_asset  = EXCLUDED.persona_asset,
    persona_prompt = EXCLUDED.persona_prompt,
    slack_aliases  = EXCLUDED.slack_aliases,
    enabled        = EXCLUDED.enabled,
    updated_at     = NOW()
RETURNING
    id,
    org_id,
    slug,
    display_name,
    description,
    sx_bot,
    persona_asset,
    persona_prompt,
    slack_aliases,
    enabled,
    created_at,
    updated_at
`

type UpsertAgentProfileParams struct {
	OrgID         string   `json:"org_id"`
	Slug          string   `json:"slug"`
	DisplayName   string   `json:"display_name"`
	Description   string   `json:"description"`
	SxBot         string   `json:"sx_bot"`
	PersonaAsset  string   `json:"persona_asset"`
	PersonaPrompt string   `json:"persona_prompt"`
	SlackAliases  []string `json:"slack_aliases"`
	Enabled       bool     `json:"enabled"`
}

func (q *Queries) UpsertAgentProfile(ctx context.Context, arg UpsertAgentProfileParams) (AgentProfile, error) {
	row := q.db.QueryRow(ctx, upsertAgentProfile,
		arg.OrgID,
		arg.Slug,
		arg.DisplayName,
		arg.Description,
		arg.SxBot,
		arg.PersonaAsset,
		arg.PersonaPrompt,
		arg.SlackAliases,
		arg.Enabled,
	)
	var i AgentProfile
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.SxBot,
		&i.PersonaAsset,
		&i.PersonaPrompt,
		&i.SlackAliases,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
