// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_runs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendAgentRunEvent = `-- name: AppendAgentRunEvent :one
WITH next_event AS (
    UPDATE agent_runs
       SET next_event_seq = next_event_seq + 1,
           heartbeat_at = NOW(),
           updated_at = NOW()
     WHERE id = $1
       AND lease_owner = $4
       AND state IN ('preparing', 'running', 'recovering', 'finalizing', 'succeeded', 'failed', 'cancelled')
     RETURNING next_event_seq - 1 AS seq
)
INSERT INTO agent_run_events (run_id, seq, event, data)
SELECT $1, seq, $2, $3
FROM next_event
RETURNING seq
`

type AppendAgentRunEventParams struct {
	RunID      string `json:"run_id"`
	Event      string `json:"event"`
	Data       []byte `json:"data"`
	LeaseOwner string `json:"lease_owner"`
}

// Appends intentionally serialize per run on the agent_runs row lock so
// next_event_seq stays monotonic and replay order is deterministic.
func (q *Queries) AppendAgentRunEvent(ctx context.Context, arg AppendAgentRunEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, appendAgentRunEvent,
		arg.RunID,
		arg.Event,
		arg.Data,
		arg.LeaseOwner,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const claimAgentRunForCancel = `-- name: ClaimAgentRunForCancel :one
UPDATE agent_runs
   SET lease_owner = $2,
       lease_expires_at = NOW() + $3::interval,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
`

type ClaimAgentRunForCancelParams struct {
	ID            string          `json:"id"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) ClaimAgentRunForCancel(ctx context.Context, arg ClaimAgentRunForCancelParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimAgentRunForCancel, arg.ID, arg.LeaseOwner, arg.LeaseDuration)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const claimAgentRunLease = `-- name: ClaimAgentRunLease :one
UPDATE agent_runs
   SET state = 'recovering',
       lease_owner = $1,
       lease_expires_at = NOW() + $2::interval,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND (lease_expires_at IS NULL OR lease_expires_at < NOW() OR lease_owner = $1)
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
`

type ClaimAgentRunLeaseParams struct {
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
	ID            string          `json:"id"`
}

func (q *Queries) ClaimAgentRunLease(ctx context.Context, arg ClaimAgentRunLeaseParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimAgentRunLease, arg.LeaseOwner, arg.LeaseDuration, arg.ID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const claimAgentRunLeaseFromOwner = `-- name: ClaimAgentRunLeaseFromOwner :one
UPDATE agent_runs
   SET state = 'recovering',
       lease_owner = $1,
       lease_expires_at = NOW() + $2::interval,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $3
  AND lease_owner = $4
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
`

type ClaimAgentRunLeaseFromOwnerParams struct {
	LeaseOwner         string          `json:"lease_owner"`
	LeaseDuration      pgtype.Interval `json:"lease_duration"`
	ID                 string          `json:"id"`
	PreviousLeaseOwner string          `json:"previous_lease_owner"`
}

func (q *Queries) ClaimAgentRunLeaseFromOwner(ctx context.Context, arg ClaimAgentRunLeaseFromOwnerParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimAgentRunLeaseFromOwner,
		arg.LeaseOwner,
		arg.LeaseDuration,
		arg.ID,
		arg.PreviousLeaseOwner,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const claimStaleAgentRunLease = `-- name: ClaimStaleAgentRunLease :one
UPDATE agent_runs
   SET state = 'recovering',
       lease_owner = $1,
       lease_expires_at = NOW() + $2::interval,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND lease_owner <> $1
  AND (heartbeat_at IS NULL OR heartbeat_at < NOW() - $4::interval)
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
`

type ClaimStaleAgentRunLeaseParams struct {
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
	ID            string          `json:"id"`
	StaleAfter    pgtype.Interval `json:"stale_after"`
}

func (q *Queries) ClaimStaleAgentRunLease(ctx context.Context, arg ClaimStaleAgentRunLeaseParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, claimStaleAgentRunLease,
		arg.LeaseOwner,
		arg.LeaseDuration,
		arg.ID,
		arg.StaleAfter,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const createAgentRun = `-- name: CreateAgentRun :one
INSERT INTO agent_runs (
    id, org_id, thread_id, run_kind, request_id,
    trigger_source, job_id, job_execution_id, user_request,
    state, lease_owner, lease_expires_at, heartbeat_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9,
    'preparing', $10, NOW() + $11::interval, NOW()
)
ON CONFLICT DO NOTHING
RETURNING id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
          user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
          lease_owner, lease_expires_at, heartbeat_at, last_error,
          created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
`

type CreateAgentRunParams struct {
	ID             string          `json:"id"`
	OrgID          string          `json:"org_id"`
	ThreadID       string          `json:"thread_id"`
	RunKind        string          `json:"run_kind"`
	RequestID      string          `json:"request_id"`
	TriggerSource  string          `json:"trigger_source"`
	JobID          *string         `json:"job_id"`
	JobExecutionID *string         `json:"job_execution_id"`
	UserRequest    string          `json:"user_request"`
	LeaseOwner     string          `json:"lease_owner"`
	LeaseDuration  pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) CreateAgentRun(ctx context.Context, arg CreateAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, createAgentRun,
		arg.ID,
		arg.OrgID,
		arg.ThreadID,
		arg.RunKind,
		arg.RequestID,
		arg.TriggerSource,
		arg.JobID,
		arg.JobExecutionID,
		arg.UserRequest,
		arg.LeaseOwner,
		arg.LeaseDuration,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const getActiveAgentRunForThread = `-- name: GetActiveAgentRunForThread :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE org_id = $1 AND thread_id = $2
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
ORDER BY updated_at DESC
LIMIT 1
`

type GetActiveAgentRunForThreadParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) GetActiveAgentRunForThread(ctx context.Context, arg GetActiveAgentRunForThreadParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getActiveAgentRunForThread, arg.OrgID, arg.ThreadID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE id = $1
`

func (q *Queries) GetAgentRun(ctx context.Context, id string) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const getAgentRunByRequest = `-- name: GetAgentRunByRequest :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE org_id = $1 AND request_id = $2
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type GetAgentRunByRequestParams struct {
	OrgID     string `json:"org_id"`
	RequestID string `json:"request_id"`
}

func (q *Queries) GetAgentRunByRequest(ctx context.Context, arg GetAgentRunByRequestParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRunByRequest, arg.OrgID, arg.RequestID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const getLatestAgentRunForThread = `-- name: GetLatestAgentRunForThread :one
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE org_id = $1 AND thread_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAgentRunForThreadParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) GetLatestAgentRunForThread(ctx context.Context, arg GetLatestAgentRunForThreadParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getLatestAgentRunForThread, arg.OrgID, arg.ThreadID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.RunKind,
		&i.RequestID,
		&i.SandboxID,
		&i.Branch,
		&i.UserRequest,
		&i.SessionID,
		&i.CommandID,
		&i.CommandStartSeq,
		&i.State,
		&i.LogCursor,
		&i.NextEventSeq,
		&i.LeaseOwner,
		&i.LeaseExpiresAt,
		&i.HeartbeatAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CommandStep,
		&i.Outcome,
		&i.OutcomeDetail,
		&i.QualityScore,
		&i.TriggerSource,
		&i.JobID,
		&i.JobExecutionID,
	)
	return i, err
}

const listActiveAgentRunsForLeaseOwnerPrefix = `-- name: ListActiveAgentRunsForLeaseOwnerPrefix :many
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND LEFT(lease_owner, LENGTH($1::text)) = $1::text
ORDER BY updated_at ASC
LIMIT $2
`

type ListActiveAgentRunsForLeaseOwnerPrefixParams struct {
	LeaseOwnerPrefix string `json:"lease_owner_prefix"`
	LimitCount       int32  `json:"limit_count"`
}

func (q *Queries) ListActiveAgentRunsForLeaseOwnerPrefix(ctx context.Context, arg ListActiveAgentRunsForLeaseOwnerPrefixParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listActiveAgentRunsForLeaseOwnerPrefix, arg.LeaseOwnerPrefix, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.RunKind,
			&i.RequestID,
			&i.SandboxID,
			&i.Branch,
			&i.UserRequest,
			&i.SessionID,
			&i.CommandID,
			&i.CommandStartSeq,
			&i.State,
			&i.LogCursor,
			&i.NextEventSeq,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommandStep,
			&i.Outcome,
			&i.OutcomeDetail,
			&i.QualityScore,
			&i.TriggerSource,
			&i.JobID,
			&i.JobExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentRunEventsFromSeq = `-- name: ListAgentRunEventsFromSeq :many
SELECT run_id, seq, event, data, created_at
FROM agent_run_events
WHERE run_id = $1 AND seq > $2
ORDER BY seq ASC
LIMIT $3
`

type ListAgentRunEventsFromSeqParams struct {
	RunID string `json:"run_id"`
	Seq   int64  `json:"seq"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListAgentRunEventsFromSeq(ctx context.Context, arg ListAgentRunEventsFromSeqParams) ([]AgentRunEvent, error) {
	rows, err := q.db.Query(ctx, listAgentRunEventsFromSeq, arg.RunID, arg.Seq, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRunEvent
	for rows.Next() {
		var i AgentRunEvent
		if err := rows.Scan(
			&i.RunID,
			&i.Seq,
			&i.Event,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredAgentRuns = `-- name: ListExpiredAgentRuns :many
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND (lease_expires_at IS NULL OR lease_expires_at < NOW())
ORDER BY updated_at ASC
LIMIT $1
`

func (q *Queries) ListExpiredAgentRuns(ctx context.Context, limit int32) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listExpiredAgentRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.RunKind,
			&i.RequestID,
			&i.SandboxID,
			&i.Branch,
			&i.UserRequest,
			&i.SessionID,
			&i.CommandID,
			&i.CommandStartSeq,
			&i.State,
			&i.LogCursor,
			&i.NextEventSeq,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommandStep,
			&i.Outcome,
			&i.OutcomeDetail,
			&i.QualityScore,
			&i.TriggerSource,
			&i.JobID,
			&i.JobExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAgentRunsForThreads = `-- name: ListLatestAgentRunsForThreads :many
SELECT DISTINCT ON (thread_id)
       id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE org_id = $1
  AND thread_id = ANY($2::text[])
ORDER BY thread_id, created_at DESC
`

type ListLatestAgentRunsForThreadsParams struct {
	OrgID     string   `json:"org_id"`
	ThreadIds []string `json:"thread_ids"`
}

func (q *Queries) ListLatestAgentRunsForThreads(ctx context.Context, arg ListLatestAgentRunsForThreadsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listLatestAgentRunsForThreads, arg.OrgID, arg.ThreadIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.RunKind,
			&i.RequestID,
			&i.SandboxID,
			&i.Branch,
			&i.UserRequest,
			&i.SessionID,
			&i.CommandID,
			&i.CommandStartSeq,
			&i.State,
			&i.LogCursor,
			&i.NextEventSeq,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommandStep,
			&i.Outcome,
			&i.OutcomeDetail,
			&i.QualityScore,
			&i.TriggerSource,
			&i.JobID,
			&i.JobExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleAgentRuns = `-- name: ListStaleAgentRuns :many
SELECT id, org_id, thread_id, run_kind, request_id, sandbox_id, branch,
       user_request, session_id, command_id, command_start_seq, state, log_cursor, next_event_seq,
       lease_owner, lease_expires_at, heartbeat_at, last_error,
       created_at, updated_at, command_step, outcome, outcome_detail, quality_score, trigger_source, job_id, job_execution_id
FROM agent_runs
WHERE state IN ('preparing', 'running', 'recovering', 'finalizing')
  AND (heartbeat_at IS NULL OR heartbeat_at < NOW() - $1::interval)
ORDER BY heartbeat_at ASC NULLS FIRST, updated_at ASC
LIMIT $2
`

type ListStaleAgentRunsParams struct {
	StaleAfter pgtype.Interval `json:"stale_after"`
	LimitCount int32           `json:"limit_count"`
}

func (q *Queries) ListStaleAgentRuns(ctx context.Context, arg ListStaleAgentRunsParams) ([]AgentRun, error) {
	rows, err := q.db.Query(ctx, listStaleAgentRuns, arg.StaleAfter, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentRun
	for rows.Next() {
		var i AgentRun
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.RunKind,
			&i.RequestID,
			&i.SandboxID,
			&i.Branch,
			&i.UserRequest,
			&i.SessionID,
			&i.CommandID,
			&i.CommandStartSeq,
			&i.State,
			&i.LogCursor,
			&i.NextEventSeq,
			&i.LeaseOwner,
			&i.LeaseExpiresAt,
			&i.HeartbeatAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CommandStep,
			&i.Outcome,
			&i.OutcomeDetail,
			&i.QualityScore,
			&i.TriggerSource,
			&i.JobID,
			&i.JobExecutionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAgentRunLease = `-- name: TouchAgentRunLease :exec
UPDATE agent_runs
   SET heartbeat_at = NOW(),
       lease_owner = $2,
       lease_expires_at = NOW() + $3::interval,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $2
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type TouchAgentRunLeaseParams struct {
	ID            string          `json:"id"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) TouchAgentRunLease(ctx context.Context, arg TouchAgentRunLeaseParams) error {
	_, err := q.db.Exec(ctx, touchAgentRunLease, arg.ID, arg.LeaseOwner, arg.LeaseDuration)
	return err
}

const updateAgentRunBranch = `-- name: UpdateAgentRunBranch :exec
UPDATE agent_runs
   SET branch = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunBranchParams struct {
	ID         string `json:"id"`
	Branch     string `json:"branch"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunBranch(ctx context.Context, arg UpdateAgentRunBranchParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunBranch, arg.ID, arg.Branch, arg.LeaseOwner)
	return err
}

const updateAgentRunCommand = `-- name: UpdateAgentRunCommand :exec
UPDATE agent_runs
   SET session_id = $2,
       command_id = $3,
       command_step = $4,
       command_start_seq = next_event_seq,
       state = 'running',
       heartbeat_at = NOW(),
       lease_owner = $5,
       lease_expires_at = NOW() + $6::interval,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $5
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunCommandParams struct {
	ID            string          `json:"id"`
	SessionID     string          `json:"session_id"`
	CommandID     string          `json:"command_id"`
	CommandStep   string          `json:"command_step"`
	LeaseOwner    string          `json:"lease_owner"`
	LeaseDuration pgtype.Interval `json:"lease_duration"`
}

func (q *Queries) UpdateAgentRunCommand(ctx context.Context, arg UpdateAgentRunCommandParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunCommand,
		arg.ID,
		arg.SessionID,
		arg.CommandID,
		arg.CommandStep,
		arg.LeaseOwner,
		arg.LeaseDuration,
	)
	return err
}

const updateAgentRunKind = `-- name: UpdateAgentRunKind :exec
UPDATE agent_runs
   SET run_kind = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunKindParams struct {
	ID         string `json:"id"`
	RunKind    string `json:"run_kind"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunKind(ctx context.Context, arg UpdateAgentRunKindParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunKind, arg.ID, arg.RunKind, arg.LeaseOwner)
	return err
}

const updateAgentRunLogCursor = `-- name: UpdateAgentRunLogCursor :exec
UPDATE agent_runs
   SET log_cursor = GREATEST(log_cursor, $2),
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunLogCursorParams struct {
	ID         string `json:"id"`
	LogCursor  int64  `json:"log_cursor"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunLogCursor(ctx context.Context, arg UpdateAgentRunLogCursorParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunLogCursor, arg.ID, arg.LogCursor, arg.LeaseOwner)
	return err
}

const updateAgentRunOutcome = `-- name: UpdateAgentRunOutcome :exec
UPDATE agent_runs
   SET outcome = $2,
       outcome_detail = $3,
       quality_score = $4,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $5
  AND state IN ('preparing', 'running', 'recovering', 'finalizing', 'succeeded', 'failed', 'cancelled')
`

type UpdateAgentRunOutcomeParams struct {
	ID            string `json:"id"`
	Outcome       string `json:"outcome"`
	OutcomeDetail []byte `json:"outcome_detail"`
	QualityScore  *int32 `json:"quality_score"`
	LeaseOwner    string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunOutcome(ctx context.Context, arg UpdateAgentRunOutcomeParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunOutcome,
		arg.ID,
		arg.Outcome,
		arg.OutcomeDetail,
		arg.QualityScore,
		arg.LeaseOwner,
	)
	return err
}

const updateAgentRunSandbox = `-- name: UpdateAgentRunSandbox :exec
UPDATE agent_runs
   SET sandbox_id = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunSandboxParams struct {
	ID         string `json:"id"`
	SandboxID  string `json:"sandbox_id"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunSandbox(ctx context.Context, arg UpdateAgentRunSandboxParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunSandbox, arg.ID, arg.SandboxID, arg.LeaseOwner)
	return err
}

const updateAgentRunSession = `-- name: UpdateAgentRunSession :exec
UPDATE agent_runs
   SET session_id = $2,
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $3
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunSessionParams struct {
	ID         string `json:"id"`
	SessionID  string `json:"session_id"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunSession(ctx context.Context, arg UpdateAgentRunSessionParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunSession, arg.ID, arg.SessionID, arg.LeaseOwner)
	return err
}

const updateAgentRunState = `-- name: UpdateAgentRunState :exec
UPDATE agent_runs
   SET state = $2,
       last_error = $3,
       heartbeat_at = NOW(),
       updated_at = NOW()
WHERE id = $1
  AND lease_owner = $4
  AND state IN ('preparing', 'running', 'recovering', 'finalizing')
`

type UpdateAgentRunStateParams struct {
	ID         string `json:"id"`
	State      string `json:"state"`
	LastError  string `json:"last_error"`
	LeaseOwner string `json:"lease_owner"`
}

func (q *Queries) UpdateAgentRunState(ctx context.Context, arg UpdateAgentRunStateParams) error {
	_, err := q.db.Exec(ctx, updateAgentRunState,
		arg.ID,
		arg.State,
		arg.LastError,
		arg.LeaseOwner,
	)
	return err
}
