// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlc

import (
	"context"
)

const createOrgAPIKey = `-- name: CreateOrgAPIKey :one
INSERT INTO org_api_keys (
    id, org_id, name, key_prefix, key_hash, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, org_id, name, key_prefix, key_hash, created_by,
          created_at, last_used_at, revoked_at
`

type CreateOrgAPIKeyParams struct {
	ID        string `json:"id"`
	OrgID     string `json:"org_id"`
	Name      string `json:"name"`
	KeyPrefix string `json:"key_prefix"`
	KeyHash   []byte `json:"key_hash"`
	CreatedBy string `json:"created_by"`
}

func (q *Queries) CreateOrgAPIKey(ctx context.Context, arg CreateOrgAPIKeyParams) (OrgApiKey, error) {
	row := q.db.QueryRow(ctx, createOrgAPIKey,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.CreatedBy,
	)
	var i OrgApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteOrgAPIKeysByOrg = `-- name: DeleteOrgAPIKeysByOrg :exec
DELETE FROM org_api_keys WHERE org_id = $1
`

func (q *Queries) DeleteOrgAPIKeysByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteOrgAPIKeysByOrg, orgID)
	return err
}

const getOrgAPIKeyByHash = `-- name: GetOrgAPIKeyByHash :one
SELECT id, org_id, name, key_prefix, key_hash, created_by,
       created_at, last_used_at, revoked_at
FROM org_api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) GetOrgAPIKeyByHash(ctx context.Context, keyHash []byte) (OrgApiKey, error) {
	row := q.db.QueryRow(ctx, getOrgAPIKeyByHash, keyHash)
	var i OrgApiKey
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listOrgAPIKeys = `-- name: ListOrgAPIKeys :many
SELECT id, org_id, name, key_prefix, key_hash, created_by,
       created_at, last_used_at, revoked_at
FROM org_api_keys
WHERE org_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListOrgAPIKeys(ctx context.Context, orgID string) ([]OrgApiKey, error) {
	rows, err := q.db.Query(ctx, listOrgAPIKeys, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgApiKey
	for rows.Next() {
		var i OrgApiKey
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOrgAPIKey = `-- name: RevokeOrgAPIKey :execrows
UPDATE org_api_keys
   SET revoked_at = NOW()
WHERE org_id = $1 AND id = $2 AND revoked_at IS NULL
`

type RevokeOrgAPIKeyParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) RevokeOrgAPIKey(ctx context.Context, arg RevokeOrgAPIKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeOrgAPIKey, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchOrgAPIKeyLastUsed = `-- name: TouchOrgAPIKeyLastUsed :exec
UPDATE org_api_keys
   SET last_used_at = NOW()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) TouchOrgAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchOrgAPIKeyLastUsed, id)
	return err
}
