// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: billing.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRepoBillingSetting = `-- name: DeleteRepoBillingSetting :exec
DELETE FROM repo_billing_settings
WHERE org_id = $1 AND github_owner = $2 AND github_repo = $3
`

type DeleteRepoBillingSettingParams struct {
	OrgID       string `json:"org_id"`
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
}

func (q *Queries) DeleteRepoBillingSetting(ctx context.Context, arg DeleteRepoBillingSettingParams) error {
	_, err := q.db.Exec(ctx, deleteRepoBillingSetting, arg.OrgID, arg.GithubOwner, arg.GithubRepo)
	return err
}

const ensureBillingAccount = `-- name: EnsureBillingAccount :one
INSERT INTO billing_accounts (org_id)
VALUES ($1)
ON CONFLICT (org_id) DO UPDATE SET org_id = EXCLUDED.org_id
RETURNING org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
          current_period_start, current_period_end,
          included_credits, included_credits_used, topup_credits,
          max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
          created_at, updated_at
`

func (q *Queries) EnsureBillingAccount(ctx context.Context, orgID string) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, ensureBillingAccount, orgID)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureBillingTopupSettings = `-- name: EnsureBillingTopupSettings :one
INSERT INTO billing_topup_settings (org_id)
VALUES ($1)
ON CONFLICT (org_id) DO UPDATE SET org_id = EXCLUDED.org_id
RETURNING org_id, auto_topup_enabled, trigger_threshold, target_balance,
          monthly_max_units, monthly_units_used, monthly_anchor_month,
          created_at, updated_at
`

func (q *Queries) EnsureBillingTopupSettings(ctx context.Context, orgID string) (BillingTopupSetting, error) {
	row := q.db.QueryRow(ctx, ensureBillingTopupSettings, orgID)
	var i BillingTopupSetting
	err := row.Scan(
		&i.OrgID,
		&i.AutoTopupEnabled,
		&i.TriggerThreshold,
		&i.TargetBalance,
		&i.MonthlyMaxUnits,
		&i.MonthlyUnitsUsed,
		&i.MonthlyAnchorMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const finalizeBillingRunMeter = `-- name: FinalizeBillingRunMeter :one
UPDATE billing_run_meters
   SET ended_at = $2,
       billable_minutes = $3,
       captured_credits = $4,
       terminal_state = $5,
       updated_at = NOW()
WHERE run_id = $1
RETURNING run_id, org_id, flavor, multiplier, sandbox_vcpu, sandbox_memory_gib,
          sandbox_disk_gib, started_at, ended_at, billable_minutes,
          captured_credits, terminal_state, created_at, updated_at
`

type FinalizeBillingRunMeterParams struct {
	RunID           string             `json:"run_id"`
	EndedAt         pgtype.Timestamptz `json:"ended_at"`
	BillableMinutes int32              `json:"billable_minutes"`
	CapturedCredits int32              `json:"captured_credits"`
	TerminalState   string             `json:"terminal_state"`
}

func (q *Queries) FinalizeBillingRunMeter(ctx context.Context, arg FinalizeBillingRunMeterParams) (BillingRunMeter, error) {
	row := q.db.QueryRow(ctx, finalizeBillingRunMeter,
		arg.RunID,
		arg.EndedAt,
		arg.BillableMinutes,
		arg.CapturedCredits,
		arg.TerminalState,
	)
	var i BillingRunMeter
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.Flavor,
		&i.Multiplier,
		&i.SandboxVcpu,
		&i.SandboxMemoryGib,
		&i.SandboxDiskGib,
		&i.StartedAt,
		&i.EndedAt,
		&i.BillableMinutes,
		&i.CapturedCredits,
		&i.TerminalState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingAccount = `-- name: GetBillingAccount :one
SELECT org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
       current_period_start, current_period_end,
       included_credits, included_credits_used, topup_credits,
       max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
       created_at, updated_at
FROM billing_accounts
WHERE org_id = $1
`

func (q *Queries) GetBillingAccount(ctx context.Context, orgID string) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccount, orgID)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingAccountByStripeCustomer = `-- name: GetBillingAccountByStripeCustomer :one
SELECT org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
       current_period_start, current_period_end,
       included_credits, included_credits_used, topup_credits,
       max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
       created_at, updated_at
FROM billing_accounts
WHERE stripe_customer_id = $1
`

func (q *Queries) GetBillingAccountByStripeCustomer(ctx context.Context, stripeCustomerID string) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccountByStripeCustomer, stripeCustomerID)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingCreditReservation = `-- name: GetBillingCreditReservation :one
SELECT run_id, org_id, reserved_credits, from_included_credits, from_topup_credits,
       captured_credits, released_credits, status, created_at, updated_at
FROM billing_credit_reservations
WHERE run_id = $1
`

func (q *Queries) GetBillingCreditReservation(ctx context.Context, runID string) (BillingCreditReservation, error) {
	row := q.db.QueryRow(ctx, getBillingCreditReservation, runID)
	var i BillingCreditReservation
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.ReservedCredits,
		&i.FromIncludedCredits,
		&i.FromTopupCredits,
		&i.CapturedCredits,
		&i.ReleasedCredits,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingCreditReservationForUpdate = `-- name: GetBillingCreditReservationForUpdate :one
SELECT run_id, org_id, reserved_credits, from_included_credits, from_topup_credits,
       captured_credits, released_credits, status, created_at, updated_at
FROM billing_credit_reservations
WHERE run_id = $1
FOR UPDATE
`

func (q *Queries) GetBillingCreditReservationForUpdate(ctx context.Context, runID string) (BillingCreditReservation, error) {
	row := q.db.QueryRow(ctx, getBillingCreditReservationForUpdate, runID)
	var i BillingCreditReservation
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.ReservedCredits,
		&i.FromIncludedCredits,
		&i.FromTopupCredits,
		&i.CapturedCredits,
		&i.ReleasedCredits,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingRunMeterForUpdate = `-- name: GetBillingRunMeterForUpdate :one
SELECT run_id, org_id, flavor, multiplier, sandbox_vcpu, sandbox_memory_gib,
       sandbox_disk_gib, started_at, ended_at, billable_minutes,
       captured_credits, terminal_state, created_at, updated_at
FROM billing_run_meters
WHERE run_id = $1
FOR UPDATE
`

func (q *Queries) GetBillingRunMeterForUpdate(ctx context.Context, runID string) (BillingRunMeter, error) {
	row := q.db.QueryRow(ctx, getBillingRunMeterForUpdate, runID)
	var i BillingRunMeter
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.Flavor,
		&i.Multiplier,
		&i.SandboxVcpu,
		&i.SandboxMemoryGib,
		&i.SandboxDiskGib,
		&i.StartedAt,
		&i.EndedAt,
		&i.BillableMinutes,
		&i.CapturedCredits,
		&i.TerminalState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingTopupSettings = `-- name: GetBillingTopupSettings :one
SELECT org_id, auto_topup_enabled, trigger_threshold, target_balance,
       monthly_max_units, monthly_units_used, monthly_anchor_month,
       created_at, updated_at
FROM billing_topup_settings
WHERE org_id = $1
`

func (q *Queries) GetBillingTopupSettings(ctx context.Context, orgID string) (BillingTopupSetting, error) {
	row := q.db.QueryRow(ctx, getBillingTopupSettings, orgID)
	var i BillingTopupSetting
	err := row.Scan(
		&i.OrgID,
		&i.AutoTopupEnabled,
		&i.TriggerThreshold,
		&i.TargetBalance,
		&i.MonthlyMaxUnits,
		&i.MonthlyUnitsUsed,
		&i.MonthlyAnchorMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoBillingSetting = `-- name: GetRepoBillingSetting :one
SELECT org_id, github_owner, github_repo, flavor, created_at, updated_at
FROM repo_billing_settings
WHERE org_id = $1 AND github_owner = $2 AND github_repo = $3
`

type GetRepoBillingSettingParams struct {
	OrgID       string `json:"org_id"`
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
}

func (q *Queries) GetRepoBillingSetting(ctx context.Context, arg GetRepoBillingSettingParams) (RepoBillingSetting, error) {
	row := q.db.QueryRow(ctx, getRepoBillingSetting, arg.OrgID, arg.GithubOwner, arg.GithubRepo)
	var i RepoBillingSetting
	err := row.Scan(
		&i.OrgID,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.Flavor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const grantBillingTopupCredits = `-- name: GrantBillingTopupCredits :one
UPDATE billing_accounts
   SET topup_credits = topup_credits + $2,
       last_payment_error = '',
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
          current_period_start, current_period_end,
          included_credits, included_credits_used, topup_credits,
          max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
          created_at, updated_at
`

type GrantBillingTopupCreditsParams struct {
	OrgID        string `json:"org_id"`
	TopupCredits int32  `json:"topup_credits"`
}

func (q *Queries) GrantBillingTopupCredits(ctx context.Context, arg GrantBillingTopupCreditsParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, grantBillingTopupCredits, arg.OrgID, arg.TopupCredits)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementBillingTopupMonthlyUnits = `-- name: IncrementBillingTopupMonthlyUnits :one
UPDATE billing_topup_settings
   SET monthly_units_used = monthly_units_used + $2,
       monthly_anchor_month = $3,
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, auto_topup_enabled, trigger_threshold, target_balance,
          monthly_max_units, monthly_units_used, monthly_anchor_month,
          created_at, updated_at
`

type IncrementBillingTopupMonthlyUnitsParams struct {
	OrgID              string `json:"org_id"`
	MonthlyUnitsUsed   int32  `json:"monthly_units_used"`
	MonthlyAnchorMonth string `json:"monthly_anchor_month"`
}

func (q *Queries) IncrementBillingTopupMonthlyUnits(ctx context.Context, arg IncrementBillingTopupMonthlyUnitsParams) (BillingTopupSetting, error) {
	row := q.db.QueryRow(ctx, incrementBillingTopupMonthlyUnits, arg.OrgID, arg.MonthlyUnitsUsed, arg.MonthlyAnchorMonth)
	var i BillingTopupSetting
	err := row.Scan(
		&i.OrgID,
		&i.AutoTopupEnabled,
		&i.TriggerThreshold,
		&i.TargetBalance,
		&i.MonthlyMaxUnits,
		&i.MonthlyUnitsUsed,
		&i.MonthlyAnchorMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBillingCreditReservation = `-- name: InsertBillingCreditReservation :one
INSERT INTO billing_credit_reservations (
    run_id, org_id, reserved_credits, from_included_credits, from_topup_credits, status
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING run_id, org_id, reserved_credits, from_included_credits, from_topup_credits,
          captured_credits, released_credits, status, created_at, updated_at
`

type InsertBillingCreditReservationParams struct {
	RunID               string `json:"run_id"`
	OrgID               string `json:"org_id"`
	ReservedCredits     int32  `json:"reserved_credits"`
	FromIncludedCredits int32  `json:"from_included_credits"`
	FromTopupCredits    int32  `json:"from_topup_credits"`
	Status              string `json:"status"`
}

func (q *Queries) InsertBillingCreditReservation(ctx context.Context, arg InsertBillingCreditReservationParams) (BillingCreditReservation, error) {
	row := q.db.QueryRow(ctx, insertBillingCreditReservation,
		arg.RunID,
		arg.OrgID,
		arg.ReservedCredits,
		arg.FromIncludedCredits,
		arg.FromTopupCredits,
		arg.Status,
	)
	var i BillingCreditReservation
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.ReservedCredits,
		&i.FromIncludedCredits,
		&i.FromTopupCredits,
		&i.CapturedCredits,
		&i.ReleasedCredits,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBillingStripeEvent = `-- name: InsertBillingStripeEvent :one
WITH inserted AS (
    INSERT INTO billing_stripe_events (event_id, event_type, org_id)
    VALUES ($1, $2, $3)
    ON CONFLICT (event_id) DO NOTHING
    RETURNING event_id
)
SELECT EXISTS(SELECT 1 FROM inserted)::boolean AS inserted
`

type InsertBillingStripeEventParams struct {
	EventID   string `json:"event_id"`
	EventType string `json:"event_type"`
	OrgID     string `json:"org_id"`
}

func (q *Queries) InsertBillingStripeEvent(ctx context.Context, arg InsertBillingStripeEventParams) (bool, error) {
	row := q.db.QueryRow(ctx, insertBillingStripeEvent, arg.EventID, arg.EventType, arg.OrgID)
	var inserted bool
	err := row.Scan(&inserted)
	return inserted, err
}

const listBillingRunMetersByOrg = `-- name: ListBillingRunMetersByOrg :many
SELECT run_id, org_id, flavor, multiplier, sandbox_vcpu, sandbox_memory_gib,
       sandbox_disk_gib, started_at, ended_at, billable_minutes,
       captured_credits, terminal_state, created_at, updated_at
FROM billing_run_meters
WHERE org_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type ListBillingRunMetersByOrgParams struct {
	OrgID string `json:"org_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListBillingRunMetersByOrg(ctx context.Context, arg ListBillingRunMetersByOrgParams) ([]BillingRunMeter, error) {
	rows, err := q.db.Query(ctx, listBillingRunMetersByOrg, arg.OrgID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BillingRunMeter
	for rows.Next() {
		var i BillingRunMeter
		if err := rows.Scan(
			&i.RunID,
			&i.OrgID,
			&i.Flavor,
			&i.Multiplier,
			&i.SandboxVcpu,
			&i.SandboxMemoryGib,
			&i.SandboxDiskGib,
			&i.StartedAt,
			&i.EndedAt,
			&i.BillableMinutes,
			&i.CapturedCredits,
			&i.TerminalState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoBillingSettingsByOrg = `-- name: ListRepoBillingSettingsByOrg :many
SELECT org_id, github_owner, github_repo, flavor, created_at, updated_at
FROM repo_billing_settings
WHERE org_id = $1
ORDER BY github_owner, github_repo
`

func (q *Queries) ListRepoBillingSettingsByOrg(ctx context.Context, orgID string) ([]RepoBillingSetting, error) {
	rows, err := q.db.Query(ctx, listRepoBillingSettingsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoBillingSetting
	for rows.Next() {
		var i RepoBillingSetting
		if err := rows.Scan(
			&i.OrgID,
			&i.GithubOwner,
			&i.GithubRepo,
			&i.Flavor,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBillingAccountForUpdate = `-- name: LockBillingAccountForUpdate :one
SELECT org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
       current_period_start, current_period_end,
       included_credits, included_credits_used, topup_credits,
       max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
       created_at, updated_at
FROM billing_accounts
WHERE org_id = $1
FOR UPDATE
`

func (q *Queries) LockBillingAccountForUpdate(ctx context.Context, orgID string) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, lockBillingAccountForUpdate, orgID)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockBillingTopupSettingsForUpdate = `-- name: LockBillingTopupSettingsForUpdate :one
SELECT org_id, auto_topup_enabled, trigger_threshold, target_balance,
       monthly_max_units, monthly_units_used, monthly_anchor_month,
       created_at, updated_at
FROM billing_topup_settings
WHERE org_id = $1
FOR UPDATE
`

func (q *Queries) LockBillingTopupSettingsForUpdate(ctx context.Context, orgID string) (BillingTopupSetting, error) {
	row := q.db.QueryRow(ctx, lockBillingTopupSettingsForUpdate, orgID)
	var i BillingTopupSetting
	err := row.Scan(
		&i.OrgID,
		&i.AutoTopupEnabled,
		&i.TriggerThreshold,
		&i.TargetBalance,
		&i.MonthlyMaxUnits,
		&i.MonthlyUnitsUsed,
		&i.MonthlyAnchorMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetBillingTopupMonthlyUsage = `-- name: ResetBillingTopupMonthlyUsage :one
UPDATE billing_topup_settings
   SET monthly_units_used = 0,
       monthly_anchor_month = $2,
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, auto_topup_enabled, trigger_threshold, target_balance,
          monthly_max_units, monthly_units_used, monthly_anchor_month,
          created_at, updated_at
`

type ResetBillingTopupMonthlyUsageParams struct {
	OrgID              string `json:"org_id"`
	MonthlyAnchorMonth string `json:"monthly_anchor_month"`
}

func (q *Queries) ResetBillingTopupMonthlyUsage(ctx context.Context, arg ResetBillingTopupMonthlyUsageParams) (BillingTopupSetting, error) {
	row := q.db.QueryRow(ctx, resetBillingTopupMonthlyUsage, arg.OrgID, arg.MonthlyAnchorMonth)
	var i BillingTopupSetting
	err := row.Scan(
		&i.OrgID,
		&i.AutoTopupEnabled,
		&i.TriggerThreshold,
		&i.TargetBalance,
		&i.MonthlyMaxUnits,
		&i.MonthlyUnitsUsed,
		&i.MonthlyAnchorMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setBillingLastPaymentError = `-- name: SetBillingLastPaymentError :exec
UPDATE billing_accounts
   SET last_payment_error = $2,
       updated_at = NOW()
WHERE org_id = $1
`

type SetBillingLastPaymentErrorParams struct {
	OrgID            string `json:"org_id"`
	LastPaymentError string `json:"last_payment_error"`
}

func (q *Queries) SetBillingLastPaymentError(ctx context.Context, arg SetBillingLastPaymentErrorParams) error {
	_, err := q.db.Exec(ctx, setBillingLastPaymentError, arg.OrgID, arg.LastPaymentError)
	return err
}

const updateBillingCapturedBalances = `-- name: UpdateBillingCapturedBalances :one
UPDATE billing_accounts
   SET included_credits_used = GREATEST(included_credits_used + $2, 0),
       topup_credits = GREATEST(topup_credits + $3, 0),
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
          current_period_start, current_period_end,
          included_credits, included_credits_used, topup_credits,
          max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
          created_at, updated_at
`

type UpdateBillingCapturedBalancesParams struct {
	OrgID               string `json:"org_id"`
	IncludedCreditsUsed int32  `json:"included_credits_used"`
	TopupCredits        int32  `json:"topup_credits"`
}

func (q *Queries) UpdateBillingCapturedBalances(ctx context.Context, arg UpdateBillingCapturedBalancesParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingCapturedBalances, arg.OrgID, arg.IncludedCreditsUsed, arg.TopupCredits)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingCreditReservationCaptured = `-- name: UpdateBillingCreditReservationCaptured :one
UPDATE billing_credit_reservations
   SET captured_credits = $2,
       released_credits = $3,
       status = $4,
       updated_at = NOW()
WHERE run_id = $1
RETURNING run_id, org_id, reserved_credits, from_included_credits, from_topup_credits,
          captured_credits, released_credits, status, created_at, updated_at
`

type UpdateBillingCreditReservationCapturedParams struct {
	RunID           string `json:"run_id"`
	CapturedCredits int32  `json:"captured_credits"`
	ReleasedCredits int32  `json:"released_credits"`
	Status          string `json:"status"`
}

func (q *Queries) UpdateBillingCreditReservationCaptured(ctx context.Context, arg UpdateBillingCreditReservationCapturedParams) (BillingCreditReservation, error) {
	row := q.db.QueryRow(ctx, updateBillingCreditReservationCaptured,
		arg.RunID,
		arg.CapturedCredits,
		arg.ReleasedCredits,
		arg.Status,
	)
	var i BillingCreditReservation
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.ReservedCredits,
		&i.FromIncludedCredits,
		&i.FromTopupCredits,
		&i.CapturedCredits,
		&i.ReleasedCredits,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingReservedBalances = `-- name: UpdateBillingReservedBalances :one
UPDATE billing_accounts
   SET included_credits_used = included_credits_used + $2,
       topup_credits = topup_credits - $3,
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
          current_period_start, current_period_end,
          included_credits, included_credits_used, topup_credits,
          max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
          created_at, updated_at
`

type UpdateBillingReservedBalancesParams struct {
	OrgID               string `json:"org_id"`
	IncludedCreditsUsed int32  `json:"included_credits_used"`
	TopupCredits        int32  `json:"topup_credits"`
}

func (q *Queries) UpdateBillingReservedBalances(ctx context.Context, arg UpdateBillingReservedBalancesParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingReservedBalances, arg.OrgID, arg.IncludedCreditsUsed, arg.TopupCredits)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingStripeCustomer = `-- name: UpdateBillingStripeCustomer :one
UPDATE billing_accounts
   SET stripe_customer_id = $2,
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
          current_period_start, current_period_end,
          included_credits, included_credits_used, topup_credits,
          max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
          created_at, updated_at
`

type UpdateBillingStripeCustomerParams struct {
	OrgID            string `json:"org_id"`
	StripeCustomerID string `json:"stripe_customer_id"`
}

func (q *Queries) UpdateBillingStripeCustomer(ctx context.Context, arg UpdateBillingStripeCustomerParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingStripeCustomer, arg.OrgID, arg.StripeCustomerID)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBillingTopupSettings = `-- name: UpdateBillingTopupSettings :one
UPDATE billing_topup_settings
   SET auto_topup_enabled = $2,
       trigger_threshold = $3,
       target_balance = $4,
       monthly_max_units = $5,
       updated_at = NOW()
WHERE org_id = $1
RETURNING org_id, auto_topup_enabled, trigger_threshold, target_balance,
          monthly_max_units, monthly_units_used, monthly_anchor_month,
          created_at, updated_at
`

type UpdateBillingTopupSettingsParams struct {
	OrgID            string `json:"org_id"`
	AutoTopupEnabled bool   `json:"auto_topup_enabled"`
	TriggerThreshold int32  `json:"trigger_threshold"`
	TargetBalance    int32  `json:"target_balance"`
	MonthlyMaxUnits  int32  `json:"monthly_max_units"`
}

func (q *Queries) UpdateBillingTopupSettings(ctx context.Context, arg UpdateBillingTopupSettingsParams) (BillingTopupSetting, error) {
	row := q.db.QueryRow(ctx, updateBillingTopupSettings,
		arg.OrgID,
		arg.AutoTopupEnabled,
		arg.TriggerThreshold,
		arg.TargetBalance,
		arg.MonthlyMaxUnits,
	)
	var i BillingTopupSetting
	err := row.Scan(
		&i.OrgID,
		&i.AutoTopupEnabled,
		&i.TriggerThreshold,
		&i.TargetBalance,
		&i.MonthlyMaxUnits,
		&i.MonthlyUnitsUsed,
		&i.MonthlyAnchorMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBillingAccountMirror = `-- name: UpsertBillingAccountMirror :one
INSERT INTO billing_accounts (
    org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
    current_period_start, current_period_end,
    included_credits, max_flavor, per_run_max_credits, billing_exempt,
    last_payment_error
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
ON CONFLICT (org_id) DO UPDATE SET
    stripe_customer_id     = EXCLUDED.stripe_customer_id,
    stripe_subscription_id = EXCLUDED.stripe_subscription_id,
    plan_code              = EXCLUDED.plan_code,
    status                 = EXCLUDED.status,
    current_period_start   = EXCLUDED.current_period_start,
    current_period_end     = EXCLUDED.current_period_end,
    included_credits       = EXCLUDED.included_credits,
    included_credits_used  = CASE
        WHEN billing_accounts.current_period_start IS DISTINCT FROM EXCLUDED.current_period_start
          OR billing_accounts.current_period_end IS DISTINCT FROM EXCLUDED.current_period_end
        THEN 0
        ELSE LEAST(billing_accounts.included_credits_used, EXCLUDED.included_credits)
    END,
    max_flavor             = EXCLUDED.max_flavor,
    per_run_max_credits    = EXCLUDED.per_run_max_credits,
    billing_exempt         = EXCLUDED.billing_exempt,
    last_payment_error     = EXCLUDED.last_payment_error,
    updated_at             = NOW()
RETURNING org_id, stripe_customer_id, stripe_subscription_id, plan_code, status,
          current_period_start, current_period_end,
          included_credits, included_credits_used, topup_credits,
          max_flavor, per_run_max_credits, billing_exempt, last_payment_error,
          created_at, updated_at
`

type UpsertBillingAccountMirrorParams struct {
	OrgID                string             `json:"org_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripeSubscriptionID string             `json:"stripe_subscription_id"`
	PlanCode             string             `json:"plan_code"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	IncludedCredits      int32              `json:"included_credits"`
	MaxFlavor            string             `json:"max_flavor"`
	PerRunMaxCredits     int32              `json:"per_run_max_credits"`
	BillingExempt        bool               `json:"billing_exempt"`
	LastPaymentError     string             `json:"last_payment_error"`
}

func (q *Queries) UpsertBillingAccountMirror(ctx context.Context, arg UpsertBillingAccountMirrorParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, upsertBillingAccountMirror,
		arg.OrgID,
		arg.StripeCustomerID,
		arg.StripeSubscriptionID,
		arg.PlanCode,
		arg.Status,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.IncludedCredits,
		arg.MaxFlavor,
		arg.PerRunMaxCredits,
		arg.BillingExempt,
		arg.LastPaymentError,
	)
	var i BillingAccount
	err := row.Scan(
		&i.OrgID,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.PlanCode,
		&i.Status,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.IncludedCredits,
		&i.IncludedCreditsUsed,
		&i.TopupCredits,
		&i.MaxFlavor,
		&i.PerRunMaxCredits,
		&i.BillingExempt,
		&i.LastPaymentError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertBillingRunMeterStart = `-- name: UpsertBillingRunMeterStart :one
INSERT INTO billing_run_meters (
    run_id, org_id, flavor, multiplier, sandbox_vcpu, sandbox_memory_gib,
    sandbox_disk_gib, started_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (run_id) DO UPDATE SET
    flavor = EXCLUDED.flavor,
    multiplier = EXCLUDED.multiplier,
    sandbox_vcpu = EXCLUDED.sandbox_vcpu,
    sandbox_memory_gib = EXCLUDED.sandbox_memory_gib,
    sandbox_disk_gib = EXCLUDED.sandbox_disk_gib,
    updated_at = NOW()
RETURNING run_id, org_id, flavor, multiplier, sandbox_vcpu, sandbox_memory_gib,
          sandbox_disk_gib, started_at, ended_at, billable_minutes,
          captured_credits, terminal_state, created_at, updated_at
`

type UpsertBillingRunMeterStartParams struct {
	RunID            string             `json:"run_id"`
	OrgID            string             `json:"org_id"`
	Flavor           string             `json:"flavor"`
	Multiplier       int32              `json:"multiplier"`
	SandboxVcpu      int32              `json:"sandbox_vcpu"`
	SandboxMemoryGib int32              `json:"sandbox_memory_gib"`
	SandboxDiskGib   int32              `json:"sandbox_disk_gib"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) UpsertBillingRunMeterStart(ctx context.Context, arg UpsertBillingRunMeterStartParams) (BillingRunMeter, error) {
	row := q.db.QueryRow(ctx, upsertBillingRunMeterStart,
		arg.RunID,
		arg.OrgID,
		arg.Flavor,
		arg.Multiplier,
		arg.SandboxVcpu,
		arg.SandboxMemoryGib,
		arg.SandboxDiskGib,
		arg.StartedAt,
	)
	var i BillingRunMeter
	err := row.Scan(
		&i.RunID,
		&i.OrgID,
		&i.Flavor,
		&i.Multiplier,
		&i.SandboxVcpu,
		&i.SandboxMemoryGib,
		&i.SandboxDiskGib,
		&i.StartedAt,
		&i.EndedAt,
		&i.BillableMinutes,
		&i.CapturedCredits,
		&i.TerminalState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoBillingSetting = `-- name: UpsertRepoBillingSetting :one
INSERT INTO repo_billing_settings (org_id, github_owner, github_repo, flavor)
VALUES ($1, $2, $3, $4)
ON CONFLICT (org_id, github_owner, github_repo) DO UPDATE SET
    flavor = EXCLUDED.flavor,
    updated_at = NOW()
RETURNING org_id, github_owner, github_repo, flavor, created_at, updated_at
`

type UpsertRepoBillingSettingParams struct {
	OrgID       string `json:"org_id"`
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
	Flavor      string `json:"flavor"`
}

func (q *Queries) UpsertRepoBillingSetting(ctx context.Context, arg UpsertRepoBillingSettingParams) (RepoBillingSetting, error) {
	row := q.db.QueryRow(ctx, upsertRepoBillingSetting,
		arg.OrgID,
		arg.GithubOwner,
		arg.GithubRepo,
		arg.Flavor,
	)
	var i RepoBillingSetting
	err := row.Scan(
		&i.OrgID,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.Flavor,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
