// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE org_id = $1 AND thread_id = $2
`

type DeleteConversationParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.OrgID, arg.ThreadID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo, custom_title, creator_id, agent_slug
FROM conversations
WHERE org_id = $1 AND thread_id = $2
`

type GetConversationParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

type GetConversationRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.OrgID, arg.ThreadID)
	var i GetConversationRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.CustomTitle,
		&i.CreatorID,
		&i.AgentSlug,
	)
	return i, err
}

const renameConversation = `-- name: RenameConversation :execrows
UPDATE conversations SET custom_title = $3
WHERE org_id = $1 AND thread_id = $2
`

type RenameConversationParams struct {
	OrgID       string `json:"org_id"`
	ThreadID    string `json:"thread_id"`
	CustomTitle string `json:"custom_title"`
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameConversation, arg.OrgID, arg.ThreadID, arg.CustomTitle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveConversationProgress = `-- name: SaveConversationProgress :exec
UPDATE conversations
   SET history         = $3,
       response_blocks = $4,
       creator_id      = CASE
                             WHEN creator_id = '' THEN $5
                             ELSE creator_id
                         END,
       updated_at      = NOW()
WHERE org_id = $1 AND thread_id = $2
`

type SaveConversationProgressParams struct {
	OrgID          string   `json:"org_id"`
	ThreadID       string   `json:"thread_id"`
	History        []string `json:"history"`
	ResponseBlocks [][]byte `json:"response_blocks"`
	CreatorID      string   `json:"creator_id"`
}

// Periodic mid-run snapshot used by chatPersister. Only writes the
// handful of fields that change progressively as the agent emits
// blocks (history + response_blocks + creator_id). The fields that
// track terminal state (sandbox_id, branch, pr_url, github_owner,
// github_repo) are deliberately left alone — their canonical values
// are written by UpsertConversation at end-of-turn, and overwriting
// them here mid-run would race the dispatcher into the wrong state
// machine branch on a concurrent reload.
//
// Pure UPDATE. We rely on the dispatcher's entry-Upsert (in
// HandleRequest, before runFreshAgent) to create the row with the
// NOT NULL columns populated; if a tick fires before that landing
// the UPDATE simply matches zero rows and silently no-ops, which is
// the correct behaviour. An INSERT here would either need to know
// sandbox_id (it doesn't) or break NOT NULL by default-empty —
// neither is desirable, and the persister has no business creating
// rows on its own.
func (q *Queries) SaveConversationProgress(ctx context.Context, arg SaveConversationProgressParams) error {
	_, err := q.db.Exec(ctx, saveConversationProgress,
		arg.OrgID,
		arg.ThreadID,
		arg.History,
		arg.ResponseBlocks,
		arg.CreatorID,
	)
	return err
}

const searchConversations = `-- name: SearchConversations :many
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo, custom_title, creator_id, agent_slug
FROM conversations
WHERE org_id = $1
  AND ($2::text = '' OR creator_id = $2)
  AND (
    $3::text = ''
    OR custom_title ILIKE '%' || $3 || '%' ESCAPE '\'
    OR history[1]    ILIKE '%' || $3 || '%' ESCAPE '\'
  )
ORDER BY updated_at DESC
LIMIT $5
OFFSET $4
`

type SearchConversationsParams struct {
	OrgID     string `json:"org_id"`
	CreatorID string `json:"creator_id"`
	Query     string `json:"query"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type SearchConversationsRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
}

// Backs the sidebar list. Filters by optional creator_id and an
// optional case-insensitive substring match against either the
// custom_title or the first user message (history[1] — Postgres
// arrays are 1-indexed; out-of-range yields NULL, and NULL ILIKE
// pattern is NULL, which evaluates as falsy in WHERE so an empty
// history harmlessly fails to match).
//
// Pass empty strings to skip a filter; LIMIT/OFFSET drive the
// "Load more" pager. The ESCAPE '\' clause makes the literal '\'
// character the escape — caller is expected to backslash-escape
// '%', '_' and '\' in the user-typed query so they read as
// literals instead of pattern metacharacters.
//
// Performance note: ILIKE '%foo%' is sequential scan territory
// because no B-tree index can cover a leading-wildcard pattern.
// Fine for the current per-org chat counts (tens to low hundreds);
// when an org grows past a few thousand chats, switch to pg_trgm
// + a GIN index on custom_title (and a generated column for
// history[1]).
func (q *Queries) SearchConversations(ctx context.Context, arg SearchConversationsParams) ([]SearchConversationsRow, error) {
	rows, err := q.db.Query(ctx, searchConversations,
		arg.OrgID,
		arg.CreatorID,
		arg.Query,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConversationsRow
	for rows.Next() {
		var i SearchConversationsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ThreadID,
			&i.SandboxID,
			&i.Branch,
			&i.PrUrl,
			&i.History,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponseBlocks,
			&i.GithubOwner,
			&i.GithubRepo,
			&i.CustomTitle,
			&i.CreatorID,
			&i.AgentSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (
    org_id, thread_id, sandbox_id, branch, pr_url, history, response_blocks,
    github_owner, github_repo, creator_id, agent_slug
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
)
ON CONFLICT (org_id, thread_id) DO UPDATE SET
    sandbox_id      = EXCLUDED.sandbox_id,
    branch          = EXCLUDED.branch,
    pr_url          = EXCLUDED.pr_url,
    history         = EXCLUDED.history,
    response_blocks = EXCLUDED.response_blocks,
    github_owner    = EXCLUDED.github_owner,
    github_repo     = EXCLUDED.github_repo,
    agent_slug      = EXCLUDED.agent_slug,
    updated_at      = NOW()
RETURNING org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
          github_owner, github_repo, custom_title, creator_id, agent_slug
`

type UpsertConversationParams struct {
	OrgID          string   `json:"org_id"`
	ThreadID       string   `json:"thread_id"`
	SandboxID      string   `json:"sandbox_id"`
	Branch         string   `json:"branch"`
	PrUrl          string   `json:"pr_url"`
	History        []string `json:"history"`
	ResponseBlocks [][]byte `json:"response_blocks"`
	GithubOwner    string   `json:"github_owner"`
	GithubRepo     string   `json:"github_repo"`
	CreatorID      string   `json:"creator_id"`
	AgentSlug      string   `json:"agent_slug"`
}

type UpsertConversationRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (UpsertConversationRow, error) {
	row := q.db.QueryRow(ctx, upsertConversation,
		arg.OrgID,
		arg.ThreadID,
		arg.SandboxID,
		arg.Branch,
		arg.PrUrl,
		arg.History,
		arg.ResponseBlocks,
		arg.GithubOwner,
		arg.GithubRepo,
		arg.CreatorID,
		arg.AgentSlug,
	)
	var i UpsertConversationRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.CustomTitle,
		&i.CreatorID,
		&i.AgentSlug,
	)
	return i, err
}
