// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE org_id = $1 AND thread_id = $2
`

type DeleteConversationParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.OrgID, arg.ThreadID)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo
FROM conversations
WHERE org_id = $1 AND thread_id = $2
`

type GetConversationParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

type GetConversationRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.OrgID, arg.ThreadID)
	var i GetConversationRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
	)
	return i, err
}

const listConversationsByOrg = `-- name: ListConversationsByOrg :many
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo
FROM conversations
WHERE org_id = $1
ORDER BY updated_at DESC
`

type ListConversationsByOrgRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
}

func (q *Queries) ListConversationsByOrg(ctx context.Context, orgID string) ([]ListConversationsByOrgRow, error) {
	rows, err := q.db.Query(ctx, listConversationsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationsByOrgRow
	for rows.Next() {
		var i ListConversationsByOrgRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ThreadID,
			&i.SandboxID,
			&i.Branch,
			&i.PrUrl,
			&i.History,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponseBlocks,
			&i.GithubOwner,
			&i.GithubRepo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (
    org_id, thread_id, sandbox_id, branch, pr_url, history, response_blocks,
    github_owner, github_repo
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (org_id, thread_id) DO UPDATE SET
    sandbox_id      = EXCLUDED.sandbox_id,
    branch          = EXCLUDED.branch,
    pr_url          = EXCLUDED.pr_url,
    history         = EXCLUDED.history,
    response_blocks = EXCLUDED.response_blocks,
    github_owner    = EXCLUDED.github_owner,
    github_repo     = EXCLUDED.github_repo,
    updated_at      = NOW()
RETURNING org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
          github_owner, github_repo
`

type UpsertConversationParams struct {
	OrgID          string   `json:"org_id"`
	ThreadID       string   `json:"thread_id"`
	SandboxID      string   `json:"sandbox_id"`
	Branch         string   `json:"branch"`
	PrUrl          string   `json:"pr_url"`
	History        []string `json:"history"`
	ResponseBlocks [][]byte `json:"response_blocks"`
	GithubOwner    string   `json:"github_owner"`
	GithubRepo     string   `json:"github_repo"`
}

type UpsertConversationRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (UpsertConversationRow, error) {
	row := q.db.QueryRow(ctx, upsertConversation,
		arg.OrgID,
		arg.ThreadID,
		arg.SandboxID,
		arg.Branch,
		arg.PrUrl,
		arg.History,
		arg.ResponseBlocks,
		arg.GithubOwner,
		arg.GithubRepo,
	)
	var i UpsertConversationRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
	)
	return i, err
}
