// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversation_events.sql

package sqlc

import (
	"context"
)

const insertConversationEvent = `-- name: InsertConversationEvent :exec
INSERT INTO conversation_events (org_id, thread_id, seq, kind, payload)
VALUES ($1, $2, $3, $4, $5)
`

type InsertConversationEventParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
	Seq      int64  `json:"seq"`
	Kind     string `json:"kind"`
	Payload  []byte `json:"payload"`
}

// Append-only event log. The seq is supplied by the caller after
// AllocateNextSeq inside the same transaction; pg_notify on commit wakes
// any replica with attached SSE subscribers.
func (q *Queries) InsertConversationEvent(ctx context.Context, arg InsertConversationEventParams) error {
	_, err := q.db.Exec(ctx, insertConversationEvent,
		arg.OrgID,
		arg.ThreadID,
		arg.Seq,
		arg.Kind,
		arg.Payload,
	)
	return err
}

const replayConversationEvents = `-- name: ReplayConversationEvents :many
SELECT org_id, thread_id, seq, kind, payload, created_at
FROM conversation_events
WHERE org_id = $1
  AND thread_id = $2
  AND seq > $3
ORDER BY seq
LIMIT $4
`

type ReplayConversationEventsParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
	SinceSeq int64  `json:"since_seq"`
	Lim      int32  `json:"lim"`
}

// SSE replay path. Returns events strictly after sinceSeq so a client
// reattaching after a network blip with Last-Event-Id set to its last
// seq sees the gap and only the gap.
func (q *Queries) ReplayConversationEvents(ctx context.Context, arg ReplayConversationEventsParams) ([]ConversationEvent, error) {
	rows, err := q.db.Query(ctx, replayConversationEvents,
		arg.OrgID,
		arg.ThreadID,
		arg.SinceSeq,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationEvent
	for rows.Next() {
		var i ConversationEvent
		if err := rows.Scan(
			&i.OrgID,
			&i.ThreadID,
			&i.Seq,
			&i.Kind,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
