// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteConversation = `-- name: DeleteConversation :exec
DELETE FROM conversations WHERE org_id = $1 AND thread_id = $2
`

type DeleteConversationParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) error {
	_, err := q.db.Exec(ctx, deleteConversation, arg.OrgID, arg.ThreadID)
	return err
}

const deleteConversationAttachmentsForTurn = `-- name: DeleteConversationAttachmentsForTurn :exec
DELETE FROM conversation_attachments
WHERE org_id = $1 AND thread_id = $2 AND turn_index = $3
`

type DeleteConversationAttachmentsForTurnParams struct {
	OrgID     string `json:"org_id"`
	ThreadID  string `json:"thread_id"`
	TurnIndex int32  `json:"turn_index"`
}

func (q *Queries) DeleteConversationAttachmentsForTurn(ctx context.Context, arg DeleteConversationAttachmentsForTurnParams) error {
	_, err := q.db.Exec(ctx, deleteConversationAttachmentsForTurn, arg.OrgID, arg.ThreadID, arg.TurnIndex)
	return err
}

const findConversationByPRURL = `-- name: FindConversationByPRURL :one
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo, custom_title, creator_id, agent_slug, model, task_options
FROM conversations
WHERE org_id = $1 AND pr_url = $2
ORDER BY updated_at DESC
LIMIT 1
`

type FindConversationByPRURLParams struct {
	OrgID string `json:"org_id"`
	PrUrl string `json:"pr_url"`
}

type FindConversationByPRURLRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
	Model          string             `json:"model"`
	TaskOptions    []byte             `json:"task_options"`
}

// Resolves a GitHub PR URL back to the conversation that opened it. The
// inbound webhook payload carries the installation_id, which we map to
// org_id before calling this, so the (org_id, pr_url) pair scopes the
// lookup to that org's data even though two different orgs could in
// principle have an installation that mirrors the same upstream repo.
//
// Newest-first ordering is a defensive tiebreak: a single PR URL should
// correspond to at most one conversation, but if a retry or rerun ever
// duplicated the URL we'd rather route the comment to the latest live
// thread than to a stale one.
func (q *Queries) FindConversationByPRURL(ctx context.Context, arg FindConversationByPRURLParams) (FindConversationByPRURLRow, error) {
	row := q.db.QueryRow(ctx, findConversationByPRURL, arg.OrgID, arg.PrUrl)
	var i FindConversationByPRURLRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.CustomTitle,
		&i.CreatorID,
		&i.AgentSlug,
		&i.Model,
		&i.TaskOptions,
	)
	return i, err
}

const getConversation = `-- name: GetConversation :one
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo, custom_title, creator_id, agent_slug, model, task_options
FROM conversations
WHERE org_id = $1 AND thread_id = $2
`

type GetConversationParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

type GetConversationRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
	Model          string             `json:"model"`
	TaskOptions    []byte             `json:"task_options"`
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.OrgID, arg.ThreadID)
	var i GetConversationRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.CustomTitle,
		&i.CreatorID,
		&i.AgentSlug,
		&i.Model,
		&i.TaskOptions,
	)
	return i, err
}

const getConversationAttachment = `-- name: GetConversationAttachment :one
SELECT id, org_id, thread_id, turn_index, filename, content_type,
       size_bytes, data, source, slack_file_id, created_at
FROM conversation_attachments
WHERE org_id = $1 AND id = $2
`

type GetConversationAttachmentParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetConversationAttachment(ctx context.Context, arg GetConversationAttachmentParams) (ConversationAttachment, error) {
	row := q.db.QueryRow(ctx, getConversationAttachment, arg.OrgID, arg.ID)
	var i ConversationAttachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.TurnIndex,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Data,
		&i.Source,
		&i.SlackFileID,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationAttachments = `-- name: ListConversationAttachments :many
SELECT id, org_id, thread_id, turn_index, filename, content_type,
       size_bytes, source, slack_file_id, created_at
FROM conversation_attachments
WHERE org_id = $1 AND thread_id = $2
ORDER BY turn_index ASC, created_at ASC, id ASC
`

type ListConversationAttachmentsParams struct {
	OrgID    string `json:"org_id"`
	ThreadID string `json:"thread_id"`
}

type ListConversationAttachmentsRow struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	ThreadID    string             `json:"thread_id"`
	TurnIndex   int32              `json:"turn_index"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Source      string             `json:"source"`
	SlackFileID string             `json:"slack_file_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListConversationAttachments(ctx context.Context, arg ListConversationAttachmentsParams) ([]ListConversationAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listConversationAttachments, arg.OrgID, arg.ThreadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConversationAttachmentsRow
	for rows.Next() {
		var i ListConversationAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.TurnIndex,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Source,
			&i.SlackFileID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConversationAttachmentsForTurn = `-- name: ListConversationAttachmentsForTurn :many
SELECT id, org_id, thread_id, turn_index, filename, content_type,
       size_bytes, data, source, slack_file_id, created_at
FROM conversation_attachments
WHERE org_id = $1 AND thread_id = $2 AND turn_index = $3
ORDER BY created_at ASC, id ASC
`

type ListConversationAttachmentsForTurnParams struct {
	OrgID     string `json:"org_id"`
	ThreadID  string `json:"thread_id"`
	TurnIndex int32  `json:"turn_index"`
}

func (q *Queries) ListConversationAttachmentsForTurn(ctx context.Context, arg ListConversationAttachmentsForTurnParams) ([]ConversationAttachment, error) {
	rows, err := q.db.Query(ctx, listConversationAttachmentsForTurn, arg.OrgID, arg.ThreadID, arg.TurnIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConversationAttachment
	for rows.Next() {
		var i ConversationAttachment
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ThreadID,
			&i.TurnIndex,
			&i.Filename,
			&i.ContentType,
			&i.SizeBytes,
			&i.Data,
			&i.Source,
			&i.SlackFileID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameConversation = `-- name: RenameConversation :execrows
UPDATE conversations SET custom_title = $3
WHERE org_id = $1 AND thread_id = $2
`

type RenameConversationParams struct {
	OrgID       string `json:"org_id"`
	ThreadID    string `json:"thread_id"`
	CustomTitle string `json:"custom_title"`
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameConversation, arg.OrgID, arg.ThreadID, arg.CustomTitle)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveConversationAttachment = `-- name: SaveConversationAttachment :one
INSERT INTO conversation_attachments (
    id, org_id, thread_id, turn_index, filename, content_type,
    size_bytes, data, source, slack_file_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, org_id, thread_id, turn_index, filename, content_type,
          size_bytes, data, source, slack_file_id, created_at
`

type SaveConversationAttachmentParams struct {
	ID          string `json:"id"`
	OrgID       string `json:"org_id"`
	ThreadID    string `json:"thread_id"`
	TurnIndex   int32  `json:"turn_index"`
	Filename    string `json:"filename"`
	ContentType string `json:"content_type"`
	SizeBytes   int64  `json:"size_bytes"`
	Data        []byte `json:"data"`
	Source      string `json:"source"`
	SlackFileID string `json:"slack_file_id"`
}

func (q *Queries) SaveConversationAttachment(ctx context.Context, arg SaveConversationAttachmentParams) (ConversationAttachment, error) {
	row := q.db.QueryRow(ctx, saveConversationAttachment,
		arg.ID,
		arg.OrgID,
		arg.ThreadID,
		arg.TurnIndex,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Data,
		arg.Source,
		arg.SlackFileID,
	)
	var i ConversationAttachment
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ThreadID,
		&i.TurnIndex,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Data,
		&i.Source,
		&i.SlackFileID,
		&i.CreatedAt,
	)
	return i, err
}

const saveConversationProgress = `-- name: SaveConversationProgress :exec
UPDATE conversations
   SET history         = $3,
       response_blocks = $4,
       creator_id      = CASE
                             WHEN creator_id = '' THEN $5
                             ELSE creator_id
                         END,
       updated_at      = NOW()
WHERE org_id = $1 AND thread_id = $2
`

type SaveConversationProgressParams struct {
	OrgID          string   `json:"org_id"`
	ThreadID       string   `json:"thread_id"`
	History        []string `json:"history"`
	ResponseBlocks [][]byte `json:"response_blocks"`
	CreatorID      string   `json:"creator_id"`
}

// Periodic mid-run snapshot used by chatPersister. Only writes the
// handful of fields that change progressively as the agent emits
// blocks (history + response_blocks + creator_id). The fields that
// track terminal state (sandbox_id, branch, pr_url, github_owner,
// github_repo) are deliberately left alone — their canonical values
// are written by UpsertConversation at end-of-turn, and overwriting
// them here mid-run would race the dispatcher into the wrong state
// machine branch on a concurrent reload.
//
// Pure UPDATE. We rely on the dispatcher's entry-Upsert (in
// HandleRequest, before runFreshAgent) to create the row with the
// NOT NULL columns populated; if a tick fires before that landing
// the UPDATE simply matches zero rows and silently no-ops, which is
// the correct behaviour. An INSERT here would either need to know
// sandbox_id (it doesn't) or break NOT NULL by default-empty —
// neither is desirable, and the persister has no business creating
// rows on its own.
func (q *Queries) SaveConversationProgress(ctx context.Context, arg SaveConversationProgressParams) error {
	_, err := q.db.Exec(ctx, saveConversationProgress,
		arg.OrgID,
		arg.ThreadID,
		arg.History,
		arg.ResponseBlocks,
		arg.CreatorID,
	)
	return err
}

const saveConversationTaskOptions = `-- name: SaveConversationTaskOptions :exec
UPDATE conversations
   SET task_options = $3,
       updated_at   = NOW()
WHERE org_id = $1 AND thread_id = $2
`

type SaveConversationTaskOptionsParams struct {
	OrgID       string `json:"org_id"`
	ThreadID    string `json:"thread_id"`
	TaskOptions []byte `json:"task_options"`
}

func (q *Queries) SaveConversationTaskOptions(ctx context.Context, arg SaveConversationTaskOptionsParams) error {
	_, err := q.db.Exec(ctx, saveConversationTaskOptions, arg.OrgID, arg.ThreadID, arg.TaskOptions)
	return err
}

const searchConversations = `-- name: SearchConversations :many
SELECT org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
       github_owner, github_repo, custom_title, creator_id, agent_slug, model, task_options
FROM conversations
WHERE org_id = $1
  AND ($2::text = '' OR creator_id = $2)
  AND (
    $3::text = ''
    OR custom_title ILIKE '%' || $3 || '%' ESCAPE '\'
    OR history[1]    ILIKE '%' || $3 || '%' ESCAPE '\'
  )
ORDER BY created_at DESC, thread_id DESC
LIMIT $5
OFFSET $4
`

type SearchConversationsParams struct {
	OrgID     string `json:"org_id"`
	CreatorID string `json:"creator_id"`
	Query     string `json:"query"`
	Off       int32  `json:"off"`
	Lim       int32  `json:"lim"`
}

type SearchConversationsRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
	Model          string             `json:"model"`
	TaskOptions    []byte             `json:"task_options"`
}

// Backs the sidebar list. Filters by optional creator_id and an
// optional case-insensitive substring match against either the
// custom_title or the first user message (history[1] — Postgres
// arrays are 1-indexed; out-of-range yields NULL, and NULL ILIKE
// pattern is NULL, which evaluates as falsy in WHERE so an empty
// history harmlessly fails to match).
//
// Pass empty strings to skip a filter; LIMIT/OFFSET drive the
// "Load more" pager. The ESCAPE '\' clause makes the literal '\'
// character the escape — caller is expected to backslash-escape
// '%', '_' and '\' in the user-typed query so they read as
// literals instead of pattern metacharacters.
//
// Ordering is by created_at descending (newest first) so a chat's
// position in the sidebar stays stable as new turns land — replying
// to an old chat never reshuffles the list, and a brand-new chat
// lands on page 0 where the sidebar's offset=0 reload will see it.
// thread_id breaks ties when two rows share the same created_at (common
// for inserts within the same transaction, since NOW() returns
// transaction-start time) so pagination stays deterministic.
//
// Caveat: LIMIT/OFFSET pagination is not snapshot-isolated. A new chat
// inserted between a user's page-0 fetch and their "Load more" click
// shifts every existing row down by one, so the OFFSET N request may
// re-fetch the last row of the previous page or skip a row. Acceptable
// at current per-org scale (tens to low hundreds). Future fix: keyset
// pagination on (created_at, thread_id) — pass the last row's pair as
// a cursor instead of an offset.
//
// Performance note: ILIKE '%foo%' is sequential scan territory
// because no B-tree index can cover a leading-wildcard pattern.
// Fine for the current per-org chat counts (tens to low hundreds);
// when an org grows past a few thousand chats, switch to pg_trgm
// + a GIN index on custom_title (and a generated column for
// history[1]).
func (q *Queries) SearchConversations(ctx context.Context, arg SearchConversationsParams) ([]SearchConversationsRow, error) {
	rows, err := q.db.Query(ctx, searchConversations,
		arg.OrgID,
		arg.CreatorID,
		arg.Query,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchConversationsRow
	for rows.Next() {
		var i SearchConversationsRow
		if err := rows.Scan(
			&i.OrgID,
			&i.ThreadID,
			&i.SandboxID,
			&i.Branch,
			&i.PrUrl,
			&i.History,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResponseBlocks,
			&i.GithubOwner,
			&i.GithubRepo,
			&i.CustomTitle,
			&i.CreatorID,
			&i.AgentSlug,
			&i.Model,
			&i.TaskOptions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO conversations (
    org_id, thread_id, sandbox_id, branch, pr_url, history, response_blocks,
    github_owner, github_repo, creator_id, agent_slug, model, task_options
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
ON CONFLICT (org_id, thread_id) DO UPDATE SET
    sandbox_id      = EXCLUDED.sandbox_id,
    branch          = EXCLUDED.branch,
    pr_url          = EXCLUDED.pr_url,
    history         = EXCLUDED.history,
    response_blocks = EXCLUDED.response_blocks,
    github_owner    = EXCLUDED.github_owner,
    github_repo     = EXCLUDED.github_repo,
    agent_slug      = EXCLUDED.agent_slug,
    model           = EXCLUDED.model,
    task_options    = EXCLUDED.task_options,
    updated_at      = NOW()
RETURNING org_id, thread_id, sandbox_id, branch, pr_url, history, created_at, updated_at, response_blocks,
          github_owner, github_repo, custom_title, creator_id, agent_slug, model, task_options
`

type UpsertConversationParams struct {
	OrgID          string   `json:"org_id"`
	ThreadID       string   `json:"thread_id"`
	SandboxID      string   `json:"sandbox_id"`
	Branch         string   `json:"branch"`
	PrUrl          string   `json:"pr_url"`
	History        []string `json:"history"`
	ResponseBlocks [][]byte `json:"response_blocks"`
	GithubOwner    string   `json:"github_owner"`
	GithubRepo     string   `json:"github_repo"`
	CreatorID      string   `json:"creator_id"`
	AgentSlug      string   `json:"agent_slug"`
	Model          string   `json:"model"`
	TaskOptions    []byte   `json:"task_options"`
}

type UpsertConversationRow struct {
	OrgID          string             `json:"org_id"`
	ThreadID       string             `json:"thread_id"`
	SandboxID      string             `json:"sandbox_id"`
	Branch         string             `json:"branch"`
	PrUrl          string             `json:"pr_url"`
	History        []string           `json:"history"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	ResponseBlocks [][]byte           `json:"response_blocks"`
	GithubOwner    string             `json:"github_owner"`
	GithubRepo     string             `json:"github_repo"`
	CustomTitle    string             `json:"custom_title"`
	CreatorID      string             `json:"creator_id"`
	AgentSlug      string             `json:"agent_slug"`
	Model          string             `json:"model"`
	TaskOptions    []byte             `json:"task_options"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (UpsertConversationRow, error) {
	row := q.db.QueryRow(ctx, upsertConversation,
		arg.OrgID,
		arg.ThreadID,
		arg.SandboxID,
		arg.Branch,
		arg.PrUrl,
		arg.History,
		arg.ResponseBlocks,
		arg.GithubOwner,
		arg.GithubRepo,
		arg.CreatorID,
		arg.AgentSlug,
		arg.Model,
		arg.TaskOptions,
	)
	var i UpsertConversationRow
	err := row.Scan(
		&i.OrgID,
		&i.ThreadID,
		&i.SandboxID,
		&i.Branch,
		&i.PrUrl,
		&i.History,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResponseBlocks,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.CustomTitle,
		&i.CreatorID,
		&i.AgentSlug,
		&i.Model,
		&i.TaskOptions,
	)
	return i, err
}
