// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_mentions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGithubMentionDeliveriesBefore = `-- name: DeleteGithubMentionDeliveriesBefore :execrows
DELETE FROM github_mention_deliveries WHERE created_at < $1
`

// TTL cleanup, run periodically by the bot. Delivery IDs only need to
// survive realistic GitHub webhook redelivery windows; keeping a
// longer retention window prevents unbounded table growth.
func (q *Queries) DeleteGithubMentionDeliveriesBefore(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGithubMentionDeliveriesBefore, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertGithubMentionDelivery = `-- name: InsertGithubMentionDelivery :execrows
INSERT INTO github_mention_deliveries (org_id, delivery_id, request_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertGithubMentionDeliveryParams struct {
	OrgID      string `json:"org_id"`
	DeliveryID string `json:"delivery_id"`
	RequestID  string `json:"request_id"`
}

func (q *Queries) InsertGithubMentionDelivery(ctx context.Context, arg InsertGithubMentionDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertGithubMentionDelivery, arg.OrgID, arg.DeliveryID, arg.RequestID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertGithubMentionThread = `-- name: UpsertGithubMentionThread :one
INSERT INTO github_mention_threads (
    org_id, owner, repo, subject_type, subject_number,
    thread_id
) VALUES (
    $1, $2, $3, $4,
    $5, $6
)
ON CONFLICT (org_id, owner, repo, subject_type, subject_number) DO UPDATE SET
    thread_id  = github_mention_threads.thread_id,
    updated_at = NOW()
RETURNING org_id, owner, repo, subject_type, subject_number,
          thread_id, created_at, updated_at
`

type UpsertGithubMentionThreadParams struct {
	OrgID         string `json:"org_id"`
	Owner         string `json:"owner"`
	Repo          string `json:"repo"`
	SubjectType   string `json:"subject_type"`
	SubjectNumber int32  `json:"subject_number"`
	ThreadID      string `json:"thread_id"`
}

func (q *Queries) UpsertGithubMentionThread(ctx context.Context, arg UpsertGithubMentionThreadParams) (GithubMentionThread, error) {
	row := q.db.QueryRow(ctx, upsertGithubMentionThread,
		arg.OrgID,
		arg.Owner,
		arg.Repo,
		arg.SubjectType,
		arg.SubjectNumber,
		arg.ThreadID,
	)
	var i GithubMentionThread
	err := row.Scan(
		&i.OrgID,
		&i.Owner,
		&i.Repo,
		&i.SubjectType,
		&i.SubjectNumber,
		&i.ThreadID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
