// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github_app.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteGithubInstallation = `-- name: DeleteGithubInstallation :exec
DELETE FROM github_app_installations WHERE installation_id = $1
`

func (q *Queries) DeleteGithubInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteGithubInstallation, installationID)
	return err
}

const deleteGithubReposByInstallation = `-- name: DeleteGithubReposByInstallation :exec
DELETE FROM github_repos WHERE installation_id = $1
`

func (q *Queries) DeleteGithubReposByInstallation(ctx context.Context, installationID int64) error {
	_, err := q.db.Exec(ctx, deleteGithubReposByInstallation, installationID)
	return err
}

const deleteGithubReposByInstallationExcept = `-- name: DeleteGithubReposByInstallationExcept :exec
DELETE FROM github_repos
WHERE installation_id = $1
  AND repo_id <> ALL($2::BIGINT[])
`

type DeleteGithubReposByInstallationExceptParams struct {
	InstallationID int64   `json:"installation_id"`
	Column2        []int64 `json:"column_2"`
}

// Used by the sync routine: after upserting the current set of repos,
// delete anything that wasn't in the list (revoked access).
func (q *Queries) DeleteGithubReposByInstallationExcept(ctx context.Context, arg DeleteGithubReposByInstallationExceptParams) error {
	_, err := q.db.Exec(ctx, deleteGithubReposByInstallationExcept, arg.InstallationID, arg.Column2)
	return err
}

const deleteGithubTeamMembersForTeam = `-- name: DeleteGithubTeamMembersForTeam :exec
DELETE FROM github_team_members
WHERE installation_id = $1 AND team_id = $2
`

type DeleteGithubTeamMembersForTeamParams struct {
	InstallationID int64 `json:"installation_id"`
	TeamID         int64 `json:"team_id"`
}

func (q *Queries) DeleteGithubTeamMembersForTeam(ctx context.Context, arg DeleteGithubTeamMembersForTeamParams) error {
	_, err := q.db.Exec(ctx, deleteGithubTeamMembersForTeam, arg.InstallationID, arg.TeamID)
	return err
}

const deleteGithubTeamsByInstallationExcept = `-- name: DeleteGithubTeamsByInstallationExcept :exec
DELETE FROM github_teams
WHERE installation_id = $1
  AND team_id <> ALL($2::BIGINT[])
`

type DeleteGithubTeamsByInstallationExceptParams struct {
	InstallationID int64   `json:"installation_id"`
	Column2        []int64 `json:"column_2"`
}

func (q *Queries) DeleteGithubTeamsByInstallationExcept(ctx context.Context, arg DeleteGithubTeamsByInstallationExceptParams) error {
	_, err := q.db.Exec(ctx, deleteGithubTeamsByInstallationExcept, arg.InstallationID, arg.Column2)
	return err
}

const getGithubInstallation = `-- name: GetGithubInstallation :one
SELECT installation_id, org_id, account_login, account_type, account_id, suspended_at, created_at, updated_at
FROM github_app_installations
WHERE installation_id = $1
`

func (q *Queries) GetGithubInstallation(ctx context.Context, installationID int64) (GithubAppInstallation, error) {
	row := q.db.QueryRow(ctx, getGithubInstallation, installationID)
	var i GithubAppInstallation
	err := row.Scan(
		&i.InstallationID,
		&i.OrgID,
		&i.AccountLogin,
		&i.AccountType,
		&i.AccountID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGithubRepoForOrg = `-- name: GetGithubRepoForOrg :one
SELECT r.installation_id, r.repo_id, r.owner, r.name, r.default_branch, r.private, r.last_synced_at
FROM github_repos r
JOIN github_app_installations i ON i.installation_id = r.installation_id
WHERE i.org_id = $1 AND r.owner = $2 AND r.name = $3
  AND i.suspended_at IS NULL
ORDER BY r.installation_id
LIMIT 1
`

type GetGithubRepoForOrgParams struct {
	OrgID string `json:"org_id"`
	Owner string `json:"owner"`
	Name  string `json:"name"`
}

// Resolves an (owner, name) the user typed in chat to a concrete
// (installation_id, repo_id, default_branch) for this org. If the same
// repo is exposed via two installations we prefer the unsuspended one
// and break the remaining tie deterministically by installation_id so
// repeat calls return the same row (and the caller's cached token
// stays warm).
func (q *Queries) GetGithubRepoForOrg(ctx context.Context, arg GetGithubRepoForOrgParams) (GithubRepo, error) {
	row := q.db.QueryRow(ctx, getGithubRepoForOrg, arg.OrgID, arg.Owner, arg.Name)
	var i GithubRepo
	err := row.Scan(
		&i.InstallationID,
		&i.RepoID,
		&i.Owner,
		&i.Name,
		&i.DefaultBranch,
		&i.Private,
		&i.LastSyncedAt,
	)
	return i, err
}

const listGithubInstallationsByOrg = `-- name: ListGithubInstallationsByOrg :many
SELECT installation_id, org_id, account_login, account_type, account_id, suspended_at, created_at, updated_at
FROM github_app_installations
WHERE org_id = $1
ORDER BY account_login
`

func (q *Queries) ListGithubInstallationsByOrg(ctx context.Context, orgID string) ([]GithubAppInstallation, error) {
	rows, err := q.db.Query(ctx, listGithubInstallationsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubAppInstallation
	for rows.Next() {
		var i GithubAppInstallation
		if err := rows.Scan(
			&i.InstallationID,
			&i.OrgID,
			&i.AccountLogin,
			&i.AccountType,
			&i.AccountID,
			&i.SuspendedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubReposByInstallation = `-- name: ListGithubReposByInstallation :many
SELECT installation_id, repo_id, owner, name, default_branch, private, last_synced_at
FROM github_repos
WHERE installation_id = $1
ORDER BY owner, name
`

func (q *Queries) ListGithubReposByInstallation(ctx context.Context, installationID int64) ([]GithubRepo, error) {
	rows, err := q.db.Query(ctx, listGithubReposByInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubRepo
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.InstallationID,
			&i.RepoID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Private,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubReposByOrg = `-- name: ListGithubReposByOrg :many
SELECT r.installation_id, r.repo_id, r.owner, r.name, r.default_branch, r.private, r.last_synced_at
FROM github_repos r
JOIN github_app_installations i ON i.installation_id = r.installation_id
WHERE i.org_id = $1
ORDER BY r.owner, r.name
`

// Every repo accessible to the given Hetchy org, across all of its
// GitHub App installations. Powers the "default repo" picker and the
// per-conversation repo selector.
func (q *Queries) ListGithubReposByOrg(ctx context.Context, orgID string) ([]GithubRepo, error) {
	rows, err := q.db.Query(ctx, listGithubReposByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubRepo
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.InstallationID,
			&i.RepoID,
			&i.Owner,
			&i.Name,
			&i.DefaultBranch,
			&i.Private,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubTeamMembers = `-- name: ListGithubTeamMembers :many
SELECT installation_id, team_id, github_user_id, github_login
FROM github_team_members
WHERE installation_id = $1 AND team_id = $2
ORDER BY github_login
`

type ListGithubTeamMembersParams struct {
	InstallationID int64 `json:"installation_id"`
	TeamID         int64 `json:"team_id"`
}

func (q *Queries) ListGithubTeamMembers(ctx context.Context, arg ListGithubTeamMembersParams) ([]GithubTeamMember, error) {
	rows, err := q.db.Query(ctx, listGithubTeamMembers, arg.InstallationID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubTeamMember
	for rows.Next() {
		var i GithubTeamMember
		if err := rows.Scan(
			&i.InstallationID,
			&i.TeamID,
			&i.GithubUserID,
			&i.GithubLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGithubTeamsByInstallation = `-- name: ListGithubTeamsByInstallation :many
SELECT installation_id, team_id, slug, name, parent_team_id, last_synced_at
FROM github_teams
WHERE installation_id = $1
ORDER BY slug
`

func (q *Queries) ListGithubTeamsByInstallation(ctx context.Context, installationID int64) ([]GithubTeam, error) {
	rows, err := q.db.Query(ctx, listGithubTeamsByInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubTeam
	for rows.Next() {
		var i GithubTeam
		if err := rows.Scan(
			&i.InstallationID,
			&i.TeamID,
			&i.Slug,
			&i.Name,
			&i.ParentTeamID,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGithubInstallation = `-- name: UpsertGithubInstallation :one

INSERT INTO github_app_installations (
    installation_id, org_id, account_login, account_type, account_id, suspended_at
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (installation_id) DO UPDATE SET
    org_id        = EXCLUDED.org_id,
    account_login = EXCLUDED.account_login,
    account_type  = EXCLUDED.account_type,
    account_id    = EXCLUDED.account_id,
    suspended_at  = EXCLUDED.suspended_at,
    updated_at    = NOW()
WHERE github_app_installations.org_id = EXCLUDED.org_id
RETURNING installation_id, org_id, account_login, account_type, account_id, suspended_at, created_at, updated_at
`

type UpsertGithubInstallationParams struct {
	InstallationID int64              `json:"installation_id"`
	OrgID          string             `json:"org_id"`
	AccountLogin   string             `json:"account_login"`
	AccountType    string             `json:"account_type"`
	AccountID      int64              `json:"account_id"`
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
}

// Queries for the GitHub App installation cache: installations, the
// repos they grant access to, and (for Organization installs) team
// + membership snapshots.
// The WHERE clause on the DO UPDATE is the SQL-level guard against
// one Hetchy org silently rebinding another org's installation_id.
// The Go-side pre-check covers the common case with a clean error;
// this WHERE closes the TOCTOU window where two simultaneous installs
// of the same installation_id from different orgs could race past the
// pre-check. On a cross-org conflict the UPDATE doesn't fire and
// RETURNING yields zero rows — callers must handle pgx.ErrNoRows.
func (q *Queries) UpsertGithubInstallation(ctx context.Context, arg UpsertGithubInstallationParams) (GithubAppInstallation, error) {
	row := q.db.QueryRow(ctx, upsertGithubInstallation,
		arg.InstallationID,
		arg.OrgID,
		arg.AccountLogin,
		arg.AccountType,
		arg.AccountID,
		arg.SuspendedAt,
	)
	var i GithubAppInstallation
	err := row.Scan(
		&i.InstallationID,
		&i.OrgID,
		&i.AccountLogin,
		&i.AccountType,
		&i.AccountID,
		&i.SuspendedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertGithubRepo = `-- name: UpsertGithubRepo :exec
INSERT INTO github_repos (
    installation_id, repo_id, owner, name, default_branch, private, last_synced_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (installation_id, repo_id) DO UPDATE SET
    owner          = EXCLUDED.owner,
    name           = EXCLUDED.name,
    default_branch = EXCLUDED.default_branch,
    private        = EXCLUDED.private,
    last_synced_at = NOW()
`

type UpsertGithubRepoParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Owner          string `json:"owner"`
	Name           string `json:"name"`
	DefaultBranch  string `json:"default_branch"`
	Private        bool   `json:"private"`
}

func (q *Queries) UpsertGithubRepo(ctx context.Context, arg UpsertGithubRepoParams) error {
	_, err := q.db.Exec(ctx, upsertGithubRepo,
		arg.InstallationID,
		arg.RepoID,
		arg.Owner,
		arg.Name,
		arg.DefaultBranch,
		arg.Private,
	)
	return err
}

const upsertGithubTeam = `-- name: UpsertGithubTeam :exec
INSERT INTO github_teams (
    installation_id, team_id, slug, name, parent_team_id, last_synced_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (installation_id, team_id) DO UPDATE SET
    slug           = EXCLUDED.slug,
    name           = EXCLUDED.name,
    parent_team_id = EXCLUDED.parent_team_id,
    last_synced_at = NOW()
`

type UpsertGithubTeamParams struct {
	InstallationID int64  `json:"installation_id"`
	TeamID         int64  `json:"team_id"`
	Slug           string `json:"slug"`
	Name           string `json:"name"`
	ParentTeamID   *int64 `json:"parent_team_id"`
}

func (q *Queries) UpsertGithubTeam(ctx context.Context, arg UpsertGithubTeamParams) error {
	_, err := q.db.Exec(ctx, upsertGithubTeam,
		arg.InstallationID,
		arg.TeamID,
		arg.Slug,
		arg.Name,
		arg.ParentTeamID,
	)
	return err
}

const upsertGithubTeamMember = `-- name: UpsertGithubTeamMember :exec
INSERT INTO github_team_members (
    installation_id, team_id, github_user_id, github_login
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (installation_id, team_id, github_user_id) DO UPDATE SET
    github_login = EXCLUDED.github_login
`

type UpsertGithubTeamMemberParams struct {
	InstallationID int64  `json:"installation_id"`
	TeamID         int64  `json:"team_id"`
	GithubUserID   int64  `json:"github_user_id"`
	GithubLogin    string `json:"github_login"`
}

func (q *Queries) UpsertGithubTeamMember(ctx context.Context, arg UpsertGithubTeamMemberParams) error {
	_, err := q.db.Exec(ctx, upsertGithubTeamMember,
		arg.InstallationID,
		arg.TeamID,
		arg.GithubUserID,
		arg.GithubLogin,
	)
	return err
}
