// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: health_checks.sql

package sqlc

import (
	"context"
)

const insertHealthCheck = `-- name: InsertHealthCheck :one

INSERT INTO health_checks (note)
VALUES ($1)
RETURNING id, checked_at, note
`

// Example scaffolding: these queries (and the matching health_checks
// migration) exist only to demonstrate the sqlc + golang-migrate flow on a
// live table. Delete this file and the 20260501000001_init migration once
// you have a real schema.
func (q *Queries) InsertHealthCheck(ctx context.Context, note string) (HealthCheck, error) {
	row := q.db.QueryRow(ctx, insertHealthCheck, note)
	var i HealthCheck
	err := row.Scan(&i.ID, &i.CheckedAt, &i.Note)
	return i, err
}

const latestHealthCheck = `-- name: LatestHealthCheck :one
SELECT id, checked_at, note
FROM health_checks
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) LatestHealthCheck(ctx context.Context) (HealthCheck, error) {
	row := q.db.QueryRow(ctx, latestHealthCheck)
	var i HealthCheck
	err := row.Scan(&i.ID, &i.CheckedAt, &i.Note)
	return i, err
}
