// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentJob = `-- name: CreateAgentJob :one
INSERT INTO agent_jobs (
    id, org_id, name, definition, agent_slug,
    primary_owner, primary_repo, additional_repos,
    cron_schedule, timezone, enabled, next_run_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9, $10, $11, $12
)
RETURNING id, org_id, name, definition, agent_slug,
          primary_owner, primary_repo, additional_repos,
          cron_schedule, timezone, enabled, next_run_at,
          last_run_at, last_run_id, last_error, created_at, updated_at
`

type CreateAgentJobParams struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Definition      string             `json:"definition"`
	AgentSlug       string             `json:"agent_slug"`
	PrimaryOwner    string             `json:"primary_owner"`
	PrimaryRepo     string             `json:"primary_repo"`
	AdditionalRepos []byte             `json:"additional_repos"`
	CronSchedule    string             `json:"cron_schedule"`
	Timezone        string             `json:"timezone"`
	Enabled         bool               `json:"enabled"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) CreateAgentJob(ctx context.Context, arg CreateAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, createAgentJob,
		arg.ID,
		arg.OrgID,
		arg.Name,
		arg.Definition,
		arg.AgentSlug,
		arg.PrimaryOwner,
		arg.PrimaryRepo,
		arg.AdditionalRepos,
		arg.CronSchedule,
		arg.Timezone,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Definition,
		&i.AgentSlug,
		&i.PrimaryOwner,
		&i.PrimaryRepo,
		&i.AdditionalRepos,
		&i.CronSchedule,
		&i.Timezone,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAgentJobExecution = `-- name: CreateAgentJobExecution :one
INSERT INTO agent_job_executions (
    id, job_id, org_id, scheduled_for, status, claimed_by, claimed_at
) VALUES (
    $1, $2, $3, $4, 'claimed', $5, NOW()
)
RETURNING id, job_id, org_id, run_id, scheduled_for, status,
          claimed_by, claimed_at, finished_at, error, created_at, updated_at
`

type CreateAgentJobExecutionParams struct {
	ID           string             `json:"id"`
	JobID        string             `json:"job_id"`
	OrgID        string             `json:"org_id"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	ClaimedBy    string             `json:"claimed_by"`
}

func (q *Queries) CreateAgentJobExecution(ctx context.Context, arg CreateAgentJobExecutionParams) (AgentJobExecution, error) {
	row := q.db.QueryRow(ctx, createAgentJobExecution,
		arg.ID,
		arg.JobID,
		arg.OrgID,
		arg.ScheduledFor,
		arg.ClaimedBy,
	)
	var i AgentJobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OrgID,
		&i.RunID,
		&i.ScheduledFor,
		&i.Status,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentJob = `-- name: DeleteAgentJob :execrows
DELETE FROM agent_jobs
WHERE org_id = $1 AND id = $2
`

type DeleteAgentJobParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) DeleteAgentJob(ctx context.Context, arg DeleteAgentJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAgentJob, arg.OrgID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAgentJob = `-- name: GetAgentJob :one
SELECT id, org_id, name, definition, agent_slug,
       primary_owner, primary_repo, additional_repos,
       cron_schedule, timezone, enabled, next_run_at,
       last_run_at, last_run_id, last_error, created_at, updated_at
FROM agent_jobs
WHERE org_id = $1 AND id = $2
`

type GetAgentJobParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetAgentJob(ctx context.Context, arg GetAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJob, arg.OrgID, arg.ID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Definition,
		&i.AgentSlug,
		&i.PrimaryOwner,
		&i.PrimaryRepo,
		&i.AdditionalRepos,
		&i.CronSchedule,
		&i.Timezone,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobExecution = `-- name: GetAgentJobExecution :one
SELECT id, job_id, org_id, run_id, scheduled_for, status,
       claimed_by, claimed_at, finished_at, error, created_at, updated_at
FROM agent_job_executions
WHERE org_id = $1 AND id = $2
`

type GetAgentJobExecutionParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetAgentJobExecution(ctx context.Context, arg GetAgentJobExecutionParams) (AgentJobExecution, error) {
	row := q.db.QueryRow(ctx, getAgentJobExecution, arg.OrgID, arg.ID)
	var i AgentJobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OrgID,
		&i.RunID,
		&i.ScheduledFor,
		&i.Status,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgentJobForUpdate = `-- name: GetAgentJobForUpdate :one
SELECT id, org_id, name, definition, agent_slug,
       primary_owner, primary_repo, additional_repos,
       cron_schedule, timezone, enabled, next_run_at,
       last_run_at, last_run_id, last_error, created_at, updated_at
FROM agent_jobs
WHERE org_id = $1 AND id = $2
FOR UPDATE
`

type GetAgentJobForUpdateParams struct {
	OrgID string `json:"org_id"`
	ID    string `json:"id"`
}

func (q *Queries) GetAgentJobForUpdate(ctx context.Context, arg GetAgentJobForUpdateParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, getAgentJobForUpdate, arg.OrgID, arg.ID)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Definition,
		&i.AgentSlug,
		&i.PrimaryOwner,
		&i.PrimaryRepo,
		&i.AdditionalRepos,
		&i.CronSchedule,
		&i.Timezone,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestAgentJobExecution = `-- name: GetLatestAgentJobExecution :one
SELECT id, job_id, org_id, run_id, scheduled_for, status,
       claimed_by, claimed_at, finished_at, error, created_at, updated_at
FROM agent_job_executions
WHERE org_id = $1 AND job_id = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLatestAgentJobExecutionParams struct {
	OrgID string `json:"org_id"`
	JobID string `json:"job_id"`
}

func (q *Queries) GetLatestAgentJobExecution(ctx context.Context, arg GetLatestAgentJobExecutionParams) (AgentJobExecution, error) {
	row := q.db.QueryRow(ctx, getLatestAgentJobExecution, arg.OrgID, arg.JobID)
	var i AgentJobExecution
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.OrgID,
		&i.RunID,
		&i.ScheduledFor,
		&i.Status,
		&i.ClaimedBy,
		&i.ClaimedAt,
		&i.FinishedAt,
		&i.Error,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasActiveAgentJobExecution = `-- name: HasActiveAgentJobExecution :one
SELECT EXISTS (
    SELECT 1
    FROM agent_job_executions
    WHERE job_id = $1
      AND status IN ('claimed', 'running')
)::boolean
`

func (q *Queries) HasActiveAgentJobExecution(ctx context.Context, jobID string) (bool, error) {
	row := q.db.QueryRow(ctx, hasActiveAgentJobExecution, jobID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listAgentJobExecutionsByJob = `-- name: ListAgentJobExecutionsByJob :many
SELECT id, job_id, org_id, run_id, scheduled_for, status,
       claimed_by, claimed_at, finished_at, error, created_at, updated_at
FROM agent_job_executions
WHERE org_id = $1 AND job_id = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListAgentJobExecutionsByJobParams struct {
	OrgID string `json:"org_id"`
	JobID string `json:"job_id"`
	Limit int32  `json:"limit"`
}

func (q *Queries) ListAgentJobExecutionsByJob(ctx context.Context, arg ListAgentJobExecutionsByJobParams) ([]AgentJobExecution, error) {
	rows, err := q.db.Query(ctx, listAgentJobExecutionsByJob, arg.OrgID, arg.JobID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentJobExecution
	for rows.Next() {
		var i AgentJobExecution
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.OrgID,
			&i.RunID,
			&i.ScheduledFor,
			&i.Status,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.FinishedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentJobsByAgent = `-- name: ListAgentJobsByAgent :many
SELECT id, org_id, name, definition, agent_slug,
       primary_owner, primary_repo, additional_repos,
       cron_schedule, timezone, enabled, next_run_at,
       last_run_at, last_run_id, last_error, created_at, updated_at
FROM agent_jobs
WHERE org_id = $1 AND agent_slug = $2
ORDER BY enabled DESC, next_run_at ASC NULLS LAST, created_at DESC
`

type ListAgentJobsByAgentParams struct {
	OrgID     string `json:"org_id"`
	AgentSlug string `json:"agent_slug"`
}

func (q *Queries) ListAgentJobsByAgent(ctx context.Context, arg ListAgentJobsByAgentParams) ([]AgentJob, error) {
	rows, err := q.db.Query(ctx, listAgentJobsByAgent, arg.OrgID, arg.AgentSlug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentJob
	for rows.Next() {
		var i AgentJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Definition,
			&i.AgentSlug,
			&i.PrimaryOwner,
			&i.PrimaryRepo,
			&i.AdditionalRepos,
			&i.CronSchedule,
			&i.Timezone,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentJobsByOrg = `-- name: ListAgentJobsByOrg :many
SELECT id, org_id, name, definition, agent_slug,
       primary_owner, primary_repo, additional_repos,
       cron_schedule, timezone, enabled, next_run_at,
       last_run_at, last_run_id, last_error, created_at, updated_at
FROM agent_jobs
WHERE org_id = $1
ORDER BY enabled DESC, next_run_at ASC NULLS LAST, created_at DESC
`

func (q *Queries) ListAgentJobsByOrg(ctx context.Context, orgID string) ([]AgentJob, error) {
	rows, err := q.db.Query(ctx, listAgentJobsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentJob
	for rows.Next() {
		var i AgentJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Definition,
			&i.AgentSlug,
			&i.PrimaryOwner,
			&i.PrimaryRepo,
			&i.AdditionalRepos,
			&i.CronSchedule,
			&i.Timezone,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClaimableDueAgentJobs = `-- name: ListClaimableDueAgentJobs :many
SELECT id, org_id, name, definition, agent_slug,
       primary_owner, primary_repo, additional_repos,
       cron_schedule, timezone, enabled, next_run_at,
       last_run_at, last_run_id, last_error, created_at, updated_at
FROM agent_jobs j
WHERE enabled = TRUE
  AND next_run_at IS NOT NULL
  AND next_run_at <= $1
  AND NOT EXISTS (
    SELECT 1
    FROM agent_job_executions e
    WHERE e.job_id = j.id
      AND e.status IN ('claimed', 'running')
  )
ORDER BY next_run_at ASC, id ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ListClaimableDueAgentJobsParams struct {
	NowAt      pgtype.Timestamptz `json:"now_at"`
	LimitCount int32              `json:"limit_count"`
}

func (q *Queries) ListClaimableDueAgentJobs(ctx context.Context, arg ListClaimableDueAgentJobsParams) ([]AgentJob, error) {
	rows, err := q.db.Query(ctx, listClaimableDueAgentJobs, arg.NowAt, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentJob
	for rows.Next() {
		var i AgentJob
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Definition,
			&i.AgentSlug,
			&i.PrimaryOwner,
			&i.PrimaryRepo,
			&i.AdditionalRepos,
			&i.CronSchedule,
			&i.Timezone,
			&i.Enabled,
			&i.NextRunAt,
			&i.LastRunAt,
			&i.LastRunID,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestAgentJobExecutionsByOrg = `-- name: ListLatestAgentJobExecutionsByOrg :many
SELECT DISTINCT ON (job_id)
       id, job_id, org_id, run_id, scheduled_for, status,
       claimed_by, claimed_at, finished_at, error, created_at, updated_at
FROM agent_job_executions
WHERE org_id = $1
ORDER BY job_id, created_at DESC, id DESC
`

func (q *Queries) ListLatestAgentJobExecutionsByOrg(ctx context.Context, orgID string) ([]AgentJobExecution, error) {
	rows, err := q.db.Query(ctx, listLatestAgentJobExecutionsByOrg, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentJobExecution
	for rows.Next() {
		var i AgentJobExecution
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.OrgID,
			&i.RunID,
			&i.ScheduledFor,
			&i.Status,
			&i.ClaimedBy,
			&i.ClaimedAt,
			&i.FinishedAt,
			&i.Error,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAgentJobExecutionFinished = `-- name: MarkAgentJobExecutionFinished :execrows
UPDATE agent_job_executions
SET status = $3,
    finished_at = NOW(),
    error = $4,
    updated_at = NOW()
WHERE org_id = $1
  AND id = $2
  AND status IN ('claimed', 'running')
`

type MarkAgentJobExecutionFinishedParams struct {
	OrgID  string `json:"org_id"`
	ID     string `json:"id"`
	Status string `json:"status"`
	Error  string `json:"error"`
}

func (q *Queries) MarkAgentJobExecutionFinished(ctx context.Context, arg MarkAgentJobExecutionFinishedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAgentJobExecutionFinished,
		arg.OrgID,
		arg.ID,
		arg.Status,
		arg.Error,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markAgentJobExecutionRunning = `-- name: MarkAgentJobExecutionRunning :execrows
UPDATE agent_job_executions
SET status = 'running',
    run_id = COALESCE($3, run_id),
    updated_at = NOW()
WHERE org_id = $1
  AND id = $2
  AND status IN ('claimed', 'running')
`

type MarkAgentJobExecutionRunningParams struct {
	OrgID string  `json:"org_id"`
	ID    string  `json:"id"`
	RunID *string `json:"run_id"`
}

func (q *Queries) MarkAgentJobExecutionRunning(ctx context.Context, arg MarkAgentJobExecutionRunningParams) (int64, error) {
	result, err := q.db.Exec(ctx, markAgentJobExecutionRunning, arg.OrgID, arg.ID, arg.RunID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseStaleClaimedAgentJobExecutions = `-- name: ReleaseStaleClaimedAgentJobExecutions :execrows
UPDATE agent_job_executions
SET status = 'failed',
    finished_at = NOW(),
    error = 'job dispatch claim timed out',
    updated_at = NOW()
WHERE status = 'claimed'
  AND claimed_at IS NOT NULL
  AND claimed_at < NOW() - $1::interval
`

func (q *Queries) ReleaseStaleClaimedAgentJobExecutions(ctx context.Context, staleAfter pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, releaseStaleClaimedAgentJobExecutions, staleAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAgentJob = `-- name: UpdateAgentJob :one
UPDATE agent_jobs
SET name = $3,
    definition = $4,
    agent_slug = $5,
    primary_owner = $6,
    primary_repo = $7,
    additional_repos = $8,
    cron_schedule = $9,
    timezone = $10,
    enabled = $11,
    next_run_at = $12,
    updated_at = NOW()
WHERE org_id = $1 AND id = $2
RETURNING id, org_id, name, definition, agent_slug,
          primary_owner, primary_repo, additional_repos,
          cron_schedule, timezone, enabled, next_run_at,
          last_run_at, last_run_id, last_error, created_at, updated_at
`

type UpdateAgentJobParams struct {
	OrgID           string             `json:"org_id"`
	ID              string             `json:"id"`
	Name            string             `json:"name"`
	Definition      string             `json:"definition"`
	AgentSlug       string             `json:"agent_slug"`
	PrimaryOwner    string             `json:"primary_owner"`
	PrimaryRepo     string             `json:"primary_repo"`
	AdditionalRepos []byte             `json:"additional_repos"`
	CronSchedule    string             `json:"cron_schedule"`
	Timezone        string             `json:"timezone"`
	Enabled         bool               `json:"enabled"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateAgentJob(ctx context.Context, arg UpdateAgentJobParams) (AgentJob, error) {
	row := q.db.QueryRow(ctx, updateAgentJob,
		arg.OrgID,
		arg.ID,
		arg.Name,
		arg.Definition,
		arg.AgentSlug,
		arg.PrimaryOwner,
		arg.PrimaryRepo,
		arg.AdditionalRepos,
		arg.CronSchedule,
		arg.Timezone,
		arg.Enabled,
		arg.NextRunAt,
	)
	var i AgentJob
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Definition,
		&i.AgentSlug,
		&i.PrimaryOwner,
		&i.PrimaryRepo,
		&i.AdditionalRepos,
		&i.CronSchedule,
		&i.Timezone,
		&i.Enabled,
		&i.NextRunAt,
		&i.LastRunAt,
		&i.LastRunID,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAgentJobLastRun = `-- name: UpdateAgentJobLastRun :exec
UPDATE agent_jobs
SET last_run_at = $2,
    last_run_id = $3,
    last_error = $4,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentJobLastRunParams struct {
	ID        string             `json:"id"`
	LastRunAt pgtype.Timestamptz `json:"last_run_at"`
	LastRunID *string            `json:"last_run_id"`
	LastError string             `json:"last_error"`
}

func (q *Queries) UpdateAgentJobLastRun(ctx context.Context, arg UpdateAgentJobLastRunParams) error {
	_, err := q.db.Exec(ctx, updateAgentJobLastRun,
		arg.ID,
		arg.LastRunAt,
		arg.LastRunID,
		arg.LastError,
	)
	return err
}

const updateAgentJobNextRun = `-- name: UpdateAgentJobNextRun :exec
UPDATE agent_jobs
SET next_run_at = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateAgentJobNextRunParams struct {
	ID        string             `json:"id"`
	NextRunAt pgtype.Timestamptz `json:"next_run_at"`
}

func (q *Queries) UpdateAgentJobNextRun(ctx context.Context, arg UpdateAgentJobNextRunParams) error {
	_, err := q.db.Exec(ctx, updateAgentJobNextRun, arg.ID, arg.NextRunAt)
	return err
}
