// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: linear_sessions.sql

package sqlc

import (
	"context"
)

const deleteLinearAgentSessionsByOrg = `-- name: DeleteLinearAgentSessionsByOrg :exec
DELETE FROM linear_agent_sessions WHERE org_id = $1
`

func (q *Queries) DeleteLinearAgentSessionsByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteLinearAgentSessionsByOrg, orgID)
	return err
}

const getLinearAgentSession = `-- name: GetLinearAgentSession :one
SELECT agent_session_id, org_id, thread_id, issue_id, issue_identifier, issue_url, created_at
FROM linear_agent_sessions
WHERE agent_session_id = $1
`

func (q *Queries) GetLinearAgentSession(ctx context.Context, agentSessionID string) (LinearAgentSession, error) {
	row := q.db.QueryRow(ctx, getLinearAgentSession, agentSessionID)
	var i LinearAgentSession
	err := row.Scan(
		&i.AgentSessionID,
		&i.OrgID,
		&i.ThreadID,
		&i.IssueID,
		&i.IssueIdentifier,
		&i.IssueUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertLinearAgentSession = `-- name: InsertLinearAgentSession :one
INSERT INTO linear_agent_sessions (
    agent_session_id, org_id, thread_id, issue_id, issue_identifier, issue_url
) VALUES (
    $1, $2, $3, $4, $5, $6
)
ON CONFLICT (agent_session_id) DO UPDATE SET
    agent_session_id = EXCLUDED.agent_session_id
RETURNING agent_session_id, org_id, thread_id, issue_id, issue_identifier, issue_url, created_at
`

type InsertLinearAgentSessionParams struct {
	AgentSessionID  string `json:"agent_session_id"`
	OrgID           string `json:"org_id"`
	ThreadID        string `json:"thread_id"`
	IssueID         string `json:"issue_id"`
	IssueIdentifier string `json:"issue_identifier"`
	IssueUrl        string `json:"issue_url"`
}

// A webhook redelivery may re-insert the same session; keep the first
// row's thread mapping so a duplicate `created` event can't re-point
// an in-flight conversation at a different thread.
func (q *Queries) InsertLinearAgentSession(ctx context.Context, arg InsertLinearAgentSessionParams) (LinearAgentSession, error) {
	row := q.db.QueryRow(ctx, insertLinearAgentSession,
		arg.AgentSessionID,
		arg.OrgID,
		arg.ThreadID,
		arg.IssueID,
		arg.IssueIdentifier,
		arg.IssueUrl,
	)
	var i LinearAgentSession
	err := row.Scan(
		&i.AgentSessionID,
		&i.OrgID,
		&i.ThreadID,
		&i.IssueID,
		&i.IssueIdentifier,
		&i.IssueUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listLinearAgentSessionsByIssue = `-- name: ListLinearAgentSessionsByIssue :many
SELECT agent_session_id, org_id, thread_id, issue_id, issue_identifier, issue_url, created_at
FROM linear_agent_sessions
WHERE org_id = $1 AND issue_id = $2
ORDER BY created_at DESC
`

type ListLinearAgentSessionsByIssueParams struct {
	OrgID   string `json:"org_id"`
	IssueID string `json:"issue_id"`
}

// Newest-first so the resume check prefers the most recent prior
// conversation on the issue.
func (q *Queries) ListLinearAgentSessionsByIssue(ctx context.Context, arg ListLinearAgentSessionsByIssueParams) ([]LinearAgentSession, error) {
	rows, err := q.db.Query(ctx, listLinearAgentSessionsByIssue, arg.OrgID, arg.IssueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinearAgentSession
	for rows.Next() {
		var i LinearAgentSession
		if err := rows.Scan(
			&i.AgentSessionID,
			&i.OrgID,
			&i.ThreadID,
			&i.IssueID,
			&i.IssueIdentifier,
			&i.IssueUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
