// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: local_auth.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptLocalAuthInvitation = `-- name: AcceptLocalAuthInvitation :exec
UPDATE local_auth_invitations
SET accepted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

func (q *Queries) AcceptLocalAuthInvitation(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, acceptLocalAuthInvitation, id)
	return err
}

const countLocalAuthAdmins = `-- name: CountLocalAuthAdmins :one
SELECT COUNT(*)::int
FROM local_auth_memberships
WHERE org_id = $1 AND role_slug = 'admin'
`

func (q *Queries) CountLocalAuthAdmins(ctx context.Context, orgID string) (int32, error) {
	row := q.db.QueryRow(ctx, countLocalAuthAdmins, orgID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLocalAuthUserOrgs = `-- name: CountLocalAuthUserOrgs :one
SELECT COUNT(*)::int
FROM local_auth_memberships
WHERE user_id = $1
`

func (q *Queries) CountLocalAuthUserOrgs(ctx context.Context, userID string) (int32, error) {
	row := q.db.QueryRow(ctx, countLocalAuthUserOrgs, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createLocalAuthInvitation = `-- name: CreateLocalAuthInvitation :one
INSERT INTO local_auth_invitations (
    id, org_id, email, email_normalized, role_slug, token_hash, expires_at, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, org_id, email, email_normalized, role_slug, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at, updated_at
`

type CreateLocalAuthInvitationParams struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Email           string             `json:"email"`
	EmailNormalized string             `json:"email_normalized"`
	RoleSlug        string             `json:"role_slug"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	CreatedBy       *string            `json:"created_by"`
}

func (q *Queries) CreateLocalAuthInvitation(ctx context.Context, arg CreateLocalAuthInvitationParams) (LocalAuthInvitation, error) {
	row := q.db.QueryRow(ctx, createLocalAuthInvitation,
		arg.ID,
		arg.OrgID,
		arg.Email,
		arg.EmailNormalized,
		arg.RoleSlug,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i LocalAuthInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.EmailNormalized,
		&i.RoleSlug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalAuthMembership = `-- name: CreateLocalAuthMembership :one
INSERT INTO local_auth_memberships (id, user_id, org_id, role_slug)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, org_id) DO UPDATE SET
    role_slug = EXCLUDED.role_slug,
    updated_at = NOW()
RETURNING id, user_id, org_id, role_slug, created_at, updated_at
`

type CreateLocalAuthMembershipParams struct {
	ID       string `json:"id"`
	UserID   string `json:"user_id"`
	OrgID    string `json:"org_id"`
	RoleSlug string `json:"role_slug"`
}

func (q *Queries) CreateLocalAuthMembership(ctx context.Context, arg CreateLocalAuthMembershipParams) (LocalAuthMembership, error) {
	row := q.db.QueryRow(ctx, createLocalAuthMembership,
		arg.ID,
		arg.UserID,
		arg.OrgID,
		arg.RoleSlug,
	)
	var i LocalAuthMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.RoleSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalAuthOrg = `-- name: CreateLocalAuthOrg :one
INSERT INTO local_auth_orgs (id, name)
VALUES ($1, $2)
RETURNING id, name, created_at, updated_at
`

type CreateLocalAuthOrgParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateLocalAuthOrg(ctx context.Context, arg CreateLocalAuthOrgParams) (LocalAuthOrg, error) {
	row := q.db.QueryRow(ctx, createLocalAuthOrg, arg.ID, arg.Name)
	var i LocalAuthOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLocalAuthSession = `-- name: CreateLocalAuthSession :one
INSERT INTO local_auth_sessions (
    id, user_id, token_hash, active_org_id, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, user_id, token_hash, active_org_id, expires_at, last_seen_at, created_at
`

type CreateLocalAuthSessionParams struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	TokenHash   []byte             `json:"token_hash"`
	ActiveOrgID *string            `json:"active_org_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateLocalAuthSession(ctx context.Context, arg CreateLocalAuthSessionParams) (LocalAuthSession, error) {
	row := q.db.QueryRow(ctx, createLocalAuthSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ActiveOrgID,
		arg.ExpiresAt,
	)
	var i LocalAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ActiveOrgID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createLocalAuthUser = `-- name: CreateLocalAuthUser :one
INSERT INTO local_auth_users (
    id, email, email_normalized, password_hash, first_name, last_name
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, email, email_normalized, password_hash, first_name, last_name, created_at, updated_at
`

type CreateLocalAuthUserParams struct {
	ID              string `json:"id"`
	Email           string `json:"email"`
	EmailNormalized string `json:"email_normalized"`
	PasswordHash    []byte `json:"password_hash"`
	FirstName       string `json:"first_name"`
	LastName        string `json:"last_name"`
}

func (q *Queries) CreateLocalAuthUser(ctx context.Context, arg CreateLocalAuthUserParams) (LocalAuthUser, error) {
	row := q.db.QueryRow(ctx, createLocalAuthUser,
		arg.ID,
		arg.Email,
		arg.EmailNormalized,
		arg.PasswordHash,
		arg.FirstName,
		arg.LastName,
	)
	var i LocalAuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteExpiredLocalAuthSessions = `-- name: DeleteExpiredLocalAuthSessions :exec
DELETE FROM local_auth_sessions WHERE expires_at <= NOW()
`

func (q *Queries) DeleteExpiredLocalAuthSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredLocalAuthSessions)
	return err
}

const deleteLocalAuthMembership = `-- name: DeleteLocalAuthMembership :exec
DELETE FROM local_auth_memberships WHERE id = $1
`

func (q *Queries) DeleteLocalAuthMembership(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocalAuthMembership, id)
	return err
}

const deleteLocalAuthOrg = `-- name: DeleteLocalAuthOrg :exec
DELETE FROM local_auth_orgs WHERE id = $1
`

func (q *Queries) DeleteLocalAuthOrg(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocalAuthOrg, id)
	return err
}

const deleteLocalAuthSession = `-- name: DeleteLocalAuthSession :exec
DELETE FROM local_auth_sessions WHERE id = $1
`

func (q *Queries) DeleteLocalAuthSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocalAuthSession, id)
	return err
}

const deleteLocalAuthSessionsForUser = `-- name: DeleteLocalAuthSessionsForUser :exec
DELETE FROM local_auth_sessions WHERE user_id = $1
`

func (q *Queries) DeleteLocalAuthSessionsForUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteLocalAuthSessionsForUser, userID)
	return err
}

const deleteLocalAuthUser = `-- name: DeleteLocalAuthUser :exec
DELETE FROM local_auth_users WHERE id = $1
`

func (q *Queries) DeleteLocalAuthUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteLocalAuthUser, id)
	return err
}

const findLocalAuthOrgUserByEmail = `-- name: FindLocalAuthOrgUserByEmail :one
SELECT u.id, u.email, u.email_normalized, u.password_hash, u.first_name, u.last_name, u.created_at, u.updated_at
FROM local_auth_users u
JOIN local_auth_memberships m ON m.user_id = u.id
WHERE m.org_id = $1 AND u.email_normalized = $2
`

type FindLocalAuthOrgUserByEmailParams struct {
	OrgID           string `json:"org_id"`
	EmailNormalized string `json:"email_normalized"`
}

func (q *Queries) FindLocalAuthOrgUserByEmail(ctx context.Context, arg FindLocalAuthOrgUserByEmailParams) (LocalAuthUser, error) {
	row := q.db.QueryRow(ctx, findLocalAuthOrgUserByEmail, arg.OrgID, arg.EmailNormalized)
	var i LocalAuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthInvitation = `-- name: GetLocalAuthInvitation :one
SELECT id, org_id, email, email_normalized, role_slug, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at, updated_at
FROM local_auth_invitations
WHERE id = $1
`

func (q *Queries) GetLocalAuthInvitation(ctx context.Context, id string) (LocalAuthInvitation, error) {
	row := q.db.QueryRow(ctx, getLocalAuthInvitation, id)
	var i LocalAuthInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.EmailNormalized,
		&i.RoleSlug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthInvitationByTokenHash = `-- name: GetLocalAuthInvitationByTokenHash :one
SELECT id, org_id, email, email_normalized, role_slug, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at, updated_at
FROM local_auth_invitations
WHERE token_hash = $1
`

func (q *Queries) GetLocalAuthInvitationByTokenHash(ctx context.Context, tokenHash []byte) (LocalAuthInvitation, error) {
	row := q.db.QueryRow(ctx, getLocalAuthInvitationByTokenHash, tokenHash)
	var i LocalAuthInvitation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Email,
		&i.EmailNormalized,
		&i.RoleSlug,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.RevokedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthMembership = `-- name: GetLocalAuthMembership :one
SELECT id, user_id, org_id, role_slug, created_at, updated_at
FROM local_auth_memberships
WHERE id = $1
`

func (q *Queries) GetLocalAuthMembership(ctx context.Context, id string) (LocalAuthMembership, error) {
	row := q.db.QueryRow(ctx, getLocalAuthMembership, id)
	var i LocalAuthMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.RoleSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthMembershipForUserOrg = `-- name: GetLocalAuthMembershipForUserOrg :one
SELECT id, user_id, org_id, role_slug, created_at, updated_at
FROM local_auth_memberships
WHERE user_id = $1 AND org_id = $2
`

type GetLocalAuthMembershipForUserOrgParams struct {
	UserID string `json:"user_id"`
	OrgID  string `json:"org_id"`
}

func (q *Queries) GetLocalAuthMembershipForUserOrg(ctx context.Context, arg GetLocalAuthMembershipForUserOrgParams) (LocalAuthMembership, error) {
	row := q.db.QueryRow(ctx, getLocalAuthMembershipForUserOrg, arg.UserID, arg.OrgID)
	var i LocalAuthMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.RoleSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthOrg = `-- name: GetLocalAuthOrg :one
SELECT id, name, created_at, updated_at
FROM local_auth_orgs
WHERE id = $1
`

func (q *Queries) GetLocalAuthOrg(ctx context.Context, id string) (LocalAuthOrg, error) {
	row := q.db.QueryRow(ctx, getLocalAuthOrg, id)
	var i LocalAuthOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthSession = `-- name: GetLocalAuthSession :one
SELECT
    s.id,
    s.user_id,
    s.token_hash,
    s.active_org_id,
    s.expires_at,
    s.last_seen_at,
    s.created_at,
    u.email,
    u.first_name,
    u.last_name,
    m.role_slug
FROM local_auth_sessions s
JOIN local_auth_users u ON u.id = s.user_id
LEFT JOIN local_auth_memberships m
    ON m.user_id = s.user_id
   AND m.org_id = s.active_org_id
WHERE s.id = $1
  AND s.expires_at > NOW()
`

type GetLocalAuthSessionRow struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	TokenHash   []byte             `json:"token_hash"`
	ActiveOrgID *string            `json:"active_org_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Email       string             `json:"email"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	RoleSlug    *string            `json:"role_slug"`
}

func (q *Queries) GetLocalAuthSession(ctx context.Context, id string) (GetLocalAuthSessionRow, error) {
	row := q.db.QueryRow(ctx, getLocalAuthSession, id)
	var i GetLocalAuthSessionRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ActiveOrgID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.RoleSlug,
	)
	return i, err
}

const getLocalAuthUserByEmail = `-- name: GetLocalAuthUserByEmail :one
SELECT id, email, email_normalized, password_hash, first_name, last_name, created_at, updated_at
FROM local_auth_users
WHERE email_normalized = $1
`

func (q *Queries) GetLocalAuthUserByEmail(ctx context.Context, emailNormalized string) (LocalAuthUser, error) {
	row := q.db.QueryRow(ctx, getLocalAuthUserByEmail, emailNormalized)
	var i LocalAuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLocalAuthUserByID = `-- name: GetLocalAuthUserByID :one
SELECT id, email, email_normalized, password_hash, first_name, last_name, created_at, updated_at
FROM local_auth_users
WHERE id = $1
`

func (q *Queries) GetLocalAuthUserByID(ctx context.Context, id string) (LocalAuthUser, error) {
	row := q.db.QueryRow(ctx, getLocalAuthUserByID, id)
	var i LocalAuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLocalAuthInvitations = `-- name: ListLocalAuthInvitations :many
SELECT id, org_id, email, email_normalized, role_slug, token_hash, expires_at, accepted_at, revoked_at, created_by, created_at, updated_at
FROM local_auth_invitations
WHERE org_id = $1
  AND accepted_at IS NULL
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY created_at DESC
`

func (q *Queries) ListLocalAuthInvitations(ctx context.Context, orgID string) ([]LocalAuthInvitation, error) {
	rows, err := q.db.Query(ctx, listLocalAuthInvitations, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalAuthInvitation
	for rows.Next() {
		var i LocalAuthInvitation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Email,
			&i.EmailNormalized,
			&i.RoleSlug,
			&i.TokenHash,
			&i.ExpiresAt,
			&i.AcceptedAt,
			&i.RevokedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalAuthMembers = `-- name: ListLocalAuthMembers :many
SELECT
    m.id AS membership_id,
    m.user_id,
    m.org_id,
    m.role_slug,
    u.email,
    u.first_name,
    u.last_name
FROM local_auth_memberships m
JOIN local_auth_users u ON u.id = m.user_id
WHERE m.org_id = $1
ORDER BY lower(u.email), u.id
`

type ListLocalAuthMembersRow struct {
	MembershipID string `json:"membership_id"`
	UserID       string `json:"user_id"`
	OrgID        string `json:"org_id"`
	RoleSlug     string `json:"role_slug"`
	Email        string `json:"email"`
	FirstName    string `json:"first_name"`
	LastName     string `json:"last_name"`
}

func (q *Queries) ListLocalAuthMembers(ctx context.Context, orgID string) ([]ListLocalAuthMembersRow, error) {
	rows, err := q.db.Query(ctx, listLocalAuthMembers, orgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocalAuthMembersRow
	for rows.Next() {
		var i ListLocalAuthMembersRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.OrgID,
			&i.RoleSlug,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalAuthUserOrgs = `-- name: ListLocalAuthUserOrgs :many
SELECT
    m.id AS membership_id,
    m.user_id,
    m.org_id,
    m.role_slug,
    o.name AS org_name
FROM local_auth_memberships m
JOIN local_auth_orgs o ON o.id = m.org_id
WHERE m.user_id = $1
ORDER BY o.name, o.id
`

type ListLocalAuthUserOrgsRow struct {
	MembershipID string `json:"membership_id"`
	UserID       string `json:"user_id"`
	OrgID        string `json:"org_id"`
	RoleSlug     string `json:"role_slug"`
	OrgName      string `json:"org_name"`
}

func (q *Queries) ListLocalAuthUserOrgs(ctx context.Context, userID string) ([]ListLocalAuthUserOrgsRow, error) {
	rows, err := q.db.Query(ctx, listLocalAuthUserOrgs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocalAuthUserOrgsRow
	for rows.Next() {
		var i ListLocalAuthUserOrgsRow
		if err := rows.Scan(
			&i.MembershipID,
			&i.UserID,
			&i.OrgID,
			&i.RoleSlug,
			&i.OrgName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeLocalAuthInvitation = `-- name: RevokeLocalAuthInvitation :exec
UPDATE local_auth_invitations
SET revoked_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND org_id = $2
  AND accepted_at IS NULL
  AND revoked_at IS NULL
`

type RevokeLocalAuthInvitationParams struct {
	ID    string `json:"id"`
	OrgID string `json:"org_id"`
}

func (q *Queries) RevokeLocalAuthInvitation(ctx context.Context, arg RevokeLocalAuthInvitationParams) error {
	_, err := q.db.Exec(ctx, revokeLocalAuthInvitation, arg.ID, arg.OrgID)
	return err
}

const touchLocalAuthSession = `-- name: TouchLocalAuthSession :exec
UPDATE local_auth_sessions
SET last_seen_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchLocalAuthSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchLocalAuthSession, id)
	return err
}

const updateLocalAuthMembershipRole = `-- name: UpdateLocalAuthMembershipRole :one
UPDATE local_auth_memberships
SET role_slug = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, org_id, role_slug, created_at, updated_at
`

type UpdateLocalAuthMembershipRoleParams struct {
	ID       string `json:"id"`
	RoleSlug string `json:"role_slug"`
}

func (q *Queries) UpdateLocalAuthMembershipRole(ctx context.Context, arg UpdateLocalAuthMembershipRoleParams) (LocalAuthMembership, error) {
	row := q.db.QueryRow(ctx, updateLocalAuthMembershipRole, arg.ID, arg.RoleSlug)
	var i LocalAuthMembership
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.OrgID,
		&i.RoleSlug,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocalAuthOrgName = `-- name: UpdateLocalAuthOrgName :one
UPDATE local_auth_orgs
SET name = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, created_at, updated_at
`

type UpdateLocalAuthOrgNameParams struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateLocalAuthOrgName(ctx context.Context, arg UpdateLocalAuthOrgNameParams) (LocalAuthOrg, error) {
	row := q.db.QueryRow(ctx, updateLocalAuthOrgName, arg.ID, arg.Name)
	var i LocalAuthOrg
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLocalAuthSessionOrg = `-- name: UpdateLocalAuthSessionOrg :one
UPDATE local_auth_sessions
SET active_org_id = $2,
    last_seen_at = NOW()
WHERE id = $1
RETURNING id, user_id, token_hash, active_org_id, expires_at, last_seen_at, created_at
`

type UpdateLocalAuthSessionOrgParams struct {
	ID          string  `json:"id"`
	ActiveOrgID *string `json:"active_org_id"`
}

func (q *Queries) UpdateLocalAuthSessionOrg(ctx context.Context, arg UpdateLocalAuthSessionOrgParams) (LocalAuthSession, error) {
	row := q.db.QueryRow(ctx, updateLocalAuthSessionOrg, arg.ID, arg.ActiveOrgID)
	var i LocalAuthSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ActiveOrgID,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const updateLocalAuthUserPassword = `-- name: UpdateLocalAuthUserPassword :exec
UPDATE local_auth_users
SET password_hash = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateLocalAuthUserPasswordParams struct {
	ID           string `json:"id"`
	PasswordHash []byte `json:"password_hash"`
}

func (q *Queries) UpdateLocalAuthUserPassword(ctx context.Context, arg UpdateLocalAuthUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateLocalAuthUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateLocalAuthUserProfile = `-- name: UpdateLocalAuthUserProfile :one
UPDATE local_auth_users
SET first_name = $2,
    last_name = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, email, email_normalized, password_hash, first_name, last_name, created_at, updated_at
`

type UpdateLocalAuthUserProfileParams struct {
	ID        string `json:"id"`
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
}

func (q *Queries) UpdateLocalAuthUserProfile(ctx context.Context, arg UpdateLocalAuthUserProfileParams) (LocalAuthUser, error) {
	row := q.db.QueryRow(ctx, updateLocalAuthUserProfile, arg.ID, arg.FirstName, arg.LastName)
	var i LocalAuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.PasswordHash,
		&i.FirstName,
		&i.LastName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
