// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentJob struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Name            string             `json:"name"`
	Definition      string             `json:"definition"`
	AgentSlug       string             `json:"agent_slug"`
	PrimaryOwner    string             `json:"primary_owner"`
	PrimaryRepo     string             `json:"primary_repo"`
	AdditionalRepos []byte             `json:"additional_repos"`
	CronSchedule    string             `json:"cron_schedule"`
	Timezone        string             `json:"timezone"`
	Enabled         bool               `json:"enabled"`
	NextRunAt       pgtype.Timestamptz `json:"next_run_at"`
	LastRunAt       pgtype.Timestamptz `json:"last_run_at"`
	LastRunID       *string            `json:"last_run_id"`
	LastError       string             `json:"last_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type AgentJobExecution struct {
	ID           string             `json:"id"`
	JobID        string             `json:"job_id"`
	OrgID        string             `json:"org_id"`
	RunID        *string            `json:"run_id"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Status       string             `json:"status"`
	ClaimedBy    string             `json:"claimed_by"`
	ClaimedAt    pgtype.Timestamptz `json:"claimed_at"`
	FinishedAt   pgtype.Timestamptz `json:"finished_at"`
	Error        string             `json:"error"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AgentProfile struct {
	ID                pgtype.UUID        `json:"id"`
	OrgID             string             `json:"org_id"`
	Slug              string             `json:"slug"`
	DisplayName       string             `json:"display_name"`
	Description       string             `json:"description"`
	SxBot             string             `json:"sx_bot"`
	PersonaAsset      string             `json:"persona_asset"`
	PersonaPrompt     string             `json:"persona_prompt"`
	SlackAliases      []string           `json:"slack_aliases"`
	Enabled           bool               `json:"enabled"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	Skills            []string           `json:"skills"`
	BuiltIn           bool               `json:"built_in"`
	VaultBackend      string             `json:"vault_backend"`
	SxBotKeyEncrypted []byte             `json:"sx_bot_key_encrypted"`
	TemplateSlug      string             `json:"template_slug"`
	SyncStatus        string             `json:"sync_status"`
	SyncError         string             `json:"sync_error"`
}

type AgentProfileTemplate struct {
	Slug          string             `json:"slug"`
	DisplayName   string             `json:"display_name"`
	Description   string             `json:"description"`
	SxBot         string             `json:"sx_bot"`
	PersonaAsset  string             `json:"persona_asset"`
	PersonaPrompt string             `json:"persona_prompt"`
	SlackAliases  []string           `json:"slack_aliases"`
	Skills        []string           `json:"skills"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type AgentRun struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	ThreadID        string             `json:"thread_id"`
	RunKind         string             `json:"run_kind"`
	RequestID       string             `json:"request_id"`
	SandboxID       string             `json:"sandbox_id"`
	Branch          string             `json:"branch"`
	UserRequest     string             `json:"user_request"`
	SessionID       string             `json:"session_id"`
	CommandID       string             `json:"command_id"`
	CommandStartSeq int64              `json:"command_start_seq"`
	State           string             `json:"state"`
	LogCursor       int64              `json:"log_cursor"`
	NextEventSeq    int64              `json:"next_event_seq"`
	LeaseOwner      string             `json:"lease_owner"`
	LeaseExpiresAt  pgtype.Timestamptz `json:"lease_expires_at"`
	HeartbeatAt     pgtype.Timestamptz `json:"heartbeat_at"`
	LastError       string             `json:"last_error"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	CommandStep     string             `json:"command_step"`
	Outcome         string             `json:"outcome"`
	OutcomeDetail   []byte             `json:"outcome_detail"`
	QualityScore    *int32             `json:"quality_score"`
	TriggerSource   string             `json:"trigger_source"`
	JobID           *string            `json:"job_id"`
	JobExecutionID  *string            `json:"job_execution_id"`
}

type AgentRunEvent struct {
	RunID     string             `json:"run_id"`
	Seq       int64              `json:"seq"`
	Event     string             `json:"event"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BillingAccount struct {
	OrgID                  string             `json:"org_id"`
	StripeCustomerID       string             `json:"stripe_customer_id"`
	StripeSubscriptionID   string             `json:"stripe_subscription_id"`
	PlanCode               string             `json:"plan_code"`
	Status                 string             `json:"status"`
	CurrentPeriodStart     pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd       pgtype.Timestamptz `json:"current_period_end"`
	IncludedCredits        int32              `json:"included_credits"`
	IncludedCreditsUsed    int32              `json:"included_credits_used"`
	TopupCredits           int32              `json:"topup_credits"`
	MaxFlavor              string             `json:"max_flavor"`
	PerRunMaxCredits       int32              `json:"per_run_max_credits"`
	BillingExempt          bool               `json:"billing_exempt"`
	LastPaymentError       string             `json:"last_payment_error"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	PendingPlanCode        string             `json:"pending_plan_code"`
	PendingPlanEffectiveAt pgtype.Timestamptz `json:"pending_plan_effective_at"`
}

type BillingCreditReservation struct {
	RunID               string             `json:"run_id"`
	OrgID               string             `json:"org_id"`
	ReservedCredits     int32              `json:"reserved_credits"`
	FromIncludedCredits int32              `json:"from_included_credits"`
	FromTopupCredits    int32              `json:"from_topup_credits"`
	CapturedCredits     int32              `json:"captured_credits"`
	ReleasedCredits     int32              `json:"released_credits"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type BillingRunMeter struct {
	RunID            string             `json:"run_id"`
	OrgID            string             `json:"org_id"`
	Flavor           string             `json:"flavor"`
	Multiplier       int32              `json:"multiplier"`
	SandboxVcpu      int32              `json:"sandbox_vcpu"`
	SandboxMemoryGib int32              `json:"sandbox_memory_gib"`
	SandboxDiskGib   int32              `json:"sandbox_disk_gib"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	EndedAt          pgtype.Timestamptz `json:"ended_at"`
	BillableMinutes  int32              `json:"billable_minutes"`
	CapturedCredits  int32              `json:"captured_credits"`
	TerminalState    string             `json:"terminal_state"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type BillingStripeEvent struct {
	EventID   string             `json:"event_id"`
	EventType string             `json:"event_type"`
	OrgID     string             `json:"org_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type BillingTopupSetting struct {
	OrgID                 string             `json:"org_id"`
	AutoTopupEnabled      bool               `json:"auto_topup_enabled"`
	TriggerThreshold      int32              `json:"trigger_threshold"`
	TargetBalance         int32              `json:"target_balance"`
	MonthlyMaxUnits       int32              `json:"monthly_max_units"`
	MonthlyUnitsUsed      int32              `json:"monthly_units_used"`
	MonthlyAnchorMonth    string             `json:"monthly_anchor_month"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	MonthlyMaxCents       int32              `json:"monthly_max_cents"`
	MonthlySpendCentsUsed int32              `json:"monthly_spend_cents_used"`
}

type Conversation struct {
	OrgID            string             `json:"org_id"`
	ThreadID         string             `json:"thread_id"`
	SandboxID        string             `json:"sandbox_id"`
	Branch           string             `json:"branch"`
	PrUrl            string             `json:"pr_url"`
	History          []string           `json:"history"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	GithubOwner      string             `json:"github_owner"`
	GithubRepo       string             `json:"github_repo"`
	ResponseBlocks   [][]byte           `json:"response_blocks"`
	CustomTitle      string             `json:"custom_title"`
	CreatorID        string             `json:"creator_id"`
	AgentSlug        string             `json:"agent_slug"`
	Model            string             `json:"model"`
	TaskOptions      []byte             `json:"task_options"`
	PrState          string             `json:"pr_state"`
	PrMerged         bool               `json:"pr_merged"`
	PrMergedAt       pgtype.Timestamptz `json:"pr_merged_at"`
	PrClosedAt       pgtype.Timestamptz `json:"pr_closed_at"`
	PrStateCheckedAt pgtype.Timestamptz `json:"pr_state_checked_at"`
	AwaitingRepo     bool               `json:"awaiting_repo"`
}

type ConversationAttachment struct {
	ID          string             `json:"id"`
	OrgID       string             `json:"org_id"`
	ThreadID    string             `json:"thread_id"`
	TurnIndex   int32              `json:"turn_index"`
	Filename    string             `json:"filename"`
	ContentType string             `json:"content_type"`
	SizeBytes   int64              `json:"size_bytes"`
	Data        []byte             `json:"data"`
	Source      string             `json:"source"`
	SlackFileID string             `json:"slack_file_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type GithubAppInstallation struct {
	InstallationID int64              `json:"installation_id"`
	OrgID          string             `json:"org_id"`
	AccountLogin   string             `json:"account_login"`
	AccountType    string             `json:"account_type"`
	AccountID      int64              `json:"account_id"`
	SuspendedAt    pgtype.Timestamptz `json:"suspended_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type GithubRepo struct {
	InstallationID int64              `json:"installation_id"`
	RepoID         int64              `json:"repo_id"`
	Owner          string             `json:"owner"`
	Name           string             `json:"name"`
	DefaultBranch  string             `json:"default_branch"`
	Private        bool               `json:"private"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
}

type GithubTeam struct {
	InstallationID int64              `json:"installation_id"`
	TeamID         int64              `json:"team_id"`
	Slug           string             `json:"slug"`
	Name           string             `json:"name"`
	ParentTeamID   *int64             `json:"parent_team_id"`
	LastSyncedAt   pgtype.Timestamptz `json:"last_synced_at"`
}

type GithubTeamMember struct {
	InstallationID int64  `json:"installation_id"`
	TeamID         int64  `json:"team_id"`
	GithubUserID   int64  `json:"github_user_id"`
	GithubLogin    string `json:"github_login"`
}

type LinearAgentSession struct {
	AgentSessionID  string             `json:"agent_session_id"`
	OrgID           string             `json:"org_id"`
	ThreadID        string             `json:"thread_id"`
	IssueID         string             `json:"issue_id"`
	IssueIdentifier string             `json:"issue_identifier"`
	IssueUrl        string             `json:"issue_url"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LocalAuthInvitation struct {
	ID              string             `json:"id"`
	OrgID           string             `json:"org_id"`
	Email           string             `json:"email"`
	EmailNormalized string             `json:"email_normalized"`
	RoleSlug        string             `json:"role_slug"`
	TokenHash       []byte             `json:"token_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt      pgtype.Timestamptz `json:"accepted_at"`
	RevokedAt       pgtype.Timestamptz `json:"revoked_at"`
	CreatedBy       *string            `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type LocalAuthMembership struct {
	ID        string             `json:"id"`
	UserID    string             `json:"user_id"`
	OrgID     string             `json:"org_id"`
	RoleSlug  string             `json:"role_slug"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LocalAuthOrg struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LocalAuthSession struct {
	ID          string             `json:"id"`
	UserID      string             `json:"user_id"`
	TokenHash   []byte             `json:"token_hash"`
	ActiveOrgID *string            `json:"active_org_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type LocalAuthUser struct {
	ID              string             `json:"id"`
	Email           string             `json:"email"`
	EmailNormalized string             `json:"email_normalized"`
	PasswordHash    []byte             `json:"password_hash"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrgApiKey struct {
	ID         string             `json:"id"`
	OrgID      string             `json:"org_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    []byte             `json:"key_hash"`
	CreatedBy  string             `json:"created_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type OrgConfig struct {
	OrgID                          string             `json:"org_id"`
	SlackBotTokenEncrypted         []byte             `json:"slack_bot_token_encrypted"`
	SlackSocketTokenEncrypted      []byte             `json:"slack_socket_token_encrypted"`
	SxKeyEncrypted                 []byte             `json:"sx_key_encrypted"`
	CreatedAt                      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                      pgtype.Timestamptz `json:"updated_at"`
	AnthropicApiKeyEncrypted       []byte             `json:"anthropic_api_key_encrypted"`
	SlackTeamID                    *string            `json:"slack_team_id"`
	DefaultGithubOwner             string             `json:"default_github_owner"`
	DefaultGithubRepo              string             `json:"default_github_repo"`
	ClaudeCodeOauthTokenEncrypted  []byte             `json:"claude_code_oauth_token_encrypted"`
	OpenaiApiKeyEncrypted          []byte             `json:"openai_api_key_encrypted"`
	OpenaiCodexOauthTokenEncrypted []byte             `json:"openai_codex_oauth_token_encrypted"`
	LinearAccessTokenEncrypted     []byte             `json:"linear_access_token_encrypted"`
	LinearWorkspaceID              *string            `json:"linear_workspace_id"`
	LinearAppUserID                string             `json:"linear_app_user_id"`
	GithubPatEncrypted             []byte             `json:"github_pat_encrypted"`
}

type OrgSxVault struct {
	OrgID                string             `json:"org_id"`
	Backend              string             `json:"backend"`
	GithubInstallationID *int64             `json:"github_installation_id"`
	GithubRepoID         int64              `json:"github_repo_id"`
	GithubOwner          string             `json:"github_owner"`
	GithubRepo           string             `json:"github_repo"`
	RepositoryUrl        string             `json:"repository_url"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type RepoBillingSetting struct {
	OrgID       string             `json:"org_id"`
	GithubOwner string             `json:"github_owner"`
	GithubRepo  string             `json:"github_repo"`
	Flavor      string             `json:"flavor"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type RepoSecretValue struct {
	ID             pgtype.UUID        `json:"id"`
	InstallationID int64              `json:"installation_id"`
	RepoID         int64              `json:"repo_id"`
	Path           string             `json:"path"`
	Name           string             `json:"name"`
	ValueEncrypted []byte             `json:"value_encrypted"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RepoSetupSpec struct {
	ID                   pgtype.UUID        `json:"id"`
	InstallationID       int64              `json:"installation_id"`
	RepoID               int64              `json:"repo_id"`
	Path                 string             `json:"path"`
	SpecVersion          int32              `json:"spec_version"`
	Kind                 string             `json:"kind"`
	SetupScript          string             `json:"setup_script"`
	StartScript          string             `json:"start_script"`
	HealthCheck          string             `json:"health_check"`
	StopScript           *string            `json:"stop_script"`
	Services             []byte             `json:"services"`
	RequiredSecrets      []byte             `json:"required_secrets"`
	DeferredCapabilities []byte             `json:"deferred_capabilities"`
	SuggestedRepoChanges []byte             `json:"suggested_repo_changes"`
	SourceFingerprint    string             `json:"source_fingerprint"`
	ValidationStatus     string             `json:"validation_status"`
	LastValidatedAt      pgtype.Timestamptz `json:"last_validated_at"`
	SuccessCount         int32              `json:"success_count"`
	FailureCount         int32              `json:"failure_count"`
	BootstrapLog         *string            `json:"bootstrap_log"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	LessonsMd            string             `json:"lessons_md"`
	ValidationCapability []byte             `json:"validation_capability"`
	BootstrapGeneration  int32              `json:"bootstrap_generation"`
}
