// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_configs.sql

package sqlc

import (
	"context"
)

const deleteAgentProfilesByOrg = `-- name: DeleteAgentProfilesByOrg :exec
DELETE FROM agent_profiles WHERE org_id = $1
`

func (q *Queries) DeleteAgentProfilesByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteAgentProfilesByOrg, orgID)
	return err
}

const deleteAgentRunsByOrg = `-- name: DeleteAgentRunsByOrg :exec
DELETE FROM agent_runs WHERE org_id = $1
`

// agent_run_events cascade-deletes via FK ON DELETE CASCADE.
func (q *Queries) DeleteAgentRunsByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteAgentRunsByOrg, orgID)
	return err
}

const deleteConversationsByOrg = `-- name: DeleteConversationsByOrg :exec
DELETE FROM conversations WHERE org_id = $1
`

func (q *Queries) DeleteConversationsByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteConversationsByOrg, orgID)
	return err
}

const deleteGithubInstallationsByOrg = `-- name: DeleteGithubInstallationsByOrg :exec
DELETE FROM github_app_installations WHERE org_id = $1
`

// github_repos / github_teams / github_team_members cascade via FK.
func (q *Queries) DeleteGithubInstallationsByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteGithubInstallationsByOrg, orgID)
	return err
}

const deleteOrgConfig = `-- name: DeleteOrgConfig :exec
DELETE FROM org_configs WHERE org_id = $1
`

func (q *Queries) DeleteOrgConfig(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteOrgConfig, orgID)
	return err
}

const deleteRepoSecretValuesByOrg = `-- name: DeleteRepoSecretValuesByOrg :exec
DELETE FROM repo_secret_values
WHERE installation_id IN (
    SELECT installation_id FROM github_app_installations WHERE org_id = $1
)
`

func (q *Queries) DeleteRepoSecretValuesByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteRepoSecretValuesByOrg, orgID)
	return err
}

const deleteRepoSetupSpecsByOrg = `-- name: DeleteRepoSetupSpecsByOrg :exec
DELETE FROM repo_setup_specs
WHERE installation_id IN (
    SELECT installation_id FROM github_app_installations WHERE org_id = $1
)
`

// repo_setup_specs are not FK-tied to github_app_installations (specs
// are user-visible work that must survive cache invalidation), so an
// org deletion has to clear them explicitly via the installation join.
func (q *Queries) DeleteRepoSetupSpecsByOrg(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteRepoSetupSpecsByOrg, orgID)
	return err
}

const getOrgConfig = `-- name: GetOrgConfig :one
SELECT
    org_id,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id,
    default_github_owner,
    default_github_repo,
    claude_code_oauth_token_encrypted,
    openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted,
    linear_workspace_id,
    linear_app_user_id,
    github_pat_encrypted
FROM org_configs
WHERE org_id = $1
`

func (q *Queries) GetOrgConfig(ctx context.Context, orgID string) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, getOrgConfig, orgID)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
		&i.DefaultGithubOwner,
		&i.DefaultGithubRepo,
		&i.ClaudeCodeOauthTokenEncrypted,
		&i.OpenaiApiKeyEncrypted,
		&i.OpenaiCodexOauthTokenEncrypted,
		&i.LinearAccessTokenEncrypted,
		&i.LinearWorkspaceID,
		&i.LinearAppUserID,
		&i.GithubPatEncrypted,
	)
	return i, err
}

const getOrgConfigByLinearWorkspaceID = `-- name: GetOrgConfigByLinearWorkspaceID :one
SELECT
    org_id,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id,
    default_github_owner,
    default_github_repo,
    claude_code_oauth_token_encrypted,
    openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted,
    linear_workspace_id,
    linear_app_user_id,
    github_pat_encrypted
FROM org_configs
WHERE linear_workspace_id = $1
`

// Routes inbound Linear webhooks (organizationId at the payload root)
// to the owning org, mirroring GetOrgConfigBySlackTeamID.
func (q *Queries) GetOrgConfigByLinearWorkspaceID(ctx context.Context, linearWorkspaceID *string) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, getOrgConfigByLinearWorkspaceID, linearWorkspaceID)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
		&i.DefaultGithubOwner,
		&i.DefaultGithubRepo,
		&i.ClaudeCodeOauthTokenEncrypted,
		&i.OpenaiApiKeyEncrypted,
		&i.OpenaiCodexOauthTokenEncrypted,
		&i.LinearAccessTokenEncrypted,
		&i.LinearWorkspaceID,
		&i.LinearAppUserID,
		&i.GithubPatEncrypted,
	)
	return i, err
}

const getOrgConfigBySlackTeamID = `-- name: GetOrgConfigBySlackTeamID :one
SELECT
    org_id,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id,
    default_github_owner,
    default_github_repo,
    claude_code_oauth_token_encrypted,
    openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted,
    linear_workspace_id,
    linear_app_user_id,
    github_pat_encrypted
FROM org_configs
WHERE slack_team_id = $1
`

func (q *Queries) GetOrgConfigBySlackTeamID(ctx context.Context, slackTeamID *string) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, getOrgConfigBySlackTeamID, slackTeamID)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
		&i.DefaultGithubOwner,
		&i.DefaultGithubRepo,
		&i.ClaudeCodeOauthTokenEncrypted,
		&i.OpenaiApiKeyEncrypted,
		&i.OpenaiCodexOauthTokenEncrypted,
		&i.LinearAccessTokenEncrypted,
		&i.LinearWorkspaceID,
		&i.LinearAppUserID,
		&i.GithubPatEncrypted,
	)
	return i, err
}

const listOrgConfigsWithSlack = `-- name: ListOrgConfigsWithSlack :many
SELECT
    org_id,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id,
    default_github_owner,
    default_github_repo,
    claude_code_oauth_token_encrypted,
    openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted,
    linear_workspace_id,
    linear_app_user_id,
    github_pat_encrypted
FROM org_configs
WHERE slack_bot_token_encrypted IS NOT NULL
  AND slack_socket_token_encrypted IS NOT NULL
`

// Lists Socket-Mode-installed orgs only. The slackManager iterates
// this on startup to open one socket per org.
//
// Important: HTTP-mode orgs (OAuth-installed via /slack/oauth/callback)
// are intentionally excluded — the OAuth callback clears
// slack_socket_token_encrypted to make sure we don't try to keep a
// doomed socket alive for them. If you need "every org with any kind
// of Slack connection," write a different query — don't rename this
// one.
func (q *Queries) ListOrgConfigsWithSlack(ctx context.Context) ([]OrgConfig, error) {
	rows, err := q.db.Query(ctx, listOrgConfigsWithSlack)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgConfig
	for rows.Next() {
		var i OrgConfig
		if err := rows.Scan(
			&i.OrgID,
			&i.SlackBotTokenEncrypted,
			&i.SlackSocketTokenEncrypted,
			&i.SxKeyEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnthropicApiKeyEncrypted,
			&i.SlackTeamID,
			&i.DefaultGithubOwner,
			&i.DefaultGithubRepo,
			&i.ClaudeCodeOauthTokenEncrypted,
			&i.OpenaiApiKeyEncrypted,
			&i.OpenaiCodexOauthTokenEncrypted,
			&i.LinearAccessTokenEncrypted,
			&i.LinearWorkspaceID,
			&i.LinearAppUserID,
			&i.GithubPatEncrypted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrgConfig = `-- name: UpsertOrgConfig :one
INSERT INTO org_configs (
    org_id,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    anthropic_api_key_encrypted,
    slack_team_id,
    default_github_owner,
    default_github_repo,
    claude_code_oauth_token_encrypted,
    openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted,
    linear_workspace_id,
    linear_app_user_id,
    github_pat_encrypted
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15
)
ON CONFLICT (org_id) DO UPDATE SET
    slack_bot_token_encrypted          = EXCLUDED.slack_bot_token_encrypted,
    slack_socket_token_encrypted       = EXCLUDED.slack_socket_token_encrypted,
    sx_key_encrypted                   = EXCLUDED.sx_key_encrypted,
    anthropic_api_key_encrypted        = EXCLUDED.anthropic_api_key_encrypted,
    slack_team_id                      = EXCLUDED.slack_team_id,
    default_github_owner               = EXCLUDED.default_github_owner,
    default_github_repo                = EXCLUDED.default_github_repo,
    claude_code_oauth_token_encrypted  = EXCLUDED.claude_code_oauth_token_encrypted,
    openai_api_key_encrypted           = EXCLUDED.openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted = EXCLUDED.openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted      = EXCLUDED.linear_access_token_encrypted,
    linear_workspace_id                = EXCLUDED.linear_workspace_id,
    linear_app_user_id                 = EXCLUDED.linear_app_user_id,
    github_pat_encrypted               = EXCLUDED.github_pat_encrypted,
    updated_at                         = NOW()
RETURNING
    org_id,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id,
    default_github_owner,
    default_github_repo,
    claude_code_oauth_token_encrypted,
    openai_api_key_encrypted,
    openai_codex_oauth_token_encrypted,
    linear_access_token_encrypted,
    linear_workspace_id,
    linear_app_user_id,
    github_pat_encrypted
`

type UpsertOrgConfigParams struct {
	OrgID                          string  `json:"org_id"`
	SlackBotTokenEncrypted         []byte  `json:"slack_bot_token_encrypted"`
	SlackSocketTokenEncrypted      []byte  `json:"slack_socket_token_encrypted"`
	SxKeyEncrypted                 []byte  `json:"sx_key_encrypted"`
	AnthropicApiKeyEncrypted       []byte  `json:"anthropic_api_key_encrypted"`
	SlackTeamID                    *string `json:"slack_team_id"`
	DefaultGithubOwner             string  `json:"default_github_owner"`
	DefaultGithubRepo              string  `json:"default_github_repo"`
	ClaudeCodeOauthTokenEncrypted  []byte  `json:"claude_code_oauth_token_encrypted"`
	OpenaiApiKeyEncrypted          []byte  `json:"openai_api_key_encrypted"`
	OpenaiCodexOauthTokenEncrypted []byte  `json:"openai_codex_oauth_token_encrypted"`
	LinearAccessTokenEncrypted     []byte  `json:"linear_access_token_encrypted"`
	LinearWorkspaceID              *string `json:"linear_workspace_id"`
	LinearAppUserID                string  `json:"linear_app_user_id"`
	GithubPatEncrypted             []byte  `json:"github_pat_encrypted"`
}

func (q *Queries) UpsertOrgConfig(ctx context.Context, arg UpsertOrgConfigParams) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, upsertOrgConfig,
		arg.OrgID,
		arg.SlackBotTokenEncrypted,
		arg.SlackSocketTokenEncrypted,
		arg.SxKeyEncrypted,
		arg.AnthropicApiKeyEncrypted,
		arg.SlackTeamID,
		arg.DefaultGithubOwner,
		arg.DefaultGithubRepo,
		arg.ClaudeCodeOauthTokenEncrypted,
		arg.OpenaiApiKeyEncrypted,
		arg.OpenaiCodexOauthTokenEncrypted,
		arg.LinearAccessTokenEncrypted,
		arg.LinearWorkspaceID,
		arg.LinearAppUserID,
		arg.GithubPatEncrypted,
	)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
		&i.DefaultGithubOwner,
		&i.DefaultGithubRepo,
		&i.ClaudeCodeOauthTokenEncrypted,
		&i.OpenaiApiKeyEncrypted,
		&i.OpenaiCodexOauthTokenEncrypted,
		&i.LinearAccessTokenEncrypted,
		&i.LinearWorkspaceID,
		&i.LinearAppUserID,
		&i.GithubPatEncrypted,
	)
	return i, err
}
