// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: org_configs.sql

package sqlc

import (
	"context"
)

const getOrgConfig = `-- name: GetOrgConfig :one
SELECT
    org_id,
    github_token_encrypted,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    github_repo,
    github_base_branch,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id
FROM org_configs
WHERE org_id = $1
`

func (q *Queries) GetOrgConfig(ctx context.Context, orgID string) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, getOrgConfig, orgID)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.GithubTokenEncrypted,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.GithubRepo,
		&i.GithubBaseBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
	)
	return i, err
}

const getOrgConfigBySlackTeamID = `-- name: GetOrgConfigBySlackTeamID :one
SELECT
    org_id,
    github_token_encrypted,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    github_repo,
    github_base_branch,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id
FROM org_configs
WHERE slack_team_id = $1
`

func (q *Queries) GetOrgConfigBySlackTeamID(ctx context.Context, slackTeamID *string) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, getOrgConfigBySlackTeamID, slackTeamID)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.GithubTokenEncrypted,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.GithubRepo,
		&i.GithubBaseBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
	)
	return i, err
}

const listOrgConfigsWithSlack = `-- name: ListOrgConfigsWithSlack :many
SELECT
    org_id,
    github_token_encrypted,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    github_repo,
    github_base_branch,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id
FROM org_configs
WHERE slack_bot_token_encrypted IS NOT NULL
  AND slack_socket_token_encrypted IS NOT NULL
`

// Lists Socket-Mode-installed orgs only. The slackManager iterates
// this on startup to open one socket per org.
//
// Important: HTTP-mode orgs (OAuth-installed via /slack/oauth/callback)
// are intentionally excluded — the OAuth callback clears
// slack_socket_token_encrypted to make sure we don't try to keep a
// doomed socket alive for them. If you need "every org with any kind
// of Slack connection," write a different query — don't rename this
// one.
func (q *Queries) ListOrgConfigsWithSlack(ctx context.Context) ([]OrgConfig, error) {
	rows, err := q.db.Query(ctx, listOrgConfigsWithSlack)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrgConfig
	for rows.Next() {
		var i OrgConfig
		if err := rows.Scan(
			&i.OrgID,
			&i.GithubTokenEncrypted,
			&i.SlackBotTokenEncrypted,
			&i.SlackSocketTokenEncrypted,
			&i.SxKeyEncrypted,
			&i.GithubRepo,
			&i.GithubBaseBranch,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AnthropicApiKeyEncrypted,
			&i.SlackTeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOrgConfig = `-- name: UpsertOrgConfig :one
INSERT INTO org_configs (
    org_id,
    github_token_encrypted,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    github_repo,
    github_base_branch,
    anthropic_api_key_encrypted,
    slack_team_id
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
ON CONFLICT (org_id) DO UPDATE SET
    github_token_encrypted       = EXCLUDED.github_token_encrypted,
    slack_bot_token_encrypted    = EXCLUDED.slack_bot_token_encrypted,
    slack_socket_token_encrypted = EXCLUDED.slack_socket_token_encrypted,
    sx_key_encrypted             = EXCLUDED.sx_key_encrypted,
    anthropic_api_key_encrypted  = EXCLUDED.anthropic_api_key_encrypted,
    github_repo                  = EXCLUDED.github_repo,
    github_base_branch           = EXCLUDED.github_base_branch,
    slack_team_id                = EXCLUDED.slack_team_id,
    updated_at                   = NOW()
RETURNING
    org_id,
    github_token_encrypted,
    slack_bot_token_encrypted,
    slack_socket_token_encrypted,
    sx_key_encrypted,
    github_repo,
    github_base_branch,
    created_at,
    updated_at,
    anthropic_api_key_encrypted,
    slack_team_id
`

type UpsertOrgConfigParams struct {
	OrgID                     string  `json:"org_id"`
	GithubTokenEncrypted      []byte  `json:"github_token_encrypted"`
	SlackBotTokenEncrypted    []byte  `json:"slack_bot_token_encrypted"`
	SlackSocketTokenEncrypted []byte  `json:"slack_socket_token_encrypted"`
	SxKeyEncrypted            []byte  `json:"sx_key_encrypted"`
	GithubRepo                string  `json:"github_repo"`
	GithubBaseBranch          string  `json:"github_base_branch"`
	AnthropicApiKeyEncrypted  []byte  `json:"anthropic_api_key_encrypted"`
	SlackTeamID               *string `json:"slack_team_id"`
}

func (q *Queries) UpsertOrgConfig(ctx context.Context, arg UpsertOrgConfigParams) (OrgConfig, error) {
	row := q.db.QueryRow(ctx, upsertOrgConfig,
		arg.OrgID,
		arg.GithubTokenEncrypted,
		arg.SlackBotTokenEncrypted,
		arg.SlackSocketTokenEncrypted,
		arg.SxKeyEncrypted,
		arg.GithubRepo,
		arg.GithubBaseBranch,
		arg.AnthropicApiKeyEncrypted,
		arg.SlackTeamID,
	)
	var i OrgConfig
	err := row.Scan(
		&i.OrgID,
		&i.GithubTokenEncrypted,
		&i.SlackBotTokenEncrypted,
		&i.SlackSocketTokenEncrypted,
		&i.SxKeyEncrypted,
		&i.GithubRepo,
		&i.GithubBaseBranch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AnthropicApiKeyEncrypted,
		&i.SlackTeamID,
	)
	return i, err
}
