// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	InsertHealthCheck(ctx context.Context, note string) (HealthCheck, error)
	LatestHealthCheck(ctx context.Context) (HealthCheck, error)
}

var _ Querier = (*Queries)(nil)
