// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CountAgentProfilesByOrg(ctx context.Context, orgID string) (int64, error)
	DeleteConversation(ctx context.Context, arg DeleteConversationParams) error
	DeleteGithubInstallation(ctx context.Context, installationID int64) error
	DeleteGithubReposByInstallation(ctx context.Context, installationID int64) error
	// Used by the sync routine: after upserting the current set of repos,
	// delete anything that wasn't in the list (revoked access).
	DeleteGithubReposByInstallationExcept(ctx context.Context, arg DeleteGithubReposByInstallationExceptParams) error
	DeleteGithubTeamMembersForTeam(ctx context.Context, arg DeleteGithubTeamMembersForTeamParams) error
	DeleteGithubTeamsByInstallationExcept(ctx context.Context, arg DeleteGithubTeamsByInstallationExceptParams) error
	DeleteRepoSecretValue(ctx context.Context, arg DeleteRepoSecretValueParams) error
	DeleteRepoSetupSpec(ctx context.Context, arg DeleteRepoSetupSpecParams) error
	DisableAgentProfile(ctx context.Context, arg DisableAgentProfileParams) (int64, error)
	GetAgentProfileBySlug(ctx context.Context, arg GetAgentProfileBySlugParams) (GetAgentProfileBySlugRow, error)
	GetConversation(ctx context.Context, arg GetConversationParams) (GetConversationRow, error)
	GetGithubInstallation(ctx context.Context, installationID int64) (GithubAppInstallation, error)
	// Resolves an (owner, name) the user typed in chat to a concrete
	// (installation_id, repo_id, default_branch) for this org. If the same
	// repo is exposed via two installations we prefer the unsuspended one
	// and break the remaining tie deterministically by installation_id so
	// repeat calls return the same row (and the caller's cached token
	// stays warm).
	GetGithubRepoForOrg(ctx context.Context, arg GetGithubRepoForOrgParams) (GithubRepo, error)
	GetOrgConfig(ctx context.Context, orgID string) (OrgConfig, error)
	GetOrgConfigBySlackTeamID(ctx context.Context, slackTeamID *string) (OrgConfig, error)
	GetRepoSecretValue(ctx context.Context, arg GetRepoSecretValueParams) (RepoSecretValue, error)
	GetRepoSetupSpec(ctx context.Context, arg GetRepoSetupSpecParams) (RepoSetupSpec, error)
	// Used by DeclareRequiredSecret to register a placeholder row for a
	// secret the bootstrap manifest asked for. ON CONFLICT DO NOTHING is
	// the key distinction from UpsertRepoSecretValue: re-declaring a
	// secret on a re-bootstrap must NOT clobber a value the user already
	// filled in via the settings UI. Replaces a SELECT-then-INSERT pattern
	// whose race window allowed the user's value to be overwritten with
	// NULL when the user filled it in between the two statements.
	InsertRepoSecretValueIfAbsent(ctx context.Context, arg InsertRepoSecretValueIfAbsentParams) error
	ListAgentProfilesByOrg(ctx context.Context, orgID string) ([]ListAgentProfilesByOrgRow, error)
	ListGithubInstallationsByOrg(ctx context.Context, orgID string) ([]GithubAppInstallation, error)
	ListGithubReposByInstallation(ctx context.Context, installationID int64) ([]GithubRepo, error)
	// Every repo accessible to the given Hetchy org, across all of its
	// GitHub App installations. Powers the "default repo" picker and the
	// per-conversation repo selector.
	ListGithubReposByOrg(ctx context.Context, orgID string) ([]GithubRepo, error)
	ListGithubTeamMembers(ctx context.Context, arg ListGithubTeamMembersParams) ([]GithubTeamMember, error)
	ListGithubTeamsByInstallation(ctx context.Context, installationID int64) ([]GithubTeam, error)
	// Lists Socket-Mode-installed orgs only. The slackManager iterates
	// this on startup to open one socket per org.
	//
	// Important: HTTP-mode orgs (OAuth-installed via /slack/oauth/callback)
	// are intentionally excluded — the OAuth callback clears
	// slack_socket_token_encrypted to make sure we don't try to keep a
	// doomed socket alive for them. If you need "every org with any kind
	// of Slack connection," write a different query — don't rename this
	// one.
	ListOrgConfigsWithSlack(ctx context.Context) ([]OrgConfig, error)
	// Used by the bootstrap apply step to build the env block, and by the
	// settings UI to show which keys are filled in vs. blank.
	ListRepoSecretValues(ctx context.Context, arg ListRepoSecretValuesParams) ([]RepoSecretValue, error)
	// All paths for a given (installation, repo). Powers the monorepo UI
	// where the user can see every target Hetchy has bootstrapped under
	// one repository.
	ListRepoSetupSpecs(ctx context.Context, arg ListRepoSetupSpecsParams) ([]RepoSetupSpec, error)
	RenameConversation(ctx context.Context, arg RenameConversationParams) (int64, error)
	// Periodic mid-run snapshot used by chatPersister. Only writes the
	// handful of fields that change progressively as the agent emits
	// blocks (history + response_blocks + creator_id). The fields that
	// track terminal state (sandbox_id, branch, pr_url, github_owner,
	// github_repo) are deliberately left alone — their canonical values
	// are written by UpsertConversation at end-of-turn, and overwriting
	// them here mid-run would race the dispatcher into the wrong state
	// machine branch on a concurrent reload.
	//
	// Pure UPDATE. We rely on the dispatcher's entry-Upsert (in
	// HandleRequest, before runFreshAgent) to create the row with the
	// NOT NULL columns populated; if a tick fires before that landing
	// the UPDATE simply matches zero rows and silently no-ops, which is
	// the correct behaviour. An INSERT here would either need to know
	// sandbox_id (it doesn't) or break NOT NULL by default-empty —
	// neither is desirable, and the persister has no business creating
	// rows on its own.
	SaveConversationProgress(ctx context.Context, arg SaveConversationProgressParams) error
	// Backs the sidebar list. Filters by optional creator_id and an
	// optional case-insensitive substring match against either the
	// custom_title or the first user message (history[1] — Postgres
	// arrays are 1-indexed; out-of-range yields NULL, and NULL ILIKE
	// pattern is NULL, which evaluates as falsy in WHERE so an empty
	// history harmlessly fails to match).
	//
	// Pass empty strings to skip a filter; LIMIT/OFFSET drive the
	// "Load more" pager. The ESCAPE '\' clause makes the literal '\'
	// character the escape — caller is expected to backslash-escape
	// '%', '_' and '\' in the user-typed query so they read as
	// literals instead of pattern metacharacters.
	//
	// Ordering is by created_at descending (newest first) so a chat's
	// position in the sidebar stays stable as new turns land — replying
	// to an old chat never reshuffles the list, and a brand-new chat
	// lands on page 0 where the sidebar's offset=0 reload will see it.
	// thread_id breaks ties when two rows share the same created_at (common
	// for inserts within the same transaction, since NOW() returns
	// transaction-start time) so pagination stays deterministic.
	//
	// Caveat: LIMIT/OFFSET pagination is not snapshot-isolated. A new chat
	// inserted between a user's page-0 fetch and their "Load more" click
	// shifts every existing row down by one, so the OFFSET N request may
	// re-fetch the last row of the previous page or skip a row. Acceptable
	// at current per-org scale (tens to low hundreds). Future fix: keyset
	// pagination on (created_at, thread_id) — pass the last row's pair as
	// a cursor instead of an offset.
	//
	// Performance note: ILIKE '%foo%' is sequential scan territory
	// because no B-tree index can cover a leading-wildcard pattern.
	// Fine for the current per-org chat counts (tens to low hundreds);
	// when an org grows past a few thousand chats, switch to pg_trgm
	// + a GIN index on custom_title (and a generated column for
	// history[1]).
	SearchConversations(ctx context.Context, arg SearchConversationsParams) ([]SearchConversationsRow, error)
	SeedDefaultAgentProfilesForOrg(ctx context.Context, orgID string) error
	UpdateAgentProfileName(ctx context.Context, arg UpdateAgentProfileNameParams) (UpdateAgentProfileNameRow, error)
	// Lightweight status update used by the runtime apply path: bumps
	// success/failure counters and the validation_status without
	// rewriting the whole spec. Avoids re-encoding all the JSONB blobs on
	// every successful task.
	UpdateRepoSetupSpecStatus(ctx context.Context, arg UpdateRepoSetupSpecStatusParams) error
	UpsertAgentProfile(ctx context.Context, arg UpsertAgentProfileParams) (UpsertAgentProfileRow, error)
	UpsertConversation(ctx context.Context, arg UpsertConversationParams) (UpsertConversationRow, error)
	// Failing-bootstrap upsert. Diverges from UpsertRepoSetupSpec in two
	// ways: success_count is left untouched (we only ever write a failing
	// row, never reset successes), and failure_count is incremented on
	// conflict instead of replaced. This way "stop retrying after N
	// consecutive failures" guards built on failure_count actually trip,
	// and AutoHealPromptPreamble's "this is attempt N" framing stays
	// accurate across retries.
	UpsertFailingRepoSetupSpec(ctx context.Context, arg UpsertFailingRepoSetupSpecParams) (RepoSetupSpec, error)
	// Queries for the GitHub App installation cache: installations, the
	// repos they grant access to, and (for Organization installs) team
	// + membership snapshots.
	// The WHERE clause on the DO UPDATE is the SQL-level guard against
	// one Hetchy org silently rebinding another org's installation_id.
	// The Go-side pre-check covers the common case with a clean error;
	// this WHERE closes the TOCTOU window where two simultaneous installs
	// of the same installation_id from different orgs could race past the
	// pre-check. On a cross-org conflict the UPDATE doesn't fire and
	// RETURNING yields zero rows — callers must handle pgx.ErrNoRows.
	UpsertGithubInstallation(ctx context.Context, arg UpsertGithubInstallationParams) (GithubAppInstallation, error)
	UpsertGithubRepo(ctx context.Context, arg UpsertGithubRepoParams) error
	UpsertGithubTeam(ctx context.Context, arg UpsertGithubTeamParams) error
	UpsertGithubTeamMember(ctx context.Context, arg UpsertGithubTeamMemberParams) error
	UpsertOrgConfig(ctx context.Context, arg UpsertOrgConfigParams) (OrgConfig, error)
	// Repo-scoped secrets ---------------------------------------------------
	// Inserts a placeholder row (value_encrypted=NULL) when bootstrap
	// declares a required secret, and updates the encrypted value when the
	// user fills it in via the settings UI. Two-phase so the UI knows what
	// to ask for even before the user types anything.
	UpsertRepoSecretValue(ctx context.Context, arg UpsertRepoSecretValueParams) error
	// Queries for repo bootstrap specs and per-repo secret values.
	UpsertRepoSetupSpec(ctx context.Context, arg UpsertRepoSetupSpecParams) (RepoSetupSpec, error)
}

var _ Querier = (*Queries)(nil)
