// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repo_bootstrap.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRepoSecretValue = `-- name: DeleteRepoSecretValue :exec
DELETE FROM repo_secret_values
WHERE installation_id = $1 AND repo_id = $2 AND path = $3 AND name = $4
`

type DeleteRepoSecretValueParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
	Name           string `json:"name"`
}

func (q *Queries) DeleteRepoSecretValue(ctx context.Context, arg DeleteRepoSecretValueParams) error {
	_, err := q.db.Exec(ctx, deleteRepoSecretValue,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.Name,
	)
	return err
}

const deleteRepoSetupSpec = `-- name: DeleteRepoSetupSpec :exec
DELETE FROM repo_setup_specs
WHERE installation_id = $1 AND repo_id = $2 AND path = $3
`

type DeleteRepoSetupSpecParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
}

func (q *Queries) DeleteRepoSetupSpec(ctx context.Context, arg DeleteRepoSetupSpecParams) error {
	_, err := q.db.Exec(ctx, deleteRepoSetupSpec, arg.InstallationID, arg.RepoID, arg.Path)
	return err
}

const getRepoSecretValue = `-- name: GetRepoSecretValue :one
SELECT id, installation_id, repo_id, path, name, value_encrypted, created_at, updated_at FROM repo_secret_values
WHERE installation_id = $1 AND repo_id = $2 AND path = $3 AND name = $4
`

type GetRepoSecretValueParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
	Name           string `json:"name"`
}

func (q *Queries) GetRepoSecretValue(ctx context.Context, arg GetRepoSecretValueParams) (RepoSecretValue, error) {
	row := q.db.QueryRow(ctx, getRepoSecretValue,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.Name,
	)
	var i RepoSecretValue
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.RepoID,
		&i.Path,
		&i.Name,
		&i.ValueEncrypted,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoSetupSpec = `-- name: GetRepoSetupSpec :one
SELECT id, installation_id, repo_id, path, spec_version, kind, setup_script, start_script, health_check, stop_script, services, required_secrets, deferred_capabilities, suggested_repo_changes, source_fingerprint, validation_status, last_validated_at, success_count, failure_count, bootstrap_log, created_at, updated_at FROM repo_setup_specs
WHERE installation_id = $1 AND repo_id = $2 AND path = $3
`

type GetRepoSetupSpecParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
}

func (q *Queries) GetRepoSetupSpec(ctx context.Context, arg GetRepoSetupSpecParams) (RepoSetupSpec, error) {
	row := q.db.QueryRow(ctx, getRepoSetupSpec, arg.InstallationID, arg.RepoID, arg.Path)
	var i RepoSetupSpec
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.RepoID,
		&i.Path,
		&i.SpecVersion,
		&i.Kind,
		&i.SetupScript,
		&i.StartScript,
		&i.HealthCheck,
		&i.StopScript,
		&i.Services,
		&i.RequiredSecrets,
		&i.DeferredCapabilities,
		&i.SuggestedRepoChanges,
		&i.SourceFingerprint,
		&i.ValidationStatus,
		&i.LastValidatedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.BootstrapLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertRepoSecretValueIfAbsent = `-- name: InsertRepoSecretValueIfAbsent :exec
INSERT INTO repo_secret_values (
    installation_id, repo_id, path, name, value_encrypted, updated_at
) VALUES (
    $1, $2, $3, $4, NULL, NOW()
)
ON CONFLICT (installation_id, repo_id, path, name) DO NOTHING
`

type InsertRepoSecretValueIfAbsentParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
	Name           string `json:"name"`
}

// Used by DeclareRequiredSecret to register a placeholder row for a
// secret the bootstrap manifest asked for. ON CONFLICT DO NOTHING is
// the key distinction from UpsertRepoSecretValue: re-declaring a
// secret on a re-bootstrap must NOT clobber a value the user already
// filled in via the settings UI. Replaces a SELECT-then-INSERT pattern
// whose race window allowed the user's value to be overwritten with
// NULL when the user filled it in between the two statements.
func (q *Queries) InsertRepoSecretValueIfAbsent(ctx context.Context, arg InsertRepoSecretValueIfAbsentParams) error {
	_, err := q.db.Exec(ctx, insertRepoSecretValueIfAbsent,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.Name,
	)
	return err
}

const listRepoSecretValues = `-- name: ListRepoSecretValues :many
SELECT id, installation_id, repo_id, path, name, value_encrypted, created_at, updated_at FROM repo_secret_values
WHERE installation_id = $1 AND repo_id = $2 AND path = $3
ORDER BY name
`

type ListRepoSecretValuesParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
}

// Used by the bootstrap apply step to build the env block, and by the
// settings UI to show which keys are filled in vs. blank.
func (q *Queries) ListRepoSecretValues(ctx context.Context, arg ListRepoSecretValuesParams) ([]RepoSecretValue, error) {
	rows, err := q.db.Query(ctx, listRepoSecretValues, arg.InstallationID, arg.RepoID, arg.Path)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSecretValue
	for rows.Next() {
		var i RepoSecretValue
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.Path,
			&i.Name,
			&i.ValueEncrypted,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepoSetupSpecs = `-- name: ListRepoSetupSpecs :many
SELECT id, installation_id, repo_id, path, spec_version, kind, setup_script, start_script, health_check, stop_script, services, required_secrets, deferred_capabilities, suggested_repo_changes, source_fingerprint, validation_status, last_validated_at, success_count, failure_count, bootstrap_log, created_at, updated_at FROM repo_setup_specs
WHERE installation_id = $1 AND repo_id = $2
ORDER BY path
`

type ListRepoSetupSpecsParams struct {
	InstallationID int64 `json:"installation_id"`
	RepoID         int64 `json:"repo_id"`
}

// All paths for a given (installation, repo). Powers the monorepo UI
// where the user can see every target Hetchy has bootstrapped under
// one repository.
func (q *Queries) ListRepoSetupSpecs(ctx context.Context, arg ListRepoSetupSpecsParams) ([]RepoSetupSpec, error) {
	rows, err := q.db.Query(ctx, listRepoSetupSpecs, arg.InstallationID, arg.RepoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoSetupSpec
	for rows.Next() {
		var i RepoSetupSpec
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.RepoID,
			&i.Path,
			&i.SpecVersion,
			&i.Kind,
			&i.SetupScript,
			&i.StartScript,
			&i.HealthCheck,
			&i.StopScript,
			&i.Services,
			&i.RequiredSecrets,
			&i.DeferredCapabilities,
			&i.SuggestedRepoChanges,
			&i.SourceFingerprint,
			&i.ValidationStatus,
			&i.LastValidatedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.BootstrapLog,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRepoSetupSpecStatus = `-- name: UpdateRepoSetupSpecStatus :exec
UPDATE repo_setup_specs SET
    validation_status = $4,
    last_validated_at = $5,
    success_count     = $6,
    failure_count     = $7,
    updated_at        = NOW()
WHERE installation_id = $1 AND repo_id = $2 AND path = $3
`

type UpdateRepoSetupSpecStatusParams struct {
	InstallationID   int64              `json:"installation_id"`
	RepoID           int64              `json:"repo_id"`
	Path             string             `json:"path"`
	ValidationStatus string             `json:"validation_status"`
	LastValidatedAt  pgtype.Timestamptz `json:"last_validated_at"`
	SuccessCount     int32              `json:"success_count"`
	FailureCount     int32              `json:"failure_count"`
}

// Lightweight status update used by the runtime apply path: bumps
// success/failure counters and the validation_status without
// rewriting the whole spec. Avoids re-encoding all the JSONB blobs on
// every successful task.
func (q *Queries) UpdateRepoSetupSpecStatus(ctx context.Context, arg UpdateRepoSetupSpecStatusParams) error {
	_, err := q.db.Exec(ctx, updateRepoSetupSpecStatus,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.ValidationStatus,
		arg.LastValidatedAt,
		arg.SuccessCount,
		arg.FailureCount,
	)
	return err
}

const upsertFailingRepoSetupSpec = `-- name: UpsertFailingRepoSetupSpec :one
INSERT INTO repo_setup_specs (
    installation_id, repo_id, path,
    spec_version, kind,
    setup_script, start_script, health_check, stop_script,
    services, required_secrets, deferred_capabilities, suggested_repo_changes,
    source_fingerprint,
    validation_status, last_validated_at,
    success_count, failure_count, bootstrap_log,
    updated_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14,
    $15, NULL,
    0, 1, $16,
    NOW()
)
ON CONFLICT (installation_id, repo_id, path) DO UPDATE SET
    spec_version           = EXCLUDED.spec_version,
    kind                   = EXCLUDED.kind,
    setup_script           = EXCLUDED.setup_script,
    start_script           = EXCLUDED.start_script,
    health_check           = EXCLUDED.health_check,
    stop_script            = EXCLUDED.stop_script,
    services               = EXCLUDED.services,
    required_secrets       = EXCLUDED.required_secrets,
    deferred_capabilities  = EXCLUDED.deferred_capabilities,
    suggested_repo_changes = EXCLUDED.suggested_repo_changes,
    source_fingerprint     = EXCLUDED.source_fingerprint,
    validation_status      = EXCLUDED.validation_status,
    failure_count          = repo_setup_specs.failure_count + 1,
    bootstrap_log          = EXCLUDED.bootstrap_log,
    updated_at             = NOW()
RETURNING id, installation_id, repo_id, path, spec_version, kind, setup_script, start_script, health_check, stop_script, services, required_secrets, deferred_capabilities, suggested_repo_changes, source_fingerprint, validation_status, last_validated_at, success_count, failure_count, bootstrap_log, created_at, updated_at
`

type UpsertFailingRepoSetupSpecParams struct {
	InstallationID       int64   `json:"installation_id"`
	RepoID               int64   `json:"repo_id"`
	Path                 string  `json:"path"`
	SpecVersion          int32   `json:"spec_version"`
	Kind                 string  `json:"kind"`
	SetupScript          string  `json:"setup_script"`
	StartScript          string  `json:"start_script"`
	HealthCheck          string  `json:"health_check"`
	StopScript           *string `json:"stop_script"`
	Services             []byte  `json:"services"`
	RequiredSecrets      []byte  `json:"required_secrets"`
	DeferredCapabilities []byte  `json:"deferred_capabilities"`
	SuggestedRepoChanges []byte  `json:"suggested_repo_changes"`
	SourceFingerprint    string  `json:"source_fingerprint"`
	ValidationStatus     string  `json:"validation_status"`
	BootstrapLog         *string `json:"bootstrap_log"`
}

// Failing-bootstrap upsert. Diverges from UpsertRepoSetupSpec in two
// ways: success_count is left untouched (we only ever write a failing
// row, never reset successes), and failure_count is incremented on
// conflict instead of replaced. This way "stop retrying after N
// consecutive failures" guards built on failure_count actually trip,
// and AutoHealPromptPreamble's "this is attempt N" framing stays
// accurate across retries.
func (q *Queries) UpsertFailingRepoSetupSpec(ctx context.Context, arg UpsertFailingRepoSetupSpecParams) (RepoSetupSpec, error) {
	row := q.db.QueryRow(ctx, upsertFailingRepoSetupSpec,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.SpecVersion,
		arg.Kind,
		arg.SetupScript,
		arg.StartScript,
		arg.HealthCheck,
		arg.StopScript,
		arg.Services,
		arg.RequiredSecrets,
		arg.DeferredCapabilities,
		arg.SuggestedRepoChanges,
		arg.SourceFingerprint,
		arg.ValidationStatus,
		arg.BootstrapLog,
	)
	var i RepoSetupSpec
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.RepoID,
		&i.Path,
		&i.SpecVersion,
		&i.Kind,
		&i.SetupScript,
		&i.StartScript,
		&i.HealthCheck,
		&i.StopScript,
		&i.Services,
		&i.RequiredSecrets,
		&i.DeferredCapabilities,
		&i.SuggestedRepoChanges,
		&i.SourceFingerprint,
		&i.ValidationStatus,
		&i.LastValidatedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.BootstrapLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRepoSecretValue = `-- name: UpsertRepoSecretValue :exec

INSERT INTO repo_secret_values (
    installation_id, repo_id, path, name, value_encrypted, updated_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
ON CONFLICT (installation_id, repo_id, path, name) DO UPDATE SET
    value_encrypted = EXCLUDED.value_encrypted,
    updated_at      = NOW()
`

type UpsertRepoSecretValueParams struct {
	InstallationID int64  `json:"installation_id"`
	RepoID         int64  `json:"repo_id"`
	Path           string `json:"path"`
	Name           string `json:"name"`
	ValueEncrypted []byte `json:"value_encrypted"`
}

// Repo-scoped secrets ---------------------------------------------------
// Inserts a placeholder row (value_encrypted=NULL) when bootstrap
// declares a required secret, and updates the encrypted value when the
// user fills it in via the settings UI. Two-phase so the UI knows what
// to ask for even before the user types anything.
func (q *Queries) UpsertRepoSecretValue(ctx context.Context, arg UpsertRepoSecretValueParams) error {
	_, err := q.db.Exec(ctx, upsertRepoSecretValue,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.Name,
		arg.ValueEncrypted,
	)
	return err
}

const upsertRepoSetupSpec = `-- name: UpsertRepoSetupSpec :one

INSERT INTO repo_setup_specs (
    installation_id, repo_id, path,
    spec_version, kind,
    setup_script, start_script, health_check, stop_script,
    services, required_secrets, deferred_capabilities, suggested_repo_changes,
    source_fingerprint,
    validation_status, last_validated_at,
    success_count, failure_count, bootstrap_log,
    updated_at
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8, $9,
    $10, $11, $12, $13,
    $14,
    $15, $16,
    $17, $18, $19,
    NOW()
)
ON CONFLICT (installation_id, repo_id, path) DO UPDATE SET
    spec_version           = EXCLUDED.spec_version,
    kind                   = EXCLUDED.kind,
    setup_script           = EXCLUDED.setup_script,
    start_script           = EXCLUDED.start_script,
    health_check           = EXCLUDED.health_check,
    stop_script            = EXCLUDED.stop_script,
    services               = EXCLUDED.services,
    required_secrets       = EXCLUDED.required_secrets,
    deferred_capabilities  = EXCLUDED.deferred_capabilities,
    suggested_repo_changes = EXCLUDED.suggested_repo_changes,
    source_fingerprint     = EXCLUDED.source_fingerprint,
    validation_status      = EXCLUDED.validation_status,
    last_validated_at      = EXCLUDED.last_validated_at,
    success_count          = EXCLUDED.success_count,
    failure_count          = EXCLUDED.failure_count,
    bootstrap_log          = EXCLUDED.bootstrap_log,
    updated_at             = NOW()
RETURNING id, installation_id, repo_id, path, spec_version, kind, setup_script, start_script, health_check, stop_script, services, required_secrets, deferred_capabilities, suggested_repo_changes, source_fingerprint, validation_status, last_validated_at, success_count, failure_count, bootstrap_log, created_at, updated_at
`

type UpsertRepoSetupSpecParams struct {
	InstallationID       int64              `json:"installation_id"`
	RepoID               int64              `json:"repo_id"`
	Path                 string             `json:"path"`
	SpecVersion          int32              `json:"spec_version"`
	Kind                 string             `json:"kind"`
	SetupScript          string             `json:"setup_script"`
	StartScript          string             `json:"start_script"`
	HealthCheck          string             `json:"health_check"`
	StopScript           *string            `json:"stop_script"`
	Services             []byte             `json:"services"`
	RequiredSecrets      []byte             `json:"required_secrets"`
	DeferredCapabilities []byte             `json:"deferred_capabilities"`
	SuggestedRepoChanges []byte             `json:"suggested_repo_changes"`
	SourceFingerprint    string             `json:"source_fingerprint"`
	ValidationStatus     string             `json:"validation_status"`
	LastValidatedAt      pgtype.Timestamptz `json:"last_validated_at"`
	SuccessCount         int32              `json:"success_count"`
	FailureCount         int32              `json:"failure_count"`
	BootstrapLog         *string            `json:"bootstrap_log"`
}

// Queries for repo bootstrap specs and per-repo secret values.
func (q *Queries) UpsertRepoSetupSpec(ctx context.Context, arg UpsertRepoSetupSpecParams) (RepoSetupSpec, error) {
	row := q.db.QueryRow(ctx, upsertRepoSetupSpec,
		arg.InstallationID,
		arg.RepoID,
		arg.Path,
		arg.SpecVersion,
		arg.Kind,
		arg.SetupScript,
		arg.StartScript,
		arg.HealthCheck,
		arg.StopScript,
		arg.Services,
		arg.RequiredSecrets,
		arg.DeferredCapabilities,
		arg.SuggestedRepoChanges,
		arg.SourceFingerprint,
		arg.ValidationStatus,
		arg.LastValidatedAt,
		arg.SuccessCount,
		arg.FailureCount,
		arg.BootstrapLog,
	)
	var i RepoSetupSpec
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.RepoID,
		&i.Path,
		&i.SpecVersion,
		&i.Kind,
		&i.SetupScript,
		&i.StartScript,
		&i.HealthCheck,
		&i.StopScript,
		&i.Services,
		&i.RequiredSecrets,
		&i.DeferredCapabilities,
		&i.SuggestedRepoChanges,
		&i.SourceFingerprint,
		&i.ValidationStatus,
		&i.LastValidatedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.BootstrapLog,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
