// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sx_vaults.sql

package sqlc

import (
	"context"
)

const deleteOrgSXVault = `-- name: DeleteOrgSXVault :exec
DELETE FROM org_sx_vaults
WHERE org_id = $1
`

func (q *Queries) DeleteOrgSXVault(ctx context.Context, orgID string) error {
	_, err := q.db.Exec(ctx, deleteOrgSXVault, orgID)
	return err
}

const getOrgSXVault = `-- name: GetOrgSXVault :one
SELECT
    org_id,
    backend,
    github_installation_id,
    github_repo_id,
    github_owner,
    github_repo,
    repository_url,
    created_at,
    updated_at
FROM org_sx_vaults
WHERE org_id = $1
`

func (q *Queries) GetOrgSXVault(ctx context.Context, orgID string) (OrgSxVault, error) {
	row := q.db.QueryRow(ctx, getOrgSXVault, orgID)
	var i OrgSxVault
	err := row.Scan(
		&i.OrgID,
		&i.Backend,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOrgSXGitVault = `-- name: UpsertOrgSXGitVault :one
INSERT INTO org_sx_vaults (
    org_id,
    backend,
    github_installation_id,
    github_repo_id,
    github_owner,
    github_repo,
    repository_url
) VALUES (
    $1, 'github_git', $2, $3, $4, $5, $6
)
ON CONFLICT (org_id) DO UPDATE SET
    backend                = EXCLUDED.backend,
    github_installation_id = EXCLUDED.github_installation_id,
    github_repo_id         = EXCLUDED.github_repo_id,
    github_owner           = EXCLUDED.github_owner,
    github_repo            = EXCLUDED.github_repo,
    repository_url         = EXCLUDED.repository_url,
    updated_at             = NOW()
RETURNING
    org_id,
    backend,
    github_installation_id,
    github_repo_id,
    github_owner,
    github_repo,
    repository_url,
    created_at,
    updated_at
`

type UpsertOrgSXGitVaultParams struct {
	OrgID                string `json:"org_id"`
	GithubInstallationID *int64 `json:"github_installation_id"`
	GithubRepoID         int64  `json:"github_repo_id"`
	GithubOwner          string `json:"github_owner"`
	GithubRepo           string `json:"github_repo"`
	RepositoryUrl        string `json:"repository_url"`
}

func (q *Queries) UpsertOrgSXGitVault(ctx context.Context, arg UpsertOrgSXGitVaultParams) (OrgSxVault, error) {
	row := q.db.QueryRow(ctx, upsertOrgSXGitVault,
		arg.OrgID,
		arg.GithubInstallationID,
		arg.GithubRepoID,
		arg.GithubOwner,
		arg.GithubRepo,
		arg.RepositoryUrl,
	)
	var i OrgSxVault
	err := row.Scan(
		&i.OrgID,
		&i.Backend,
		&i.GithubInstallationID,
		&i.GithubRepoID,
		&i.GithubOwner,
		&i.GithubRepo,
		&i.RepositoryUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
