// Code generated by tools/gen_ecc_catalog; DO NOT EDIT.
package agents

var eccCatalogEntries = joinECCCatalogEntries(
	eccCatalogEntriesPart1,
	eccCatalogEntriesPart2,
	eccCatalogEntriesPart3,
)

func joinECCCatalogEntries(parts ...[]CatalogEntry) []CatalogEntry {
	total := 0
	for _, part := range parts {
		total += len(part)
	}
	out := make([]CatalogEntry, 0, total)
	for _, part := range parts {
		out = append(out, part...)
	}
	return out
}
