// Command gen_ecc_catalog generates Hetchy's built-in ECC agent catalog.
//
// Usage:
//
//	go run ./tools/gen_ecc_catalog /path/to/ECC
//
// The command writes internal/agents/ecc_catalog_*.go from the repo root.
package main

import (
	"bufio"
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	skillPathRE  = regexp.MustCompile(`\bskills?/([a-z0-9][a-z0-9-]*)`)
	skillLabelRE = regexp.MustCompile(`(?i)\bskills?\s*:\s*([a-z0-9][a-z0-9-]*)`)
)

type agentEntry struct {
	slug        string
	displayName string
	description string
	model       string
	tools       []string
	skills      []string
	prompt      string
}

// eccCatalogRepo currently points at a personal upstream. Before the next
// governance-sensitive catalog refresh, fork or transfer ECC to the sleuth-io
// org. Changing upstream requires updating this tool and regenerating
// internal/agents/ecc_catalog_*.go; do not edit only one place.
const eccCatalogRepo = "https://github.com/affaan-m/ECC.git"

const (
	generatedAgentsDir  = "internal/agents"
	catalogEntriesChunk = 25
)

type generatedFile struct {
	path   string
	source []byte
}

func main() {
	log.SetFlags(0)
	if len(os.Args) != 2 {
		log.Fatal("usage: gen_ecc_catalog /path/to/ECC")
	}
	root := os.Args[1]
	ref := gitRef(root)
	archiveURL := strings.TrimSuffix(eccCatalogRepo, ".git") + "/archive/" + ref + ".tar.gz"
	archiveHash := ""
	if ref != "unknown" {
		archiveHash = archiveSHA256(archiveURL)
	}
	skills := skillNames(filepath.Join(root, "skills"))
	agents := agentEntries(filepath.Join(root, "agents"), skills)

	files, err := generatedCatalogFiles(agents, ref, archiveURL, archiveHash, catalogEntriesChunk)
	if err != nil {
		log.Fatal(err)
	}
	if err := writeGeneratedFiles(files); err != nil {
		log.Fatal(err)
	}
}

func generatedCatalogFiles(agents []agentEntry, ref, archiveURL, archiveHash string, entriesPerFile int) ([]generatedFile, error) {
	if entriesPerFile <= 0 {
		return nil, errors.New("entries per file must be positive")
	}
	files := make([]generatedFile, 0, 2+(len(agents)+entriesPerFile-1)/entriesPerFile)
	constants, err := formatGeneratedFile(filepath.Join(generatedAgentsDir, "ecc_catalog_generated.go"), catalogConstantsSource(ref, archiveURL, archiveHash))
	if err != nil {
		return nil, err
	}
	files = append(files, constants)

	partCount := (len(agents) + entriesPerFile - 1) / entriesPerFile
	index, err := formatGeneratedFile(filepath.Join(generatedAgentsDir, "ecc_catalog_entries_generated.go"), catalogEntriesIndexSource(partCount))
	if err != nil {
		return nil, err
	}
	files = append(files, index)

	for i := range partCount {
		start := i * entriesPerFile
		end := min(start+entriesPerFile, len(agents))
		path := filepath.Join(generatedAgentsDir, fmt.Sprintf("ecc_catalog_entries_part%d_generated.go", i+1))
		part, err := formatGeneratedFile(path, catalogEntriesPartSource(i+1, agents[start:end]))
		if err != nil {
			return nil, err
		}
		files = append(files, part)
	}
	return files, nil
}

func writeGeneratedFiles(files []generatedFile) error {
	if err := os.MkdirAll(generatedAgentsDir, 0o755); err != nil {
		return fmt.Errorf("create generated dir: %w", err)
	}
	stale, err := filepath.Glob(filepath.Join(generatedAgentsDir, "ecc_catalog_entries_part*_generated.go"))
	if err != nil {
		return fmt.Errorf("list stale generated chunks: %w", err)
	}
	for _, path := range stale {
		if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("remove stale generated chunk %s: %w", path, err)
		}
	}
	for _, file := range files {
		if err := os.WriteFile(file.path, file.source, 0o644); err != nil {
			return fmt.Errorf("write %s: %w", file.path, err)
		}
	}
	return nil
}

func formatGeneratedFile(path string, src []byte) (generatedFile, error) {
	out, err := format.Source(src)
	if err != nil {
		return generatedFile{}, fmt.Errorf("format %s: %w", path, err)
	}
	return generatedFile{path: path, source: out}, nil
}

func catalogConstantsSource(ref, archiveURL, archiveHash string) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by tools/gen_ecc_catalog; DO NOT EDIT.")
	fmt.Fprintln(&b, "package agents")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// The ECC built-in catalog is generated from an external public GitHub repo.")
	fmt.Fprintln(&b, "// Runtime installs use the commit-pinned archive URL below; catalog updates")
	fmt.Fprintln(&b, "// should review the upstream diff before regenerating this file.")
	fmt.Fprintln(&b, "// Current source is a personal upstream; fork or transfer it to sleuth-io")
	fmt.Fprintln(&b, "// before the next governance-sensitive refresh. Changing upstream requires")
	fmt.Fprintln(&b, "// updating tools/gen_ecc_catalog/main.go and regenerating the catalog files.")
	fmt.Fprintf(&b, "const ECCCatalogRepo = %q\n", eccCatalogRepo)
	fmt.Fprintf(&b, "const ECCCatalogRef = %q\n", ref)
	fmt.Fprintf(&b, "const ECCCatalogArchiveURL = %q\n", archiveURL)
	fmt.Fprintf(&b, "const ECCCatalogArchiveSHA256 = %q\n", archiveHash)
	return b.Bytes()
}

func catalogEntriesIndexSource(partCount int) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by tools/gen_ecc_catalog; DO NOT EDIT.")
	fmt.Fprintln(&b, "package agents")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "var eccCatalogEntries = joinECCCatalogEntries(")
	for i := 1; i <= partCount; i++ {
		fmt.Fprintf(&b, "eccCatalogEntriesPart%d,\n", i)
	}
	fmt.Fprintln(&b, ")")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "func joinECCCatalogEntries(parts ...[]CatalogEntry) []CatalogEntry {")
	fmt.Fprintln(&b, "total := 0")
	fmt.Fprintln(&b, "for _, part := range parts {")
	fmt.Fprintln(&b, "total += len(part)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "out := make([]CatalogEntry, 0, total)")
	fmt.Fprintln(&b, "for _, part := range parts {")
	fmt.Fprintln(&b, "out = append(out, part...)")
	fmt.Fprintln(&b, "}")
	fmt.Fprintln(&b, "return out")
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

func catalogEntriesPartSource(part int, agents []agentEntry) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by tools/gen_ecc_catalog; DO NOT EDIT.")
	fmt.Fprintln(&b, "package agents")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "var eccCatalogEntriesPart%d = []CatalogEntry{\n", part)
	for _, entry := range agents {
		writeCatalogEntry(&b, entry)
	}
	fmt.Fprintln(&b, "}")
	return b.Bytes()
}

func writeCatalogEntry(b *bytes.Buffer, entry agentEntry) {
	fmt.Fprintln(b, "{")
	fmt.Fprintf(b, "Slug: %q,\n", entry.slug)
	fmt.Fprintf(b, "DisplayName: %q,\n", entry.displayName)
	fmt.Fprintf(b, "Description: %q,\n", entry.description)
	fmt.Fprintf(b, "Model: %q,\n", entry.model)
	fmt.Fprintf(b, "Tools: %#v,\n", entry.tools)
	fmt.Fprintf(b, "RecommendedSkills: %#v,\n", entry.skills)
	fmt.Fprintf(b, "AgentPath: %q,\n", "agents/"+entry.slug+".md")
	fmt.Fprintf(b, "Prompt: %q,\n", entry.prompt)
	fmt.Fprintln(b, "},")
}

func gitRef(root string) string {
	head, err := os.ReadFile(filepath.Join(root, ".git", "HEAD"))
	if err == nil {
		headText := strings.TrimSpace(string(head))
		if refName, ok := strings.CutPrefix(headText, "ref: "); ok {
			refPath := filepath.Join(root, ".git", strings.TrimSpace(refName))
			if data, err := os.ReadFile(refPath); err == nil {
				return strings.TrimSpace(string(data))
			}
		}
		if headText != "" {
			return headText
		}
	}
	return "unknown"
}

func archiveSHA256(url string) string {
	resp, err := http.Get(url)
	if err != nil {
		log.Fatalf("download archive for sha256: %v", err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		log.Fatalf("download archive for sha256: %s", resp.Status)
	}
	hash := sha256.New()
	if _, err := io.Copy(hash, resp.Body); err != nil {
		log.Fatalf("hash archive: %v", err)
	}
	return hex.EncodeToString(hash.Sum(nil))
}

func skillNames(dir string) map[string]struct{} {
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("read skills dir: %v", err)
	}
	out := make(map[string]struct{}, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(dir, entry.Name(), "SKILL.md")); err == nil {
			out[entry.Name()] = struct{}{}
		}
	}
	return out
}

func agentEntries(dir string, skills map[string]struct{}) []agentEntry {
	files, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		log.Fatalf("list agents: %v", err)
	}
	sort.Strings(files)
	out := make([]agentEntry, 0, len(files))
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			log.Fatalf("read %s: %v", file, err)
		}
		front := frontmatter(raw)
		slug := strings.TrimSuffix(filepath.Base(file), ".md")
		if name := front["name"]; name != "" {
			slug = name
		}
		entry := agentEntry{
			slug:        slug,
			displayName: displayName(slug),
			description: front["description"],
			model:       front["model"],
			tools:       parseTools(front["tools"]),
			skills:      inferSkills(string(raw), skills),
			prompt:      strings.TrimSpace(string(raw)),
		}
		out = append(out, entry)
	}
	return out
}

func frontmatter(raw []byte) map[string]string {
	out := map[string]string{}
	scanner := bufio.NewScanner(bytes.NewReader(raw))
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return out
	}
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "---" {
			break
		}
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		out[strings.TrimSpace(key)] = strings.Trim(strings.TrimSpace(val), `"'`)
	}
	return out
}

func parseTools(value string) []string {
	value = strings.TrimSpace(value)
	value = strings.TrimPrefix(value, "[")
	value = strings.TrimSuffix(value, "]")
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.Trim(strings.TrimSpace(part), `"'`)
		if part != "" {
			out = append(out, part)
		}
	}
	return out
}

func inferSkills(content string, skills map[string]struct{}) []string {
	seen := map[string]struct{}{}
	add := func(name string) {
		name = strings.Trim(strings.TrimSpace(name), "`'\".,)")
		if _, ok := skills[name]; ok {
			seen[name] = struct{}{}
		}
	}
	for _, match := range skillPathRE.FindAllStringSubmatch(content, -1) {
		add(match[1])
	}
	for _, match := range skillLabelRE.FindAllStringSubmatch(content, -1) {
		add(match[1])
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func displayName(slug string) string {
	parts := strings.Split(slug, "-")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}
