// Command gen_ecc_catalog generates Hetchy's built-in ECC agent catalog.
//
// Usage:
//
//	go run ./tools/gen_ecc_catalog /path/to/ECC > internal/agents/ecc_catalog_generated.go
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

var (
	skillPathRE  = regexp.MustCompile(`\bskills?/([a-z0-9][a-z0-9-]*)`)
	skillLabelRE = regexp.MustCompile(`(?i)\bskills?\s*:\s*([a-z0-9][a-z0-9-]*)`)
)

type agentEntry struct {
	slug        string
	displayName string
	description string
	model       string
	tools       []string
	skills      []string
	prompt      string
}

func main() {
	log.SetFlags(0)
	if len(os.Args) != 2 {
		log.Fatal("usage: gen_ecc_catalog /path/to/ECC")
	}
	root := os.Args[1]
	ref := gitRef(root)
	skills := skillNames(filepath.Join(root, "skills"))
	agents := agentEntries(filepath.Join(root, "agents"), skills)

	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by tools/gen_ecc_catalog; DO NOT EDIT.")
	fmt.Fprintln(&b, "package agents")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "// The ECC built-in catalog is generated from an external public GitHub repo.")
	fmt.Fprintln(&b, "// Runtime installs use the commit-pinned archive URL below; catalog updates")
	fmt.Fprintln(&b, "// should review the upstream diff before regenerating this file.")
	fmt.Fprintf(&b, "const ECCCatalogRepo = %q\n", "https://github.com/affaan-m/ECC.git")
	fmt.Fprintf(&b, "const ECCCatalogRef = %q\n", ref)
	fmt.Fprintf(&b, "const ECCCatalogArchiveURL = %q\n", "https://github.com/affaan-m/ECC/archive/"+ref+".tar.gz")
	fmt.Fprintln(&b)
	fmt.Fprintln(&b, "var eccCatalogEntries = []CatalogEntry{")
	for _, entry := range agents {
		fmt.Fprintln(&b, "{")
		fmt.Fprintf(&b, "Slug: %q,\n", entry.slug)
		fmt.Fprintf(&b, "DisplayName: %q,\n", entry.displayName)
		fmt.Fprintf(&b, "Description: %q,\n", entry.description)
		fmt.Fprintf(&b, "Model: %q,\n", entry.model)
		fmt.Fprintf(&b, "Tools: %#v,\n", entry.tools)
		fmt.Fprintf(&b, "RecommendedSkills: %#v,\n", entry.skills)
		fmt.Fprintf(&b, "AgentPath: %q,\n", "agents/"+entry.slug+".md")
		fmt.Fprintf(&b, "Prompt: %q,\n", entry.prompt)
		fmt.Fprintln(&b, "},")
	}
	fmt.Fprintln(&b, "}")

	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format generated source: %v", err)
	}
	if _, err := os.Stdout.Write(out); err != nil {
		log.Fatal(err)
	}
}

func gitRef(root string) string {
	head, err := os.ReadFile(filepath.Join(root, ".git", "HEAD"))
	if err == nil {
		headText := strings.TrimSpace(string(head))
		if refName, ok := strings.CutPrefix(headText, "ref: "); ok {
			refPath := filepath.Join(root, ".git", strings.TrimSpace(refName))
			if data, err := os.ReadFile(refPath); err == nil {
				return strings.TrimSpace(string(data))
			}
		}
		if headText != "" {
			return headText
		}
	}
	return "unknown"
}

func skillNames(dir string) map[string]struct{} {
	entries, err := os.ReadDir(dir)
	if err != nil {
		log.Fatalf("read skills dir: %v", err)
	}
	out := make(map[string]struct{}, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if _, err := os.Stat(filepath.Join(dir, entry.Name(), "SKILL.md")); err == nil {
			out[entry.Name()] = struct{}{}
		}
	}
	return out
}

func agentEntries(dir string, skills map[string]struct{}) []agentEntry {
	files, err := filepath.Glob(filepath.Join(dir, "*.md"))
	if err != nil {
		log.Fatalf("list agents: %v", err)
	}
	sort.Strings(files)
	out := make([]agentEntry, 0, len(files))
	for _, file := range files {
		raw, err := os.ReadFile(file)
		if err != nil {
			log.Fatalf("read %s: %v", file, err)
		}
		front := frontmatter(raw)
		slug := strings.TrimSuffix(filepath.Base(file), ".md")
		if name := front["name"]; name != "" {
			slug = name
		}
		entry := agentEntry{
			slug:        slug,
			displayName: displayName(slug),
			description: front["description"],
			model:       front["model"],
			tools:       parseTools(front["tools"]),
			skills:      inferSkills(string(raw), skills),
			prompt:      strings.TrimSpace(string(raw)),
		}
		out = append(out, entry)
	}
	return out
}

func frontmatter(raw []byte) map[string]string {
	out := map[string]string{}
	scanner := bufio.NewScanner(bytes.NewReader(raw))
	if !scanner.Scan() || strings.TrimSpace(scanner.Text()) != "---" {
		return out
	}
	for scanner.Scan() {
		line := scanner.Text()
		if strings.TrimSpace(line) == "---" {
			break
		}
		key, val, ok := strings.Cut(line, ":")
		if !ok {
			continue
		}
		out[strings.TrimSpace(key)] = strings.Trim(strings.TrimSpace(val), `"'`)
	}
	return out
}

func parseTools(value string) []string {
	value = strings.TrimSpace(value)
	value = strings.TrimPrefix(value, "[")
	value = strings.TrimSuffix(value, "]")
	parts := strings.Split(value, ",")
	out := make([]string, 0, len(parts))
	for _, part := range parts {
		part = strings.Trim(strings.TrimSpace(part), `"'`)
		if part != "" {
			out = append(out, part)
		}
	}
	return out
}

func inferSkills(content string, skills map[string]struct{}) []string {
	seen := map[string]struct{}{}
	add := func(name string) {
		name = strings.Trim(strings.TrimSpace(name), "`'\".,)")
		if _, ok := skills[name]; ok {
			seen[name] = struct{}{}
		}
	}
	for _, match := range skillPathRE.FindAllStringSubmatch(content, -1) {
		add(match[1])
	}
	for _, match := range skillLabelRE.FindAllStringSubmatch(content, -1) {
		add(match[1])
	}
	out := make([]string, 0, len(seen))
	for name := range seen {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

func displayName(slug string) string {
	parts := strings.Split(slug, "-")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, " ")
}
